#!/usr/bin/env bash
# test-coverage-gate-script.sh — functional contract for scripts/test-coverage-gate.py.
#
# The write-tests skill treats this script as the EXECUTABLE coverage gate: the
# inventory is generated by the agent but approved only by this independent
# validator. A validator that accepts bad manifests would silently reopen the
# "42 green tests, 13 untouched methods" hole, so every reject path is proven
# here with a fixture, alongside the positive control.
#
# bash 3.2-compatible (macOS default). Accumulate-and-report, matching sibling
# skill-suite tests.
set -uo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
GATE="$ROOT/scripts/test-coverage-gate.py"
fail=0

pass() { printf 'PASS: %s\n' "$1"; }
bad()  { printf 'FAIL: %s\n' "$1"; fail=1; }

command -v python3 >/dev/null 2>&1 || { echo "SKIP: python3 not available"; exit 0; }
[ -f "$GATE" ] || { bad "scripts/test-coverage-gate.py does not exist"; exit 1; }

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# ── shared fixture: a python production file + a real test file ───────────────
mkdir -p "$TMP/src" "$TMP/tests"
cat > "$TMP/src/user_service.py" <<'EOF'
class UserService:
    def create(self, body):
        if not body:
            raise ValueError("empty body")
        return {"ok": True, "body": body}

    def find(self, uid):
        return {"id": uid}

def normalize(name):
    return name.strip().lower()
EOF

cat > "$TMP/tests/test_user_service.py" <<'EOF'
from src.user_service import UserService, normalize
import pytest

def test_create_returns_ok():
    assert UserService().create({"a": 1}) == {"ok": True, "body": {"a": 1}}

def test_create_empty_raises():
    with pytest.raises(ValueError, match="empty body"):
        UserService().create(None)

def test_find_returns_id():
    assert UserService().find("u1") == {"id": "u1"}

def test_normalize_strips_and_lowers():
    assert normalize("  MiXeD ") == "mixed"
EOF

SHA="$(python3 -c "import hashlib,sys;print(hashlib.sha256(open(sys.argv[1],'rb').read()).hexdigest())" "$TMP/src/user_service.py")"

# write_manifest <path> <sha> <extra-python-mutation>
# Builds the canonical PASSING manifest, then applies an optional mutation
# expression so each negative fixture isolates exactly one violation.
write_manifest() {
  python3 - "$1" "$2" "$3" <<'PY'
import hashlib, json, os, sys
path, sha, mutation = sys.argv[1], sys.argv[2], sys.argv[3]
_spec = "tests/test_user_service.py"
_spec_sha = hashlib.sha256(
    open(os.path.join(os.path.dirname(os.path.abspath(path)), _spec), "rb").read()).hexdigest()
m = {
  "schema": "zuvo-coverage-manifest/v1",
  "production_file": "src/user_service.py",
  "production_sha256": sha,
  "stack": "python",
  "test_files": ["tests/test_user_service.py"],
  "quality_gates": {"Q7": 1, "Q11": 1},
  "status": "final",
  "verification": {"schema": "zuvo-verify/v1", "epoch": 1,
                   "spec_sha256": {_spec: _spec_sha},
                   "suite": "PASS 4 tests passed", "mutation": "PASS 100.0%"},
  "symbols": [
    {"symbol": "UserService.create", "kind": "method", "visibility": "public",
     "production_lines": "2-5", "ownership": "owned", "rows": [
       {"id": "E1", "type": "entry", "description": "happy path returns ok",
        "coverage": "FULL", "evidence": "tests/test_user_service.py:4"},
       {"id": "B1", "type": "error_path", "description": "empty body raises ValueError",
        "coverage": "FULL", "evidence": "tests/test_user_service.py:7"}]},
    {"symbol": "UserService.find", "kind": "method", "visibility": "public",
     "production_lines": "7-8", "ownership": "owned", "rows": [
       {"id": "E1", "type": "entry", "description": "returns id dict",
        "coverage": "FULL", "evidence": "tests/test_user_service.py:11"}]},
    {"symbol": "normalize", "kind": "function", "visibility": "public",
     "production_lines": "10-11", "ownership": "owned", "rows": [
       {"id": "E1", "type": "entry", "description": "strips and lowercases",
        "coverage": "FULL", "evidence": "tests/test_user_service.py:14"}]}
  ]
}
if mutation:
    exec(mutation)
with open(path, "w") as f:
    json.dump(m, f)
PY
}

# run_gate <manifest> <phase> — echoes output; returns gate exit code
run_gate() {
  ( cd "$TMP" && python3 "$GATE" validate --manifest "$1" --phase "$2" --repo-root "$TMP" 2>&1 )
}

# ── 1. extract: python AST enumerates the public surface ──────────────────────
out="$(python3 "$GATE" extract --production "$TMP/src/user_service.py" 2>&1)"; rc=$?
if [ "$rc" -eq 0 ] && printf '%s' "$out" | grep -q '"UserService.create"' \
   && printf '%s' "$out" | grep -q '"normalize"' \
   && ! printf '%s' "$out" | grep -q '_private'; then
  pass "extract enumerates public python symbols via ast (exit 0)"
else
  bad "extract enumerates public python symbols via ast (exit=$rc): $out"
fi

# ── 2. positive control: complete manifest passes ─────────────────────────────
write_manifest "$TMP/ok.json" "$SHA" ""
out="$(run_gate ok.json final)"; rc=$?
if [ "$rc" -eq 0 ] && printf '%s' "$out" | grep -q 'Uncovered owned rows: 0' \
   && printf '%s' "$out" | grep -q 'RESULT: PASS'; then
  pass "complete manifest PASSes with 'Uncovered owned rows: 0'"
else
  bad "complete manifest PASSes (exit=$rc): $out"
fi

# ── 3. missing symbol: manifest omits a real public function ──────────────────
write_manifest "$TMP/missing.json" "$SHA" "m['symbols'] = [s for s in m['symbols'] if s['symbol'] != 'normalize']"
out="$(run_gate missing.json final)"; rc=$?
if [ "$rc" -eq 1 ] && printf '%s' "$out" | grep -q 'MISSING SYMBOL: normalize'; then
  pass "omitted public symbol FAILs the gate by name"
else
  bad "omitted public symbol FAILs the gate (exit=$rc): $out"
fi

# ── 4. stale hash: production changed after freeze ────────────────────────────
write_manifest "$TMP/stale.json" "0000000000000000000000000000000000000000000000000000000000000000" ""
out="$(run_gate stale.json final)"; rc=$?
if [ "$rc" -eq 1 ] && printf '%s' "$out" | grep -q 'STALE INVENTORY'; then
  pass "production-hash mismatch FAILs as STALE INVENTORY"
else
  bad "production-hash mismatch FAILs (exit=$rc): $out"
fi

# ── 5. uncovered owned row cannot pass ────────────────────────────────────────
write_manifest "$TMP/none.json" "$SHA" "m['symbols'][0]['rows'][1]['coverage'] = 'NONE'"
out="$(run_gate none.json final)"; rc=$?
if [ "$rc" -eq 1 ] && printf '%s' "$out" | grep -q 'UNCOVERED OWNED ROW' \
   && printf '%s' "$out" | grep -q 'Uncovered owned rows: 1'; then
  pass "coverage=NONE on an owned row FAILs and is counted"
else
  bad "coverage=NONE on an owned row FAILs (exit=$rc): $out"
fi

# ── 6. Q7=0 blocks the gate ───────────────────────────────────────────────────
write_manifest "$TMP/q7.json" "$SHA" "m['quality_gates']['Q7'] = 0"
out="$(run_gate q7.json final)"; rc=$?
if [ "$rc" -eq 1 ] && printf '%s' "$out" | grep -q 'QUALITY GATE: Q7'; then
  pass "Q7=0 FAILs the gate"
else
  bad "Q7=0 FAILs the gate (exit=$rc): $out"
fi

# ── 7. duplicate evidence: one assertion cannot back two rows ─────────────────
write_manifest "$TMP/dup.json" "$SHA" "m['symbols'][1]['rows'][0]['evidence'] = 'tests/test_user_service.py:4'"
out="$(run_gate dup.json final)"; rc=$?
if [ "$rc" -eq 1 ] && printf '%s' "$out" | grep -q 'DUPLICATE EVIDENCE'; then
  pass "duplicate evidence line FAILs the gate"
else
  bad "duplicate evidence line FAILs (exit=$rc): $out"
fi

# ── 8. empty evidence on a FULL row ───────────────────────────────────────────
write_manifest "$TMP/empty.json" "$SHA" "m['symbols'][2]['rows'][0]['evidence'] = ''"
out="$(run_gate empty.json final)"; rc=$?
if [ "$rc" -eq 1 ] && printf '%s' "$out" | grep -q 'FULL with empty evidence'; then
  pass "empty evidence on a FULL row FAILs the gate"
else
  bad "empty evidence FAILs (exit=$rc): $out"
fi

# ── 9. evidence pointing at imports/setup (before first test decl) ────────────
write_manifest "$TMP/setup.json" "$SHA" "m['symbols'][2]['rows'][0]['evidence'] = 'tests/test_user_service.py:1'"
out="$(run_gate setup.json final)"; rc=$?
if [ "$rc" -eq 1 ] && printf '%s' "$out" | grep -q 'precedes the first test declaration'; then
  pass "evidence line before the first test declaration FAILs"
else
  bad "evidence-before-first-test FAILs (exit=$rc): $out"
fi

# ── 10. evidence line outside the file ────────────────────────────────────────
write_manifest "$TMP/oob.json" "$SHA" "m['symbols'][2]['rows'][0]['evidence'] = 'tests/test_user_service.py:9999'"
out="$(run_gate oob.json final)"; rc=$?
if [ "$rc" -eq 1 ] && printf '%s' "$out" | grep -q 'outside file'; then
  pass "evidence line outside the test file FAILs"
else
  bad "evidence line outside file FAILs (exit=$rc): $out"
fi

# ── 11. excused coverage requires a note ──────────────────────────────────────
write_manifest "$TMP/excuse.json" "$SHA" "m['symbols'][2]['rows'][0].update({'coverage': 'UNREACHABLE', 'evidence': ''})"
out="$(run_gate excuse.json final)"; rc=$?
if [ "$rc" -eq 1 ] && printf '%s' "$out" | grep -q 'requires a non-empty justification note'; then
  pass "UNREACHABLE without a note FAILs the gate"
else
  bad "UNREACHABLE without note FAILs (exit=$rc): $out"
fi

# ── 12. inventory phase: FULL before tests exist is a freeze violation ────────
write_manifest "$TMP/inv.json" "$SHA" "m['status'] = 'inventory'"
out="$(run_gate inv.json inventory)"; rc=$?
if [ "$rc" -eq 1 ] && printf '%s' "$out" | grep -q 'inventory is frozen BEFORE tests exist'; then
  pass "inventory phase rejects pre-claimed FULL coverage"
else
  bad "inventory phase rejects pre-claimed FULL (exit=$rc): $out"
fi

# ── 13. inventory phase positive: NONE-coverage rows freeze cleanly ───────────
write_manifest "$TMP/inv-ok.json" "$SHA" "
for s in m['symbols']:
    for r in s['rows']:
        r['coverage'] = ''
        r['evidence'] = ''
m['status'] = 'inventory'
"
out="$(run_gate inv-ok.json inventory)"; rc=$?
if [ "$rc" -eq 0 ] && printf '%s' "$out" | grep -q 'RESULT: PASS'; then
  pass "inventory freeze with unclaimed rows PASSes"
else
  bad "inventory freeze PASSes (exit=$rc): $out"
fi

# ── 14. TS without any AST toolchain → DEGRADED_PASS (exit 3), never full PASS ─
cat > "$TMP/src/widget.ts" <<'EOF'
export function renderWidget(x: number): string {
  return String(x);
}
EOF
cat > "$TMP/tests/widget.test.ts" <<'EOF'
import { renderWidget } from '../src/widget';
it('renders the number as string', () => {
  expect(renderWidget(4)).toBe('4');
});
EOF
TSSHA="$(python3 -c "import hashlib,sys;print(hashlib.sha256(open(sys.argv[1],'rb').read()).hexdigest())" "$TMP/src/widget.ts")"
python3 - "$TMP/ts.json" "$TSSHA" <<'PY'
import hashlib, json, os, sys
_spec = "tests/widget.test.ts"
_spec_sha = hashlib.sha256(
    open(os.path.join(os.path.dirname(os.path.abspath(sys.argv[1])), _spec), "rb").read()).hexdigest()
m = {
  "schema": "zuvo-coverage-manifest/v1",
  "production_file": "src/widget.ts",
  "production_sha256": sys.argv[2],
  "stack": "ts",
  "test_files": ["tests/widget.test.ts"],
  "quality_gates": {"Q7": 1, "Q11": 1},
  "status": "final",
  "verification": {"schema": "zuvo-verify/v1", "epoch": 1,
                   "spec_sha256": {_spec: _spec_sha},
                   "suite": "PASS 1 test passed", "mutation": "SKIP"},
  "symbols": [
    {"symbol": "renderWidget", "kind": "function", "visibility": "public",
     "production_lines": "1-3", "ownership": "owned", "rows": [
       {"id": "E1", "type": "entry", "description": "stringifies input",
        "coverage": "FULL", "evidence": "tests/widget.test.ts:3"}]}
  ]
}
with open(sys.argv[1], "w") as f:
    json.dump(m, f)
PY
# PATH stripped of node/npm so no AST toolchain is reachable → forced textual fallback.
out="$(cd "$TMP" && env PATH=/usr/bin:/bin ZUVO_TSC_PATH= python3 "$GATE" validate --manifest ts.json --phase final --repo-root "$TMP" 2>&1)"; rc=$?
if [ "$rc" -eq 3 ] && printf '%s' "$out" | grep -q 'DEGRADED_PASS'; then
  pass "textual-fallback extraction yields exit 3 DEGRADED_PASS, not full PASS"
else
  bad "textual fallback DEGRADED_PASS (exit=$rc): $out"
fi

# ── 15. test-name evidence: durable form validates and rejects bad names ──────
write_manifest "$TMP/name.json" "$SHA" "m['symbols'][2]['rows'][0]['evidence'] = 'tests/test_user_service.py::test_normalize_strips_and_lowers'"
out="$(run_gate name.json final)"; rc=$?
if [ "$rc" -eq 0 ] && printf '%s' "$out" | grep -q 'RESULT: PASS'; then
  pass "evidence by exact test name (path::name) PASSes"
else
  bad "evidence by exact test name PASSes (exit=$rc): $out"
fi

write_manifest "$TMP/badname.json" "$SHA" "m['symbols'][2]['rows'][0]['evidence'] = 'tests/test_user_service.py::test_does_not_exist'"
out="$(run_gate badname.json final)"; rc=$?
if [ "$rc" -eq 1 ] && printf '%s' "$out" | grep -q 'no test named'; then
  pass "nonexistent test name FAILs the gate"
else
  bad "nonexistent test name FAILs (exit=$rc): $out"
fi

# ── 16. refresh: converts line evidence to test-name form; still passes ───────
write_manifest "$TMP/refresh.json" "$SHA" ""
out="$( cd "$TMP" && python3 "$GATE" refresh --manifest refresh.json --repo-root "$TMP" 2>&1 )"; rc=$?
if [ "$rc" -eq 0 ] && printf '%s' "$out" | grep -q 'REFRESH: 4 evidence rows converted' \
   && grep -q 'tests/test_user_service.py::test_create_returns_ok' "$TMP/refresh.json"; then
  pass "refresh rewrites line evidence to durable test-name form"
else
  bad "refresh rewrites line evidence (exit=$rc): $out"
fi
out="$(run_gate refresh.json final)"; rc=$?
if [ "$rc" -eq 0 ] && printf '%s' "$out" | grep -q 'Uncovered owned rows: 0'; then
  pass "refreshed manifest still PASSes the final gate"
else
  bad "refreshed manifest still PASSes (exit=$rc): $out"
fi

# ── 17. normhash: formatter-only edits keep the hash, semantic edits change it ─
cat > "$TMP/norm-a.ts" <<'EOF'
export function add(a: number, b: number): number {
  // sum
  return a + b;
}
EOF
cat > "$TMP/norm-b.ts" <<'EOF'
export function add(a: number,
    b: number): number {
  /* reformatted */
  return a
    + b;
}
EOF
cat > "$TMP/norm-c.ts" <<'EOF'
export function add(a: number, b: number): number {
  return a - b;
}
EOF
ha="$(python3 "$GATE" normhash --file "$TMP/norm-a.ts")"
hb="$(python3 "$GATE" normhash --file "$TMP/norm-b.ts")"
hc="$(python3 "$GATE" normhash --file "$TMP/norm-c.ts")"
if [ -n "$ha" ] && [ "$ha" = "$hb" ]; then
  pass "normhash: comment/whitespace/line-wrap churn keeps the hash"
else
  bad "normhash: formatter-only churn keeps the hash ($ha vs $hb)"
fi
if [ "$ha" != "$hc" ]; then
  pass "normhash: semantic edit changes the hash"
else
  bad "normhash: semantic edit changes the hash"
fi

# ── 18. usage errors exit 2 ───────────────────────────────────────────────────
python3 "$GATE" validate --manifest "$TMP/does-not-exist.json" >/dev/null 2>&1; rc=$?
if [ "$rc" -eq 2 ]; then
  pass "unreadable manifest exits 2 (usage/input error)"
else
  bad "unreadable manifest exits 2 (got $rc)"
fi

# ── 19. the receipt: a final manifest must prove it was measured ─────────────
# Measured on the benchmark rig across the whole corpus: roughly one run in three never executes
# the verification command at all. Not failing it — declining it, in as many words ("isn't
# practical to run in full here, I'll follow its core spine pragmatically"). The suite then ships
# unmeasured while the run reports success. Two rewordings of the instruction failed to move that,
# so the artifact carries the proof and this gate is what refuses it.
write_manifest "$TMP/noreceipt.json" "$SHA" "m.pop('verification', None)"
out="$(run_gate noreceipt.json final)"; rc=$?
if [ "$rc" -ne 0 ] && printf '%s' "$out" | grep -q 'UNVERIFIED'; then
  pass "final manifest without a verification receipt is REJECTED"
else
  bad "unmeasured suite accepted as final (exit=$rc): $out"
fi

# The hash is the load-bearing part: without it the receipt is a checkbox an earlier, different
# suite could have ticked.
write_manifest "$TMP/stale.json" "$SHA" "m['verification']['spec_sha256'][_spec] = '0'*64"
out="$(run_gate stale.json final)"; rc=$?
if [ "$rc" -ne 0 ] && printf '%s' "$out" | grep -q 'STALE RECEIPT'; then
  pass "a receipt that predates the current suite is REJECTED"
else
  bad "stale receipt accepted (exit=$rc): $out"
fi

# Inventory is frozen BEFORE any test exists, so demanding proof of measurement there would be
# demanding proof of something that has not happened yet.
write_manifest "$TMP/inv.json" "$SHA" "m.pop('verification', None); m['status'] = 'inventory'; [r.update(coverage='NONE') for sym in m['symbols'] for r in sym['rows']]"
out="$(run_gate inv.json inventory)"
printf '%s' "$out" | grep -q 'UNVERIFIED' \
  && bad "inventory phase demanded a receipt for tests that do not exist yet" \
  || pass "inventory phase does not demand a receipt"

# ── 20. scaffold: the inventory is generated, not transcribed ────────────────
# A 304-line file with 88 branches was abandoned in nine consecutive benchmark runs across three
# skill versions — no manifest was ever written, so the gate never ran. At ~90 hand-authored rows
# the runs were right that it was impractical. The generator has to produce something the
# validator then accepts, or it has moved the cliff instead of removing it.
out="$(cd "$TMP" && python3 "$GATE" scaffold --production src/user_service.py \
        --out zuvo/contracts/user_service.coverage.json \
        --test-files tests/test_user_service.py --repo-root "$TMP" 2>&1)"; rc=$?
if [ "$rc" -eq 0 ] && printf '%s' "$out" | grep -q 'SCAFFOLD:'; then
  pass "scaffold generates an inventory manifest in one command"
else
  bad "scaffold failed (exit=$rc): $out"
fi

# Round trip: what it writes must satisfy the validator it was generated for.
out="$(run_gate zuvo/contracts/user_service.coverage.json inventory)"; rc=$?
if [ "$rc" -eq 0 ] && printf '%s' "$out" | grep -q 'RESULT: PASS'; then
  pass "a generated inventory validates clean at inventory phase"
else
  bad "generated inventory rejected by the validator (exit=$rc): $out"
fi

# Every public symbol must be present — a generator that silently drops surface reopens exactly the
# hole the inventory exists to close.
if python3 -c "
import json,sys
m=json.load(open('$TMP/zuvo/contracts/user_service.coverage.json'))
names={s['symbol'] for s in m['symbols']}
sys.exit(0 if {'UserService.create','UserService.find','normalize'} <= names else 1)
"; then
  pass "scaffold covers every public symbol the extractor finds"
else
  bad "scaffold dropped public surface"
fi

# Boundary rows must land on the symbol that CONTAINS them, or the coverage question is asked of
# the wrong function.
if python3 -c "
import json,sys
m=json.load(open('$TMP/zuvo/contracts/user_service.coverage.json'))
create=[s for s in m['symbols'] if s['symbol']=='UserService.create'][0]
sys.exit(0 if any(r['type'] in ('branch','error_path') for r in create['rows']) else 1)
"; then
  pass "boundary rows attach to the symbol whose lines contain them"
else
  bad "boundaries were not attributed to their owning symbol"
fi

# It is an INVENTORY, frozen before tests exist: pre-claimed coverage would be the freeze violation
# case 12 already rejects.
if python3 -c "
import json,sys
m=json.load(open('$TMP/zuvo/contracts/user_service.coverage.json'))
sys.exit(0 if m['status']=='inventory' and all(r['coverage']=='NONE'
         for s in m['symbols'] for r in s['rows']) else 1)
"; then
  pass "scaffold freezes at coverage=NONE, claiming nothing"
else
  bad "scaffold pre-claimed coverage it cannot have"
fi

# Rows must come out in the MEASURED survival order the boundaries report uses, not source order.
# An agent working top-down through an alphabetical or line-ordered list spends its budget on
# equality rows while the throws — which survived 34 times in 39 suites — sit at the bottom.
if python3 -c "
import json,sys
m=json.load(open('$TMP/zuvo/contracts/user_service.coverage.json'))
create=[s for s in m['symbols'] if s['symbol']=='UserService.create'][0]
b=[r for r in create['rows'] if r['id'].startswith('B')]
sys.exit(0 if b and 'throw' in b[0]['description'] else 1)
"; then
  pass "boundary rows lead with the highest-risk kind, not with source order"
else
  bad "generated rows are not in measured survival order"
fi

# ── summary ───────────────────────────────────────────────────────────────────
echo "----"
if [ "$fail" -eq 0 ]; then
  echo "ALL PASSED"
  exit 0
fi
echo "SOME FAILED"
exit 1
