// MARKER-FILE-2
export function fn_2_1(a: number): number { return a * 2 + 1; } // pad pad pad pad pad
export function fn_2_2(a: number): number { return a * 2 + 2; } // pad pad pad pad pad
export function fn_2_3(a: number): number { return a * 2 + 3; } // pad pad pad pad pad
export function fn_2_4(a: number): number { return a * 2 + 4; } // pad pad pad pad pad
export function fn_2_5(a: number): number { return a * 2 + 5; } // pad pad pad pad pad
export function fn_2_6(a: number): number { return a * 2 + 6; } // pad pad pad pad pad
export function fn_2_7(a: number): number { return a * 2 + 7; } // pad pad pad pad pad
export function fn_2_8(a: number): number { return a * 2 + 8; } // pad pad pad pad pad
export function fn_2_9(a: number): number { return a * 2 + 9; } // pad pad pad pad pad
export function fn_2_10(a: number): number { return a * 2 + 10; } // pad pad pad pad pad
export function fn_2_11(a: number): number { return a * 2 + 11; } // pad pad pad pad pad
export function fn_2_12(a: number): number { return a * 2 + 12; } // pad pad pad pad pad
export function fn_2_13(a: number): number { return a * 2 + 13; } // pad pad pad pad pad
export function fn_2_14(a: number): number { return a * 2 + 14; } // pad pad pad pad pad
export function fn_2_15(a: number): number { return a * 2 + 15; } // pad pad pad pad pad
export function fn_2_16(a: number): number { return a * 2 + 16; } // pad pad pad pad pad
export function fn_2_17(a: number): number { return a * 2 + 17; } // pad pad pad pad pad
export function fn_2_18(a: number): number { return a * 2 + 18; } // pad pad pad pad pad
export function fn_2_19(a: number): number { return a * 2 + 19; } // pad pad pad pad pad
export function fn_2_20(a: number): number { return a * 2 + 20; } // pad pad pad pad pad
export function fn_2_21(a: number): number { return a * 2 + 21; } // pad pad pad pad pad
export function fn_2_22(a: number): number { return a * 2 + 22; } // pad pad pad pad pad
export function fn_2_23(a: number): number { return a * 2 + 23; } // pad pad pad pad pad
export function fn_2_24(a: number): number { return a * 2 + 24; } // pad pad pad pad pad
export function fn_2_25(a: number): number { return a * 2 + 25; } // pad pad pad pad pad
export function fn_2_26(a: number): number { return a * 2 + 26; } // pad pad pad pad pad
export function fn_2_27(a: number): number { return a * 2 + 27; } // pad pad pad pad pad
export function fn_2_28(a: number): number { return a * 2 + 28; } // pad pad pad pad pad
export function fn_2_29(a: number): number { return a * 2 + 29; } // pad pad pad pad pad
export function fn_2_30(a: number): number { return a * 2 + 30; } // pad pad pad pad pad
export function fn_2_31(a: number): number { return a * 2 + 31; } // pad pad pad pad pad
export function fn_2_32(a: number): number { return a * 2 + 32; } // pad pad pad pad pad
export function fn_2_33(a: number): number { return a * 2 + 33; } // pad pad pad pad pad
export function fn_2_34(a: number): number { return a * 2 + 34; } // pad pad pad pad pad
export function fn_2_35(a: number): number { return a * 2 + 35; } // pad pad pad pad pad
export function fn_2_36(a: number): number { return a * 2 + 36; } // pad pad pad pad pad
export function fn_2_37(a: number): number { return a * 2 + 37; } // pad pad pad pad pad
export function fn_2_38(a: number): number { return a * 2 + 38; } // pad pad pad pad pad
export function fn_2_39(a: number): number { return a * 2 + 39; } // pad pad pad pad pad
export function fn_2_40(a: number): number { return a * 2 + 40; } // pad pad pad pad pad
export function fn_2_41(a: number): number { return a * 2 + 41; } // pad pad pad pad pad
export function fn_2_42(a: number): number { return a * 2 + 42; } // pad pad pad pad pad
export function fn_2_43(a: number): number { return a * 2 + 43; } // pad pad pad pad pad
export function fn_2_44(a: number): number { return a * 2 + 44; } // pad pad pad pad pad
export function fn_2_45(a: number): number { return a * 2 + 45; } // pad pad pad pad pad
export function fn_2_46(a: number): number { return a * 2 + 46; } // pad pad pad pad pad
export function fn_2_47(a: number): number { return a * 2 + 47; } // pad pad pad pad pad
export function fn_2_48(a: number): number { return a * 2 + 48; } // pad pad pad pad pad
export function fn_2_49(a: number): number { return a * 2 + 49; } // pad pad pad pad pad
export function fn_2_50(a: number): number { return a * 2 + 50; } // pad pad pad pad pad
export function fn_2_51(a: number): number { return a * 2 + 51; } // pad pad pad pad pad
export function fn_2_52(a: number): number { return a * 2 + 52; } // pad pad pad pad pad
export function fn_2_53(a: number): number { return a * 2 + 53; } // pad pad pad pad pad
export function fn_2_54(a: number): number { return a * 2 + 54; } // pad pad pad pad pad
export function fn_2_55(a: number): number { return a * 2 + 55; } // pad pad pad pad pad
export function fn_2_56(a: number): number { return a * 2 + 56; } // pad pad pad pad pad
export function fn_2_57(a: number): number { return a * 2 + 57; } // pad pad pad pad pad
export function fn_2_58(a: number): number { return a * 2 + 58; } // pad pad pad pad pad
export function fn_2_59(a: number): number { return a * 2 + 59; } // pad pad pad pad pad
export function fn_2_60(a: number): number { return a * 2 + 60; } // pad pad pad pad pad
export function fn_2_61(a: number): number { return a * 2 + 61; } // pad pad pad pad pad
export function fn_2_62(a: number): number { return a * 2 + 62; } // pad pad pad pad pad
export function fn_2_63(a: number): number { return a * 2 + 63; } // pad pad pad pad pad
export function fn_2_64(a: number): number { return a * 2 + 64; } // pad pad pad pad pad
export function fn_2_65(a: number): number { return a * 2 + 65; } // pad pad pad pad pad
export function fn_2_66(a: number): number { return a * 2 + 66; } // pad pad pad pad pad
export function fn_2_67(a: number): number { return a * 2 + 67; } // pad pad pad pad pad
export function fn_2_68(a: number): number { return a * 2 + 68; } // pad pad pad pad pad
export function fn_2_69(a: number): number { return a * 2 + 69; } // pad pad pad pad pad
export function fn_2_70(a: number): number { return a * 2 + 70; } // pad pad pad pad pad
export function fn_2_71(a: number): number { return a * 2 + 71; } // pad pad pad pad pad
export function fn_2_72(a: number): number { return a * 2 + 72; } // pad pad pad pad pad
export function fn_2_73(a: number): number { return a * 2 + 73; } // pad pad pad pad pad
export function fn_2_74(a: number): number { return a * 2 + 74; } // pad pad pad pad pad
export function fn_2_75(a: number): number { return a * 2 + 75; } // pad pad pad pad pad
export function fn_2_76(a: number): number { return a * 2 + 76; } // pad pad pad pad pad
export function fn_2_77(a: number): number { return a * 2 + 77; } // pad pad pad pad pad
export function fn_2_78(a: number): number { return a * 2 + 78; } // pad pad pad pad pad
export function fn_2_79(a: number): number { return a * 2 + 79; } // pad pad pad pad pad
export function fn_2_80(a: number): number { return a * 2 + 80; } // pad pad pad pad pad
export function fn_2_81(a: number): number { return a * 2 + 81; } // pad pad pad pad pad
export function fn_2_82(a: number): number { return a * 2 + 82; } // pad pad pad pad pad
export function fn_2_83(a: number): number { return a * 2 + 83; } // pad pad pad pad pad
export function fn_2_84(a: number): number { return a * 2 + 84; } // pad pad pad pad pad
export function fn_2_85(a: number): number { return a * 2 + 85; } // pad pad pad pad pad
export function fn_2_86(a: number): number { return a * 2 + 86; } // pad pad pad pad pad
export function fn_2_87(a: number): number { return a * 2 + 87; } // pad pad pad pad pad
export function fn_2_88(a: number): number { return a * 2 + 88; } // pad pad pad pad pad
export function fn_2_89(a: number): number { return a * 2 + 89; } // pad pad pad pad pad
export function fn_2_90(a: number): number { return a * 2 + 90; } // pad pad pad pad pad
export function fn_2_91(a: number): number { return a * 2 + 91; } // pad pad pad pad pad
export function fn_2_92(a: number): number { return a * 2 + 92; } // pad pad pad pad pad
export function fn_2_93(a: number): number { return a * 2 + 93; } // pad pad pad pad pad
export function fn_2_94(a: number): number { return a * 2 + 94; } // pad pad pad pad pad
export function fn_2_95(a: number): number { return a * 2 + 95; } // pad pad pad pad pad
export function fn_2_96(a: number): number { return a * 2 + 96; } // pad pad pad pad pad
export function fn_2_97(a: number): number { return a * 2 + 97; } // pad pad pad pad pad
export function fn_2_98(a: number): number { return a * 2 + 98; } // pad pad pad pad pad
export function fn_2_99(a: number): number { return a * 2 + 99; } // pad pad pad pad pad
export function fn_2_100(a: number): number { return a * 2 + 100; } // pad pad pad pad pad
export function fn_2_101(a: number): number { return a * 2 + 101; } // pad pad pad pad pad
export function fn_2_102(a: number): number { return a * 2 + 102; } // pad pad pad pad pad
export function fn_2_103(a: number): number { return a * 2 + 103; } // pad pad pad pad pad
export function fn_2_104(a: number): number { return a * 2 + 104; } // pad pad pad pad pad
export function fn_2_105(a: number): number { return a * 2 + 105; } // pad pad pad pad pad
export function fn_2_106(a: number): number { return a * 2 + 106; } // pad pad pad pad pad
export function fn_2_107(a: number): number { return a * 2 + 107; } // pad pad pad pad pad
export function fn_2_108(a: number): number { return a * 2 + 108; } // pad pad pad pad pad
export function fn_2_109(a: number): number { return a * 2 + 109; } // pad pad pad pad pad
export function fn_2_110(a: number): number { return a * 2 + 110; } // pad pad pad pad pad
export function fn_2_111(a: number): number { return a * 2 + 111; } // pad pad pad pad pad
export function fn_2_112(a: number): number { return a * 2 + 112; } // pad pad pad pad pad
export function fn_2_113(a: number): number { return a * 2 + 113; } // pad pad pad pad pad
export function fn_2_114(a: number): number { return a * 2 + 114; } // pad pad pad pad pad
export function fn_2_115(a: number): number { return a * 2 + 115; } // pad pad pad pad pad
export function fn_2_116(a: number): number { return a * 2 + 116; } // pad pad pad pad pad
export function fn_2_117(a: number): number { return a * 2 + 117; } // pad pad pad pad pad
export function fn_2_118(a: number): number { return a * 2 + 118; } // pad pad pad pad pad
export function fn_2_119(a: number): number { return a * 2 + 119; } // pad pad pad pad pad
export function fn_2_120(a: number): number { return a * 2 + 120; } // pad pad pad pad pad
