# Generated by zuvo:write-tests
"""Shared harness for the scripts/zuvo-home/backlog unit specs (test_backlog_*.py).

Not a test module itself (no `test_` prefix). It loads the extensionless polyglot with a fresh
module object per test, sandboxes every path the module reads, and replaces `subprocess.run`
with a fake that runs the collector's remote command through the REAL /bin/sh against a local
sandbox directory — no ssh, no network, no real collector.
"""

import contextlib
import gzip
import importlib.machinery
import importlib.util
import io
import itertools
import json
import os
import subprocess
import sys
import tempfile
import unittest
import warnings
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parents[2]
BACKLOG = ROOT / "scripts" / "zuvo-home" / "backlog"

# Kept BEFORE any test patches subprocess.run (mod.subprocess is the global module).
REAL_RUN = subprocess.run

# Read at import or at call time by the module; never inherited from the developer's shell.
SCRUBBED_ENV = ("CODESIFT_COLLECTOR_TOKEN", "ZUVO_COLLECTOR_TOKEN", "ZUVO_PULL_MAX_BYTES",
                "ZUVO_HOME")
TOKEN_ENV = ("CODESIFT_COLLECTOR_TOKEN", "ZUVO_COLLECTOR_TOKEN")

_names = itertools.count()


def load_backlog(zuvo_dir, collector_ssh="fake-collector", extra_env=None, remove=()):
    """A fresh module object. The module reads env AT IMPORT, so it is loaded under a patched env.

    zuvo_dir=None loads it with ZUVO_DIR UNSET, to exercise the ~/.zuvo default."""
    env = {"ZUVO_DIR": zuvo_dir} if zuvo_dir is not None else {}
    if zuvo_dir is None:
        remove = tuple(remove) + ("ZUVO_DIR",)
    if collector_ssh is not None:
        env["ZUVO_COLLECTOR_SSH"] = collector_ssh
    env.update(extra_env or {})
    with mock.patch.dict(os.environ, env, clear=False):
        for key in SCRUBBED_ENV + tuple(remove):
            if key not in env:
                os.environ.pop(key, None)
        if collector_ssh is None:
            os.environ.pop("ZUVO_COLLECTOR_SSH", None)
        name = f"backlog_under_test_{next(_names)}"
        loader = importlib.machinery.SourceFileLoader(name, str(BACKLOG))
        spec = importlib.util.spec_from_loader(name, loader)
        mod = importlib.util.module_from_spec(spec)
        loader.exec_module(mod)
    return mod


class FakeRun:
    """Stand-in for subprocess.run.

    argv[0] == "ssh": the LAST argv element (the remote command) runs through the real /bin/sh
    against the sandbox — unless `ssh_result` is set, which is returned (or raised) instead.
    argv[0] == sys.executable: the push of backlog-collect.py; `push_result` is returned or raised.
    Every call is recorded with its keyword arguments.
    """

    def __init__(self):
        self.calls = []
        self.ssh_result = None
        self.push_result = subprocess.CompletedProcess([], 0, "", "")

    def __call__(self, argv, **kw):
        self.calls.append((list(argv), dict(kw)))
        if argv[0] == "ssh":
            if self.ssh_result is not None:
                if isinstance(self.ssh_result, BaseException):
                    raise self.ssh_result
                return self.ssh_result
            text = kw.get("text", True)
            env = {k: v for k, v in os.environ.items() if k not in TOKEN_ENV}
            extra = ({"encoding": kw.get("encoding", "utf-8"), "errors": kw.get("errors", "strict")}
                     if text else {})
            return REAL_RUN(["/bin/sh", "-c", argv[-1]], capture_output=True, text=text,
                            timeout=kw.get("timeout"), env=env, **extra)
        if argv[0] == sys.executable:
            if isinstance(self.push_result, BaseException):
                raise self.push_result
            return self.push_result
        raise AssertionError(f"unexpected subprocess.run argv: {argv!r}")

    @property
    def ssh_calls(self):
        return [(a, k) for a, k in self.calls if a[0] == "ssh"]

    @property
    def push_calls(self):
        return [(a, k) for a, k in self.calls if a[0] == sys.executable]

    # By CONTENT, never by position: sync runs a token fetch and a pull over ssh, and a test that read
    # `ssh_calls[0]` silently checked the other call the day their order changed.
    SSH_KINDS = {"pull": "d=", "token": "f="}

    def ssh_of(self, kind):
        """Every ssh call of one kind: "pull" (remote command `d=<data dir>; …`) or "token" (`f=<env>; …`)."""
        prefix = self.SSH_KINDS[kind]
        return [(a, k) for a, k in self.ssh_calls if a[-1].startswith(prefix)]

    def one_ssh(self, kind):
        found = self.ssh_of(kind)
        if len(found) != 1:
            raise AssertionError(f"expected exactly one {kind} ssh call, got {len(found)}: "
                                 f"{[a[-1][:60] for a, _ in self.ssh_calls]}")
        return found[0]

    def one_push(self):
        """The one run of backlog-collect.py --push — by what it runs, not merely by its interpreter."""
        found = [(a, k) for a, k in self.push_calls
                 if len(a) == 3 and os.path.basename(a[1]) == "backlog-collect.py" and a[2] == "--push"]
        if len(found) != 1 or len(self.push_calls) != 1:
            raise AssertionError(f"expected exactly one `backlog-collect.py --push`, got "
                                 f"{[a[1:] for a, _ in self.push_calls]}")
        return found[0]


def item(host, repo, item_id, status="open", severity=None, added="", text=""):
    return {"host": host, "repo": repo, "item_id": item_id, "status": status,
            "severity": severity, "added": added, "text": text}


def rec(host, run, received_at, items=None, strays=None, batch=0, batches=1, omit_items=False):
    payload = {"host": host, "run_id": run, "batch": batch, "batches": batches}
    if not omit_items:
        payload["items"] = items if items is not None else []
    if strays is not None:
        payload["stray_worktree_copies"] = strays
    return {"received_at": received_at, "payload": payload}


def write_jsonl(path, records):
    """records: dicts are JSON-encoded, str lines are written verbatim (malformed-line cases)."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for r in records:
            f.write((r if isinstance(r, str) else json.dumps(r)) + "\n")


def gz(data):
    return gzip.compress(data.encode("utf-8") if isinstance(data, str) else data)


class BacklogTestCase(unittest.TestCase):
    """Sandbox per test: ZUVO dir, collector DATA dir and collector.env, fake subprocess.run."""

    def setUp(self):
        # The module used to leave collector.conf, INDEX and META open; it closes them now, but a
        # ResourceWarning from any regression must not land in the stderr the tests assert on.
        warn = warnings.catch_warnings()
        warn.__enter__()
        self.addCleanup(warn.__exit__, None, None, None)
        warnings.simplefilter("ignore", ResourceWarning)
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        self.tmp = tmp.name
        self.zuvo = os.path.join(self.tmp, "zuvo")
        self.mod = load_backlog(self.zuvo)
        self.data = os.path.join(self.tmp, "collector", "data", "backlog")
        self.collector_env = os.path.join(self.tmp, "collector", "collector.env")
        self.mod.DATA = self.data
        self.mod.COLLECTOR_ENV = self.collector_env
        # The env the module reads at CALL time (tokens, ZUVO_PULL_MAX_BYTES, ZUVO_COLLECTOR_SSH).
        envp = mock.patch.dict(os.environ, {"ZUVO_DIR": self.zuvo,
                                            "ZUVO_COLLECTOR_SSH": "fake-collector"}, clear=False)
        envp.start()
        self.addCleanup(envp.stop)
        for key in SCRUBBED_ENV:
            os.environ.pop(key, None)
        self.fake = FakeRun()
        runp = mock.patch.object(self.mod.subprocess, "run", self.fake)
        runp.start()
        self.addCleanup(runp.stop)

    # --- helpers -------------------------------------------------------------------------------
    def capture(self, fn, *args, **kw):
        """(return value, stdout, stderr) of fn(*args)."""
        out, err = io.StringIO(), io.StringIO()
        with contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            ret = fn(*args, **kw)
        return ret, out.getvalue(), err.getvalue()

    def exit_message(self, fn, *args, **kw):
        """str(SystemExit.code) of fn(*args), plus captured stdout/stderr."""
        out, err = io.StringIO(), io.StringIO()
        with self.assertRaises(SystemExit) as cm, \
                contextlib.redirect_stdout(out), contextlib.redirect_stderr(err):
            fn(*args, **kw)
        return str(cm.exception.code), out.getvalue(), err.getvalue()

    def chmod_locked(self, path):
        """chmod 000 with the permission restored in cleanup; skips the test as root."""
        if os.geteuid() == 0:
            self.skipTest("root ignores chmod 000")
        os.chmod(path, 0)
        self.addCleanup(os.chmod, path, 0o700)

    def seed_index(self, text='{"item_id": "OLD-1"}\n'):
        os.makedirs(self.zuvo, exist_ok=True)
        with open(self.mod.INDEX, "w", encoding="utf-8") as f:
            f.write(text)
        return text

    def read_index(self):
        with open(self.mod.INDEX, encoding="utf-8") as f:
            return f.read()

    def index_items(self):
        return [json.loads(line) for line in self.read_index().splitlines() if line.strip()]

    def read_meta(self):
        with open(self.mod.META, encoding="utf-8") as f:
            return json.load(f)

    def write_index(self, items, meta=None):
        os.makedirs(self.zuvo, exist_ok=True)
        with open(self.mod.INDEX, "w", encoding="utf-8") as f:
            for it in items:
                f.write(json.dumps(it) + "\n")
        if meta is not None:
            with open(self.mod.META, "w", encoding="utf-8") as f:
                json.dump(meta, f)


def run_cli(tmp, *args, extra_env=None):
    """The real file as a real process, sandboxed: own HOME/ZUVO_DIR, no collector, no tokens."""
    env = {"PATH": os.environ.get("PATH", "/usr/bin:/bin"), "HOME": tmp,
           "ZUVO_DIR": os.path.join(tmp, "zuvo"), "ZUVO_COLLECTOR_SSH": "",
           "PYTHONIOENCODING": "utf-8"}
    env.update(extra_env or {})
    return REAL_RUN([sys.executable, str(BACKLOG), *args], capture_output=True, text=True,
                    encoding="utf-8", env=env, timeout=60)
