#!/usr/bin/env bash
# Generated by zuvo:write-tests
# Edge cases for the real refactor gate library: malformed TTL and caller shell state.
set -u
export GIT_CONFIG_GLOBAL=/dev/null GIT_CONFIG_SYSTEM=/dev/null GIT_CONFIG_NOSYSTEM=1

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
LIB="$ROOT/hooks/lib/refactor-gate-lib.sh"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
mkdir -p "$TMP/repo/zuvo/contracts" "$TMP/repo/zuvo/plans" "$TMP/repo/docs/specs" "$TMP/home/run-markers"
cd "$TMP/repo" || exit 1
git init -q
export ZUVO_CONTRACTS_DIR="$PWD/zuvo/contracts"
export ZUVO_PLANS_DIR="$PWD/zuvo/plans"
export ZUVO_HOME="$TMP/home"
export ZUVO_AI_RUN=1
unset ZUVO_OUTPUT_DIR
# Source the real library; its state reader and agent detector resolve beside it.
. "$LIB"

fails=0
ok() { echo "  ✓ $1"; }
bad() { echo "  ✗ $1"; fails=$((fails + 1)); }

cat > "$ZUVO_CONTRACTS_DIR/refactor-edge.json" <<'JSON'
{"version":3,"stage":"PHASE-3","scope_fence":["src/in.ts"],
 "prove":{"characterization":"green:abc1234:2u","blind_audit":"not_run",
          "adversarial":"clean","findings_disposition":"none"}}
JSON

echo "=== malformed TTL still checks the real proof ==="
export ZUVO_GATE_TTL_SEC=not-a-number
if refactor_gate_check 'src/in.ts' > "$TMP/ttl.out" 2> "$TMP/ttl.err"; then
  ttl_status=0
else
  ttl_status=$?
fi
if [ "$ttl_status" -eq 1 ] &&
   grep -Fq "BLOCK: refactor CONTRACT prove.blind_audit='not_run' not satisfied" "$TMP/ttl.out" &&
   [ ! -s "$TMP/ttl.err" ]; then
  ok "invalid TTL does not abort or hide the missing blind audit"
else
  bad "invalid TTL status=$ttl_status; stdout=$(cat "$TMP/ttl.out"); stderr=$(cat "$TMP/ttl.err")"
fi
# The file is still fresh by the documented 24-hour default, but old enough
# that replacing the invalid-TTL fallback with zero would bypass every proof.
python3 - "$ZUVO_CONTRACTS_DIR/refactor-edge.json" <<'PY' || { bad '30-second mtime setup failed'; exit 1; }
import os, sys, time
age = time.time() - 30
os.utime(sys.argv[1], (age, age))
PY
if refactor_gate_check 'src/in.ts' > "$TMP/ttl.out" 2> "$TMP/ttl.err"; then
  ttl_status=0
else
  ttl_status=$?
fi
if [ "$ttl_status" -eq 1 ] &&
   grep -Fq "prove.blind_audit='not_run'" "$TMP/ttl.out" &&
   [ ! -s "$TMP/ttl.err" ]; then
  ok "invalid TTL uses the normal 24-hour window for a 30-second-old contract"
else
  bad "invalid TTL bypasses a fresh contract: status=$ttl_status; stdout=$(cat "$TMP/ttl.out"); stderr=$(cat "$TMP/ttl.err")"
fi
python3 - "$ZUVO_CONTRACTS_DIR/refactor-edge.json" <<'PY' || { bad 'stale mtime setup failed'; exit 1; }
import os, sys, time
old = time.time() - 86500
os.utime(sys.argv[1], (old, old))
PY
if refactor_gate_check 'src/in.ts' > "$TMP/ttl.out" 2> "$TMP/ttl.err"; then
  ttl_status=0
else
  ttl_status=$?
fi
if [ "$ttl_status" -eq 0 ] && [ ! -s "$TMP/ttl.out" ] &&
   grep -Fq 'stale contract (> 86400s) -> bypass' "$TMP/ttl.err"; then
  ok 'invalid TTL still expires an abandoned contract after 24 hours'
else
  bad "invalid TTL did not expire an old contract: status=$ttl_status; output=$(cat "$TMP/ttl.out" "$TMP/ttl.err")"
fi
touch "$ZUVO_CONTRACTS_DIR/refactor-edge.json"
unset ZUVO_GATE_TTL_SEC

check_glob_state() {
  local label=$1 expected=$2 guard=$3 staged=$4 expected_text=${5:-} status
  local glob_preserved initial_glob
  case $- in *f*) initial_glob=1 ;; *) initial_glob=0 ;; esac
  set -f
  if "$guard" "$staged" > "$TMP/guard.out" 2> "$TMP/guard.err"; then
    status=0
  else
    status=$?
  fi
  case $- in *f*) glob_preserved=1 ;; *) glob_preserved=0 ;; esac
  [ "$initial_glob" -eq 1 ] || set +f
  if [ "$status" -eq "$expected" ] && [ "$glob_preserved" -eq 1 ] &&
     [ ! -s "$TMP/guard.err" ] &&
     { [ "$expected" -ne 0 ] || [ ! -s "$TMP/guard.out" ]; } &&
     { [ -z "$expected_text" ] || grep -Fq "$expected_text" "$TMP/guard.out"; }; then
    ok "$label returns $expected and preserves set -f"
  else
    bad "$label status=$status expected=$expected glob_preserved=$glob_preserved; stdout=$(cat "$TMP/guard.out"); stderr=$(cat "$TMP/guard.err")"
  fi
}

echo "=== contract guards still judge proofs with caller globbing disabled ==="
check_glob_state 'refactor proof block' 1 refactor_gate_check 'src/in.ts' "prove.blind_audit='not_run'"
cat > "$ZUVO_CONTRACTS_DIR/refactor-edge.json" <<'JSON'
{"version":3,"stage":"PHASE-3","scope_fence":["src/in.ts"],
 "prove":{"characterization":"green:abc1234:2u","blind_audit":"clean:strict",
          "adversarial":"not_run","findings_disposition":"none"}}
JSON
if refactor_gate_check 'src/in.ts' > "$TMP/guard.out" 2> "$TMP/guard.err"; then
  av_status=0
else
  av_status=$?
fi
if [ "$av_status" -eq 1 ] &&
   grep -Fq "prove.adversarial='not_run'" "$TMP/guard.out" &&
   [ ! -s "$TMP/guard.err" ]; then
  ok "adversarial not_run alone blocks the refactor proof"
else
  bad "adversarial not_run did not block: status=$av_status; stdout=$(cat "$TMP/guard.out"); stderr=$(cat "$TMP/guard.err")"
fi
echo '=== terminal refactor stages release the prove gate ==='
for stage in COMPLETE BLOCKED ABORTED; do
  cat > "$ZUVO_CONTRACTS_DIR/refactor-edge.json" <<JSON
{"version":3,"stage":"$stage","scope_fence":["src/in.ts"],
 "prove":{"characterization":"not_run","blind_audit":"not_run",
          "adversarial":"not_run","findings_disposition":"none"}}
JSON
  if refactor_gate_check 'src/in.ts' > "$TMP/guard.out" 2> "$TMP/guard.err" &&
     refactor_scope_gate_check 'src/out.ts' >> "$TMP/guard.out" 2>> "$TMP/guard.err" &&
     [ ! -s "$TMP/guard.out" ] && [ ! -s "$TMP/guard.err" ]; then
    ok "$stage does not enforce an in-flight proof"
  else
    bad "$stage kept enforcing the prove gate: $(cat "$TMP/guard.out" "$TMP/guard.err")"
  fi
done
cat > "$ZUVO_CONTRACTS_DIR/refactor-edge.json" <<'JSON'
{"version":4,"stage":"COMPLETE","scope_fence":["src/in.ts"],"modules_created":[],
 "prove":{"characterization":"green:abc1234:2u","blind_audit":"clean:strict",
          "adversarial":"clean","findings_disposition":"none",
          "test_quality":"not_run","split_coverage":"N/A"}}
JSON
export ZUVO_GATE_MODE=pre-push
check_glob_state 'v4 push proof block' 1 refactor_prove_v4_check 'src/in.ts' "prove.test_quality='not_run'"
unset ZUVO_GATE_MODE

# Give the scope guard a complete active proof; this case concerns only its allow/deny paths.
cat > "$ZUVO_CONTRACTS_DIR/refactor-edge.json" <<'JSON'
{"version":3,"stage":"PHASE-3","scope_fence":["src/in.ts"],
 "prove":{"characterization":"green:abc1234:2u","blind_audit":"clean:strict",
          "adversarial":"clean","findings_disposition":"none"}}
JSON

echo "=== scope guard preserves caller glob option ==="
check_glob_state 'scope allow, in fence' 0 refactor_scope_gate_check 'src/in.ts'
check_glob_state 'scope block, outside fence' 1 refactor_scope_gate_check 'src/out.ts' 'src/out.ts'

printf '# Plan\n**Files:** src/planned.ts\n' > "$TMP/repo/docs/specs/edge-plan.md"
printf 'status: pending\nplan: docs/specs/edge-plan.md\n' > "$ZUVO_PLANS_DIR/active-plan.md"

echo "=== plan/execute guard preserves caller glob option ==="
check_glob_state 'plan allow, undeclared file' 0 plan_execute_gate_check 'src/other.ts'
check_glob_state 'plan block, declared file' 1 plan_execute_gate_check 'src/planned.ts' 'Approved plan is PENDING'
printf 'skill=execute\nrepo_root=%s\n' "$PWD" > "$ZUVO_HOME/run-markers/execute-edge.marker"
printf 'status: in-progress\nplan: docs/specs/edge-plan.md\n' > "$ZUVO_PLANS_DIR/active-plan.md"
check_glob_state 'plan allow, fresh execute marker only' 0 plan_execute_gate_check 'src/planned.ts'

# scripts/zuvo-phase.sh calls this helper directly. The enclosing plan guard
# enables globbing for its own call, so only a direct call tests the helper's
# independent marker lookup and its caller-state boundary.
set -f
if _execute_run_live "$PWD" 'docs/specs/edge-plan.md' > "$TMP/guard.out" 2> "$TMP/guard.err"; then
  live_status=0
else
  live_status=$?
fi
case $- in *f*) glob_preserved=1 ;; *) glob_preserved=0 ;; esac
set +f
if [ "$live_status" -eq 0 ] && [ "$glob_preserved" -eq 1 ] &&
   [ ! -s "$TMP/guard.err" ]; then
  ok 'direct execute-run lookup finds a marker and preserves set -f'
else
  bad "direct execute-run lookup status=$live_status glob_preserved=$glob_preserved; output=$(cat "$TMP/guard.out" "$TMP/guard.err")"
fi

echo '=== future execution state is not live evidence ==='
rm "$ZUVO_HOME/run-markers/execute-edge.marker"
if _execute_run_live "$PWD" 'docs/specs/edge-plan.md' > "$TMP/guard.out" 2> "$TMP/guard.err"; then
  missing_status=0
else
  missing_status=$?
fi
if [ "$missing_status" -eq 1 ] && [ ! -s "$TMP/guard.out" ] && [ ! -s "$TMP/guard.err" ]; then
  ok 'direct execute-run lookup rejects a missing marker'
else
  bad "direct lookup accepted a missing marker: status=$missing_status; output=$(cat "$TMP/guard.out" "$TMP/guard.err")"
fi
mkdir -p "$TMP/repo/zuvo/context"
printf 'status: in-progress\nplan: docs/specs/edge-plan.md\n' \
  > "$TMP/repo/zuvo/context/execution-state.md"
if plan_execute_gate_check 'src/planned.ts' > "$TMP/guard.out" 2> "$TMP/guard.err" &&
   [ ! -s "$TMP/guard.out" ] && [ ! -s "$TMP/guard.err" ]; then
  ok 'current execution state corroborates the active plan without a marker'
else
  bad "current execution state was rejected: $(cat "$TMP/guard.out" "$TMP/guard.err")"
fi
python3 - "$TMP/repo/zuvo/context/execution-state.md" <<'PY' || { bad 'future mtime setup failed'; exit 1; }
import os, sys, time
future = time.time() + 365 * 86400
os.utime(sys.argv[1], (future, future))
PY
if plan_execute_gate_check 'src/planned.ts' > "$TMP/guard.out" 2> "$TMP/guard.err"; then
  future_status=0
else
  future_status=$?
fi
if [ "$future_status" -eq 1 ] &&
   grep -Fq 'no zuvo:execute run backs it' "$TMP/guard.out"; then
  ok 'future-dated execution state cannot corroborate an active plan'
else
  bad "future execution state status=$future_status; output=$(cat "$TMP/guard.out" "$TMP/guard.err")"
fi

echo "=== RESULT ==="
[ "$fails" -eq 0 ] && { echo 'ALL PASS'; exit 0; }
echo "$fails FAILED"; exit 1
