#!/usr/bin/env bash
# Generated by zuvo:write-tests. Medium unit test: temporary filesystem only.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TMP="$(mktemp -d)" || exit 1
trap 'rm -rf "$TMP"' EXIT
export HOME="$TMP/home" GIT_CONFIG_GLOBAL="$TMP/gitconfig" GIT_CONFIG_NOSYSTEM=1
mkdir -p "$HOME"
# shellcheck disable=SC1090
. "$ROOT/scripts/install.sh" >"$TMP/source.out" 2>&1 || exit 1

PASS=0; FAIL=0
t_ok() { printf '  PASS %s\n' "$1"; PASS=$((PASS + 1)); }
t_no() { printf '  FAIL %s\n' "$1"; FAIL=$((FAIL + 1)); }
SRC="$TMP/source.sh"; DST="$TMP/destination.sh"
printf 'current helper bytes\n' > "$SRC"
old_destination() { printf 'previous helper bytes\n' > "$DST"; }
old_intact() { [ "$(cat "$DST")" = 'previous helper bytes' ]; }
no_temp() { ! compgen -G "$TMP/.destination.sh.*" >/dev/null; }
fake_tool() {
  local dir="$TMP/$1" name="$2" body="$3"
  mkdir -p "$dir"
  printf '#!/bin/sh\n%s\n' "$body" > "$dir/$name"
  chmod +x "$dir/$name"
}

old_destination
rc=0; reason="$(install_file_atomic "$TMP/absent.sh" "$DST")" || rc=$?
if [ "$rc" -eq 1 ] && [ "$reason" = "source missing: $TMP/absent.sh" ] && old_intact; then
  t_ok "missing source is refused before destination changes"
else t_no "missing source was accepted or changed the destination"; fi

BLOCKED="$TMP/directory-destination"; mkdir -p "$BLOCKED"
rc=0; reason="$(install_file_atomic "$SRC" "$BLOCKED")" || rc=$?
if [ "$rc" -eq 1 ] && [ "$reason" = 'refused: the destination exists and is not a regular file' ] && \
   [ -z "$(ls -A "$BLOCKED")" ]; then
  t_ok "a directory destination is refused without moving a temp file inside"
else t_no "directory destination was changed or accepted"; fi

FIRST="$TMP/first-install.sh"
rc=0; reason="$(install_file_atomic "$SRC" "$FIRST")" || rc=$?
if [ "$rc" -eq 0 ] && [ -z "$reason" ] && [ -f "$FIRST" ] && \
   cmp -s "$SRC" "$FIRST" && [ ! -x "$FIRST" ] && \
   ! compgen -G "$TMP/.first-install.sh.*" >/dev/null; then
  t_ok "first install creates an exact regular file without temporary debris"
else t_no "first install failed or left incorrect bytes, mode, or debris"; fi

fake_tool failmk mktemp 'exit 43'
old_destination
rc=0; reason="$(PATH="$TMP/failmk:$PATH" install_file_atomic "$SRC" "$DST")" || rc=$?
if [ "$rc" -eq 1 ] && [ "$reason" = "mktemp failed (in $TMP)" ] && old_intact && no_temp; then
  t_ok "failed temp allocation leaves the previous file intact"
else t_no "mktemp failure was swallowed or changed the previous file"; fi

fake_tool failcp cp 'printf "partial bytes\\n" > "$2"; exit 43'
old_destination
rc=0; reason="$(PATH="$TMP/failcp:$PATH" install_file_atomic "$SRC" "$DST")" || rc=$?
if [ "$rc" -eq 1 ] && [ "$reason" = 'cp failed' ] && old_intact && no_temp; then
  t_ok "failed copy removes its partial temp and preserves the old file"
else t_no "failed copy left partial bytes or was reported successful"; fi

fake_tool trunc cp 'printf "truncated bytes\\n" > "$2"; exit 0'
old_destination
rc=0; reason="$(PATH="$TMP/trunc:$PATH" install_file_atomic "$SRC" "$DST")" || rc=$?
if [ "$rc" -eq 1 ] && [ "$reason" = 'content check failed (the copy differs from the source; the destination was left as it was)' ] && old_intact && no_temp; then
  t_ok "pre-move checksum rejects a successful but corrupt copy"
else t_no "corrupt staged bytes replaced the prior helper"; fi

fake_tool failchmod chmod 'exit 43'
old_destination
rc=0; reason="$(PATH="$TMP/failchmod:$PATH" install_file_atomic "$SRC" "$DST")" || rc=$?
if [ "$rc" -eq 1 ] && [ "$reason" = 'chmod failed' ] && old_intact && no_temp; then
  t_ok "chmod failure removes the temp and preserves the old helper"
else t_no "chmod failure was swallowed or left temp bytes"; fi

fake_tool failmv mv 'exit 43'
old_destination
rc=0; reason="$(PATH="$TMP/failmv:$PATH" install_file_atomic "$SRC" "$DST")" || rc=$?
if [ "$rc" -eq 1 ] && [ "$reason" = 'mv failed' ] && old_intact && no_temp; then
  t_ok "rename failure removes the temp and preserves the old helper"
else t_no "rename failure was swallowed or left temp bytes"; fi

fake_tool corruptmv mv '[ "$1" = -f ] && shift; printf "concurrent bytes\\n" > "$2"; rm -f "$1"'
old_destination
rc=0; reason="$(PATH="$TMP/corruptmv:$PATH" install_file_atomic "$SRC" "$DST")" || rc=$?
if [ "$rc" -eq 1 ] && [ "$reason" = 'content check failed after the move (the installed bytes differ from the source)' ] && \
   [ "$(cat "$DST")" = 'concurrent bytes' ] && no_temp; then
  t_ok "post-move checksum notices a destination changed after rename"
else t_no "post-move corruption was reported successful"; fi

old_destination
chmod +x "$SRC"
rc=0; reason="$(install_file_atomic "$SRC" "$DST")" || rc=$?
if [ "$rc" -eq 0 ] && [ -z "$reason" ] && [ -x "$DST" ] && cmp -s "$SRC" "$DST" && no_temp; then
  t_ok "successful copy installs exact executable source bytes"
else t_no "successful executable copy changed bytes, mode, or status"; fi

chmod -x "$SRC"
rc=0; reason="$(install_file_atomic "$SRC" "$DST")" || rc=$?
if [ "$rc" -eq 0 ] && [ -z "$reason" ] && [ ! -x "$DST" ] && cmp -s "$SRC" "$DST" && no_temp; then
  t_ok "successful copy follows the non-executable source mode"
else t_no "non-executable copy changed bytes, mode, or status"; fi

# A symlinked destination is the user's choice — a dotfile manager, or a dev link into a checkout.
# Replacing it turned a live link into a stale copy; the target never changed, so nothing said so.
LINK_TARGET="$TMP/linked-target.sh"; LINK="$TMP/linked.sh"
printf 'somebody else\n' > "$LINK_TARGET"; ln -s linked-target.sh "$LINK"
rc=0; reason="$(install_file_atomic "$SRC" "$LINK")" || rc=$?
if [ "$rc" -eq 1 ] && [[ "$reason" == *"is a symlink"* ]] && [ -L "$LINK" ] && [ "$(cat "$LINK_TARGET")" = 'somebody else' ]; then
  t_ok "a symlinked destination holding other bytes is refused; the link and its target are untouched"
else t_no "symlinked destination: rc=$rc reason=[$reason] link=$([ -L "$LINK" ] && echo kept || echo REPLACED) target=[$(cat "$LINK_TARGET")]"; fi
cp "$SRC" "$LINK_TARGET"
rc=0; reason="$(install_file_atomic "$SRC" "$LINK")" || rc=$?
if [ "$rc" -eq 0 ] && [ -z "$reason" ] && [ -L "$LINK" ] && cmp -s "$SRC" "$LINK_TARGET"; then
  t_ok "a symlinked destination that already holds the source bytes is left as it is (status 0)"
else t_no "symlink already current: rc=$rc reason=[$reason] link=$([ -L "$LINK" ] && echo kept || echo REPLACED)"; fi

# …"already holds the source" includes the exec bit: an executable helper behind a link to a
# non-executable copy would not run, so that link is refused like any other.
chmod +x "$SRC"; cp "$SRC" "$LINK_TARGET"; chmod -x "$LINK_TARGET"
rc=0; reason="$(install_file_atomic "$SRC" "$LINK")" || rc=$?
if [ "$rc" -eq 1 ] && [[ "$reason" == *"is a symlink"* ]] && [ -L "$LINK" ] && [ ! -x "$LINK_TARGET" ]; then
  t_ok "a symlink to the right bytes WITHOUT the source's exec bit is refused, not reported current"
else t_no "symlink missing the exec bit: rc=$rc reason=[$reason]"; fi
chmod -x "$SRC"
# A dangling symlink (its target gone) is still the user's link: refused, left in place.
DANGLE="$TMP/dangling.sh"; ln -s "$TMP/no-such-target" "$DANGLE"
rc=0; reason="$(install_file_atomic "$SRC" "$DANGLE")" || rc=$?
if [ "$rc" -eq 1 ] && [[ "$reason" == *"is a symlink (to $TMP/no-such-target)"* ]] && [ -L "$DANGLE" ] && [ ! -e "$TMP/no-such-target" ]; then
  t_ok "a dangling symlinked destination is refused, naming its target; nothing is created behind it"
else t_no "dangling symlink: rc=$rc reason=[$reason] target $([ -e "$TMP/no-such-target" ] && echo CREATED || echo absent)"; fi

# The destination becomes a directory between the entry check and the move: `mv` then puts the temp
# INSIDE it. The post-move check caught that, but named the wrong cause and left the temp behind.
DIR_DST="$TMP/became-dir.sh"; printf 'old\n' > "$DIR_DST"
fake_tool swap-bin mv 'rm -f "'"$DIR_DST"'"; mkdir "'"$DIR_DST"'"; exec '"$(command -v mv)"' "$@"'
rc=0; reason="$(PATH="$TMP/swap-bin:$PATH" install_file_atomic "$SRC" "$DIR_DST")" || rc=$?
if [ "$rc" -eq 1 ] && [[ "$reason" == *"became a directory"* ]] && [ -d "$DIR_DST" ] && \
   ! compgen -G "$DIR_DST/.became-dir.sh.*" >/dev/null && ! compgen -G "$TMP/.became-dir.sh.*" >/dev/null; then
  t_ok "a destination swapped for a directory mid-install is named, and no temp is left inside it"
else t_no "destination became a directory: rc=$rc reason=[$reason] stray=[$(ls -A "$DIR_DST" 2>/dev/null | tr '\n' ' ')]"; fi

printf '  --- install atomic file: PASS=%s FAIL=%s\n' "$PASS" "$FAIL"
echo "RESULT: PASS=$PASS FAIL=$FAIL"   # the summary line ~/.zuvo/refactor-contract and run-all read
[ "$FAIL" -eq 0 ]
