#!/usr/bin/env bash
# Generated by zuvo:write-tests. Medium integration test: isolated Git repo and HOME.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TMP="$(mktemp -d)" || exit 1
trap 'rm -rf "$TMP"' EXIT
export HOME="$TMP/home" GIT_CONFIG_GLOBAL="$TMP/gitconfig" GIT_CONFIG_NOSYSTEM=1
mkdir -p "$HOME/.zuvo"

PASS=0; FAIL=0
t_ok() { printf '  PASS %s\n' "$1"; PASS=$((PASS + 1)); }
t_no() { printf '  FAIL %s\n' "$1"; FAIL=$((FAIL + 1)); }

FIXTURE="$TMP/repo"
mkdir -p "$FIXTURE/scripts/lib" "$FIXTURE/skills"
cp "$ROOT/scripts/install.sh" "$FIXTURE/scripts/install.sh"
cp "$ROOT/scripts/lib/portable.sh" "$FIXTURE/scripts/lib/portable.sh"
# install.sh refuses to run without its lane library (and the runner library that library sources);
# a fixture without them stops at that check and never reaches the guards this file tests.
cp "$ROOT/scripts/lib/reviewer-lanes.sh" "$ROOT/scripts/lib/model-subprocess.sh" "$FIXTURE/scripts/lib/"
# …and its modules: install.sh loads scripts/install.d/ before either guard, and refuses without them.
cp -R "$ROOT/scripts/install.d" "$FIXTURE/scripts/"
printf '{"version":"0.0.0-test"}\n' > "$FIXTURE/package.json"
for validator in validate-banned-vocabulary.sh validate-banned-vocabulary-fixtures.sh; do
  printf '#!/bin/sh\nexit 0\n' > "$FIXTURE/scripts/$validator"
  chmod +x "$FIXTURE/scripts/$validator"
done

git -C "$FIXTURE" init -q
git -C "$FIXTURE" config user.name 'Install guard test'
git -C "$FIXTURE" config user.email 'test@example.invalid'
git -C "$FIXTURE" add -- scripts package.json
git -C "$FIXTURE" commit -qm 'fixture: older checkout'
OLDER="$(git -C "$FIXTURE" rev-parse HEAD)"
printf 'newer source exists\n' > "$FIXTURE/newer-marker"
git -C "$FIXTURE" add -- newer-marker
git -C "$FIXTURE" commit -qm 'fixture: installed revision'
NEWER="$(git -C "$FIXTURE" rev-parse HEAD)"
git -C "$FIXTURE" checkout -q --detach "$OLDER"

printf '%s\nmain\n' "$NEWER" > "$HOME/.zuvo/.installed-from"
older_rc=0
bash "$FIXTURE/scripts/install.sh" unknown >"$TMP/older.out" 2>&1 || older_rc=$?
if [ "$older_rc" -eq 1 ] && \
   grep -q 'does NOT contain the installed commit' "$TMP/older.out" && \
   ! grep -q 'Installing zuvo' "$TMP/older.out"; then
  t_ok "a checkout behind the installed revision is refused before installation"
else
  t_no "older checkout was not refused at the downgrade guard (rc=$older_rc)"
fi

printf 'divergent source\n' > "$FIXTURE/divergent-marker"
git -C "$FIXTURE" add -- divergent-marker
git -C "$FIXTURE" commit -qm 'fixture: divergent checkout'
divergent_rc=0
bash "$FIXTURE/scripts/install.sh" unknown >"$TMP/divergent.out" 2>&1 || divergent_rc=$?
if [ "$divergent_rc" -eq 1 ] && \
   grep -q 'does NOT contain the installed commit' "$TMP/divergent.out" && \
   ! grep -q 'Installing zuvo' "$TMP/divergent.out"; then
  t_ok "a divergent checkout is refused even though it has a newer local commit"
else
  t_no "divergent checkout bypassed the ancestry guard (rc=$divergent_rc)"
fi

git -C "$FIXTURE" checkout -q --detach "$NEWER"
printf 'descendant source\n' > "$FIXTURE/descendant-marker"
git -C "$FIXTURE" add -- descendant-marker
git -C "$FIXTURE" commit -qm 'fixture: checkout containing installed revision'
descendant_rc=0
bash "$FIXTURE/scripts/install.sh" unknown >"$TMP/descendant.out" 2>&1 || descendant_rc=$?
if [ "$descendant_rc" -eq 1 ] && \
   grep -q 'Installing zuvo v0.0.0-test' "$TMP/descendant.out" && \
   grep -q 'Usage:' "$TMP/descendant.out" && \
   ! grep -q 'REFUSING:' "$TMP/descendant.out"; then
  t_ok "a descendant of the installed revision reaches normal dispatch"
else
  t_no "descendant checkout was refused (rc=$descendant_rc)"
fi
git -C "$FIXTURE" checkout -q --detach "$OLDER"

printf '%040d\nmain\n' 0 > "$HOME/.zuvo/.installed-from"
unknown_rc=0
bash "$FIXTURE/scripts/install.sh" unknown >"$TMP/unknown.out" 2>&1 || unknown_rc=$?
if [ "$unknown_rc" -eq 1 ] && \
   grep -q 'is not in this repository' "$TMP/unknown.out" && \
   ! grep -q 'Installing zuvo' "$TMP/unknown.out"; then
  t_ok "an unknown installed commit is refused before installation"
else
  t_no "unknown installed commit was not refused (rc=$unknown_rc)"
fi

printf '%s\nmain\n' "$NEWER" > "$HOME/.zuvo/.installed-from"
force_rc=0
ZUVO_INSTALL_FORCE=1 bash "$FIXTURE/scripts/install.sh" unknown >"$TMP/force.out" 2>&1 || force_rc=$?
if [ "$force_rc" -eq 1 ] && \
   grep -q 'Installing zuvo v0.0.0-test' "$TMP/force.out" && \
   grep -q 'Usage:' "$TMP/force.out" && \
   ! grep -q 'REFUSING:' "$TMP/force.out"; then
  t_ok "explicit force bypasses the downgrade guard and reaches normal dispatch"
else
  t_no "force failed to bypass the downgrade guard (rc=$force_rc)"
fi

printf '%s\nmain\n' "$OLDER" > "$HOME/.zuvo/.installed-from"
same_rc=0
bash "$FIXTURE/scripts/install.sh" unknown >"$TMP/same.out" 2>&1 || same_rc=$?
if [ "$same_rc" -eq 1 ] && \
   grep -q 'Installing zuvo v0.0.0-test' "$TMP/same.out" && \
   ! grep -q 'REFUSING:' "$TMP/same.out"; then
  t_ok "the recorded checkout itself passes the downgrade guard"
else
  t_no "the matching installed commit was refused (rc=$same_rc)"
fi

# The early debris guard must return to a sourcing caller. A bare `exit 1`
# would kill this shell before AFTER_SOURCE can be printed.
mkdir -p "$FIXTURE/skills/tmp-test-leftover"
source_rc=0
( source "$FIXTURE/scripts/install.sh"; source_rc=$?; printf 'AFTER_SOURCE=%s\n' "$source_rc" ) \
  >"$TMP/source.out" 2>&1 || source_rc=$?
if [ "$source_rc" -eq 0 ] && \
   grep -q 'refusing to install: test debris' "$TMP/source.out" && \
   grep -q 'AFTER_SOURCE=1' "$TMP/source.out"; then
  t_ok "debris refusal returns control to a sourcing shell"
else
  t_no "debris refusal exited the sourcing shell or returned success (rc=$source_rc)"
fi

# Run the real codex-only dispatch from this checkout with isolated HOME. With
# no ~/.codex, that host path skips while install_zuvo_home still exercises the
# final stamp and copy-verification order.
STAMP_CLEAN="$TMP/stamp-clean"
mkdir -p "$STAMP_CLEAN"
clean_rc=0
HOME="$STAMP_CLEAN" bash "$ROOT/scripts/install.sh" codex >"$TMP/stamp-clean.out" 2>&1 || clean_rc=$?
# The stamp needs a KNOWN source revision: from a git checkout it is written, line 1 = HEAD; from a
# source with no git (the farm's synced mirror has no .git) it is deliberately NOT — a stamp whose
# line 1 is the branch or the date made every later install from a clone refuse.
src_sha="$(git -C "$ROOT" rev-parse --verify -q HEAD 2>/dev/null || true)"   # --verify: an unborn HEAD prints "HEAD"
if [ -n "$src_sha" ]; then
  stamp_ok() { [ -f "$1" ] && [ "$(head -1 "$1")" = "$src_sha" ]; }
  stamp_want="the installed revision stamp, line 1 = HEAD"
else
  stamp_ok() { [ ! -e "$1" ]; }
  stamp_want="NO stamp (the source has no git revision to record)"
fi
if [ "$clean_rc" -eq 0 ] && stamp_ok "$STAMP_CLEAN/.zuvo/.installed-from" && \
   grep -q 'DONE' "$TMP/stamp-clean.out"; then
  t_ok "successful dispatch writes $stamp_want"
else
  t_no "successful dispatch: want exit 0, DONE and $stamp_want (rc=$clean_rc)"
fi

STAMP_FAILED="$TMP/stamp-failed"
mkdir -p "$STAMP_FAILED/.zuvo/model-subprocess.sh"
failed_rc=0
HOME="$STAMP_FAILED" bash "$ROOT/scripts/install.sh" codex >"$TMP/stamp-failed.out" 2>&1 || failed_rc=$?
# A failed install must not arm the downgrade guard or print a success banner.
if [ "$failed_rc" -eq 1 ] && \
   grep -q 'INSTALL INCOMPLETE' "$TMP/stamp-failed.out" && \
   [ ! -e "$STAMP_FAILED/.zuvo/.installed-from" ] && \
   ! grep -q 'DONE' "$TMP/stamp-failed.out"; then
  t_ok "failed install withholds the revision stamp and success banner"
else
  t_no "failed install stamped or claimed success (rc=$failed_rc)"
fi

STAMP_PRIOR="$TMP/stamp-prior"
mkdir -p "$STAMP_PRIOR/.zuvo/model-subprocess.sh"
prior_sha="$(git -C "$ROOT" rev-parse --verify -q HEAD 2>/dev/null || true)"
printf '%s\n' "$prior_sha" > "$STAMP_PRIOR/.zuvo/.installed-from"
cp "$STAMP_PRIOR/.zuvo/.installed-from" "$TMP/prior-stamp-original"
prior_rc=0
HOME="$STAMP_PRIOR" bash "$ROOT/scripts/install.sh" codex >"$TMP/stamp-prior.out" 2>&1 || prior_rc=$?
if [ "$prior_rc" -eq 1 ] && \
   grep -q 'INSTALL INCOMPLETE' "$TMP/stamp-prior.out" && \
   cmp -s "$TMP/prior-stamp-original" "$STAMP_PRIOR/.zuvo/.installed-from"; then
  t_ok "failed reinstall preserves the previous successful revision stamp"
else
  t_no "failed reinstall changed the prior stamp (rc=$prior_rc)"
fi

printf '  --- install downgrade guard: PASS=%s FAIL=%s\n' "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ]
