# Generated by zuvo:write-tests
"""scripts/zuvo-home/backlog — the payload helpers: _pull_max_bytes, _decompress_bounded,
_decompress_bounded_bytes, _decode_payload, _decodes.

The collector's namespace arrives gzipped from every host in the fleet. These helpers bound its
expansion, refuse a truncated stream, and refuse non-UTF-8 records by count instead of publishing
a shortened index.
"""

import os
import sys
import unittest
import zlib

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from backlog_testlib import BacklogTestCase, gz, load_backlog  # noqa: E402

DEFAULT_CAP = 536870912   # 512 * 1024 * 1024, the documented ceiling


class PullMaxBytesTests(BacklogTestCase):
    def test_unset_returns_the_512_mib_default_silently(self):
        value, out, err = self.capture(self.mod._pull_max_bytes)
        self.assertEqual(DEFAULT_CAP, value)
        self.assertEqual("", out + err)

    def test_blank_value_is_treated_as_unset(self):
        os.environ["ZUVO_PULL_MAX_BYTES"] = "   "
        value, _out, err = self.capture(self.mod._pull_max_bytes)
        self.assertEqual(DEFAULT_CAP, value)
        self.assertEqual("", err)

    def test_non_integer_falls_back_to_default_and_names_the_value(self):
        os.environ["ZUVO_PULL_MAX_BYTES"] = "abc"
        value, _out, err = self.capture(self.mod._pull_max_bytes)
        self.assertEqual(DEFAULT_CAP, value)
        self.assertIn("backlog: ignoring ZUVO_PULL_MAX_BYTES='abc' — not an integer", err)

    def test_zero_falls_back_to_default_and_says_there_is_no_unlimited_setting(self):
        os.environ["ZUVO_PULL_MAX_BYTES"] = "0"
        value, _out, err = self.capture(self.mod._pull_max_bytes)
        self.assertEqual(DEFAULT_CAP, value)
        self.assertIn("ZUVO_PULL_MAX_BYTES='0' — must be a positive byte count", err)
        self.assertIn("there is no unlimited setting, raise the number instead", err)

    def test_one_is_the_smallest_accepted_value(self):
        os.environ["ZUVO_PULL_MAX_BYTES"] = "1"
        value, _out, err = self.capture(self.mod._pull_max_bytes)
        self.assertEqual(1, value)
        self.assertEqual("", err)

    def test_negative_falls_back_to_default_with_the_positive_warning(self):
        os.environ["ZUVO_PULL_MAX_BYTES"] = "-1"
        value, _out, err = self.capture(self.mod._pull_max_bytes)
        self.assertEqual(DEFAULT_CAP, value)
        self.assertIn("ZUVO_PULL_MAX_BYTES='-1' — must be a positive byte count", err)

    def test_positive_value_is_used_with_surrounding_space_stripped(self):
        os.environ["ZUVO_PULL_MAX_BYTES"] = " 4096 "
        value, _out, err = self.capture(self.mod._pull_max_bytes)
        self.assertEqual(4096, value)
        self.assertEqual("", err)

    def test_value_boundary_rejects_zero_and_minus_one_accepts_one(self):
        # `value <= 0`: 0 is the equal case (rejected), 1 and -1 the two sides.
        for raw, expected, warned in (("0", DEFAULT_CAP, True), ("1", 1, False), ("-1", DEFAULT_CAP, True)):
            with self.subTest(raw=raw):
                os.environ["ZUVO_PULL_MAX_BYTES"] = raw
                value, _out, err = self.capture(self.mod._pull_max_bytes)
                self.assertEqual(expected, value)
                self.assertEqual(warned, "must be a positive byte count" in err)

    def test_every_override_class_resolves_as_documented(self):
        cases = (
            (None, DEFAULT_CAP, ""),
            ("abc", DEFAULT_CAP, "ZUVO_PULL_MAX_BYTES='abc' — not an integer"),
            ("0", DEFAULT_CAP, "ZUVO_PULL_MAX_BYTES='0' — must be a positive byte count"),
            ("-5", DEFAULT_CAP, "ZUVO_PULL_MAX_BYTES='-5' — must be a positive byte count"),
            ("4096", 4096, ""),
        )
        for raw, expected, warning in cases:
            with self.subTest(raw=raw):
                if raw is None:
                    os.environ.pop("ZUVO_PULL_MAX_BYTES", None)
                else:
                    os.environ["ZUVO_PULL_MAX_BYTES"] = raw
                value, _out, err = self.capture(self.mod._pull_max_bytes)
                self.assertEqual(expected, value)
                if warning:
                    self.assertIn(f"backlog: ignoring {warning}", err)
                else:
                    self.assertEqual("", err)

    def test_module_reads_the_override_at_import(self):
        mod = load_backlog(self.zuvo, extra_env={"ZUVO_PULL_MAX_BYTES": "4096"})
        self.assertEqual(4096, mod.PULL_MAX_BYTES)
        self.assertEqual(DEFAULT_CAP, self.mod.PULL_MAX_BYTES)


class DecompressBoundedTests(BacklogTestCase):
    def test_single_member_decodes_to_its_text(self):
        self.assertEqual('{"a": 1}\nzażółć\n', self.mod._decompress_bounded(gz('{"a": 1}\nzażółć\n')))

    def test_two_concatenated_members_decode_to_both_texts_joined(self):
        blob = gz("first\n") + gz("second\n")
        self.assertEqual("first\nsecond\n", self.mod._decompress_bounded(blob))

    def test_nul_padding_after_last_and_between_members_is_not_data(self):
        blob = gz("one\n") + b"\x00" * 512 + gz("two\n") + b"\x00" * 1024
        self.assertEqual("one\ntwo\n", self.mod._decompress_bounded(blob))

    def test_empty_member_decodes_to_empty_text(self):
        self.assertEqual("", self.mod._decompress_bounded(gz("")))

    def test_payload_exactly_at_the_cap_is_accepted(self):
        self.mod.PULL_MAX_BYTES = 10
        self.assertEqual("0123456789", self.mod._decompress_bounded(gz("0123456789")))

    def test_payload_one_byte_over_the_cap_raises_eoferror_naming_the_cap(self):
        self.mod.PULL_MAX_BYTES = 10
        with self.assertRaises(EOFError) as cm:
            self.mod._decompress_bounded(gz("0123456789A"))
        self.assertEqual("decompressed payload exceeds 10 bytes", str(cm.exception))

    def test_cap_boundary_equal_passes_and_one_over_raises(self):
        # `total > PULL_MAX_BYTES`: the equal case passes, one byte over refuses.
        self.mod.PULL_MAX_BYTES = 5
        self.assertEqual("abcde", self.mod._decompress_bounded(gz("abcde")))
        with self.assertRaises(EOFError) as cm:
            self.mod._decompress_bounded(gz("abcdef"))
        self.assertEqual("decompressed payload exceeds 5 bytes", str(cm.exception))
        self.assertEqual("abcd", self.mod._decompress_bounded(gz("abcd")))

    def test_truncation_check_fires_only_once_input_and_output_are_both_exhausted(self):
        # A multi-chunk member keeps returning output with input still pending: it must decode whole.
        big = "a" * (3 << 20)
        self.assertEqual(big, self.mod._decompress_bounded(gz(big)))
        # Cut mid-member after output was produced, and cut before any output: both refuse.
        for blob in (gz(big)[: len(gz(big)) // 2], gz("x" * 100)[:12]):
            with self.subTest(size=len(blob)), self.assertRaises(zlib.error) as cm:
                self.mod._decompress_bounded(blob)
            self.assertEqual("gzip stream ended before the final member was complete", str(cm.exception))

    def test_cap_counts_the_total_across_members(self):
        self.mod.PULL_MAX_BYTES = 9
        with self.assertRaises(EOFError) as cm:
            self.mod._decompress_bounded(gz("abcde") + gz("fghij"))
        self.assertEqual("decompressed payload exceeds 9 bytes", str(cm.exception))

    def test_truncated_member_raises_zlib_error_instead_of_partial_text(self):
        blob = gz(bytes(range(32, 127)) * 8)[:-4]
        with self.assertRaises(zlib.error) as cm:
            self.mod._decompress_bounded(blob)
        self.assertEqual("gzip stream ended before the final member was complete", str(cm.exception))

    def test_truncated_second_member_raises_after_a_complete_first(self):
        blob = gz("complete\n") + gz("cut short " * 50)[:-6]
        with self.assertRaises(zlib.error) as cm:
            self.mod._decompress_bounded(blob)
        self.assertIn("ended before the final member", str(cm.exception))

    def test_invalid_utf8_raises_unicode_decode_error(self):
        with self.assertRaises(UnicodeDecodeError) as cm:
            self.mod._decompress_bounded(gz(b"ok\n\xff\xfe\n"))
        self.assertEqual("utf-8", cm.exception.encoding)

    def test_trailing_partial_character_raises_on_the_final_decode(self):
        with self.assertRaises(UnicodeDecodeError) as cm:
            self.mod._decompress_bounded(gz("é".encode("utf-8")[:1]))
        self.assertIn("unexpected end of data", str(cm.exception))

    def test_multibyte_character_split_across_the_1mib_chunk_boundary_still_decodes(self):
        # 'a' + 'é'*N: byte 1<<20 is the SECOND byte of an 'é', so the first 1 MiB chunk ends mid-character.
        text = "a" + "é" * 600_000
        self.assertGreater(len(text.encode("utf-8")), 1 << 20)
        self.assertEqual(text, self.mod._decompress_bounded(gz(text)))


class DecompressBoundedBytesTests(BacklogTestCase):
    def test_returns_the_bytes_unchanged_including_non_utf8(self):
        raw = b"\xff\x00abc\n\xfe"
        out = self.mod._decompress_bounded_bytes(gz(raw))
        self.assertIsInstance(out, bytes)
        self.assertEqual(raw, out)

    def test_multi_member_with_nul_padding_concatenates(self):
        blob = gz(b"\xffone\n") + b"\x00" * 300 + gz(b"two\n") + b"\x00" * 7
        self.assertEqual(b"\xffone\ntwo\n", self.mod._decompress_bounded_bytes(blob))

    def test_bytes_payload_exactly_at_the_cap_is_accepted(self):
        self.mod.PULL_MAX_BYTES = 8
        self.assertEqual(b"\xff1234567", self.mod._decompress_bounded_bytes(gz(b"\xff1234567")))

    def test_bytes_payload_one_byte_over_the_cap_raises_eoferror_naming_the_cap(self):
        self.mod.PULL_MAX_BYTES = 8
        with self.assertRaises(EOFError) as cm:
            self.mod._decompress_bounded_bytes(gz(b"\xff12345678"))
        self.assertEqual("decompressed payload exceeds 8 bytes", str(cm.exception))

    def test_truncated_stream_raises_zlib_error(self):
        with self.assertRaises(zlib.error) as cm:
            self.mod._decompress_bounded_bytes(gz(bytes(range(256)) * 8)[:-4])
        self.assertEqual("gzip stream ended before the final member was complete", str(cm.exception))

    def test_bytes_cap_boundary_equal_passes_and_one_over_raises(self):
        # `len(out) > PULL_MAX_BYTES`: the equal case passes, one byte over refuses.
        self.mod.PULL_MAX_BYTES = 5
        self.assertEqual(b"\xffbcde", self.mod._decompress_bounded_bytes(gz(b"\xffbcde")))
        with self.assertRaises(EOFError) as cm:
            self.mod._decompress_bounded_bytes(gz(b"\xffbcdef"))
        self.assertEqual("decompressed payload exceeds 5 bytes", str(cm.exception))
        self.assertEqual(b"\xffbcd", self.mod._decompress_bounded_bytes(gz(b"\xffbcd")))

    def test_bytes_truncation_check_fires_only_once_input_and_output_are_both_exhausted(self):
        big = b"\xff" * (3 << 20)
        self.assertEqual(big, self.mod._decompress_bounded_bytes(gz(big)))
        for blob in (gz(big)[: len(gz(big)) // 2], gz(b"x" * 100)[:12]):
            with self.subTest(size=len(blob)), self.assertRaises(zlib.error) as cm:
                self.mod._decompress_bounded_bytes(blob)
            self.assertEqual("gzip stream ended before the final member was complete", str(cm.exception))


class BytesCapAcrossMembersTests(BacklogTestCase):
    def test_the_bytes_cap_counts_every_member_together(self):
        # Two 3-byte members: 6 bytes fit a cap of 6, and a cap of 5 refuses although each member fits.
        blob = gz(b"abc") + gz(b"def")
        self.mod.PULL_MAX_BYTES = 6
        self.assertEqual(b"abcdef", self.mod._decompress_bounded_bytes(blob))
        self.mod.PULL_MAX_BYTES = 5
        with self.assertRaises(EOFError) as cm:
            self.mod._decompress_bounded_bytes(blob)
        self.assertEqual("decompressed payload exceeds 5 bytes", str(cm.exception))


class PayloadEdgeTests(BacklogTestCase):
    """Payload shapes adversarial pass 2 named."""

    def test_nul_bytes_inside_a_member_are_data(self):
        self.assertEqual("a\x00b\n", self.mod._decompress_bounded(gz(b"a\x00b\n") + b"\x00\x00"))

    def test_trailing_bytes_that_are_not_gzip_are_refused(self):
        with self.assertRaises(zlib.error) as cm:
            self.mod._decompress_bounded(gz(b"ok\n") + b"garbage")
        self.assertIn("incorrect header check", str(cm.exception))

    def test_the_cap_counts_bytes_not_characters(self):
        # "é" is 2 bytes in UTF-8: 5 of them fill a 10-byte cap exactly, 6 are over it.
        self.mod.PULL_MAX_BYTES = 10
        self.assertEqual("é" * 5, self.mod._decompress_bounded(gz("é" * 5)))
        with self.assertRaises(EOFError):
            self.mod._decompress_bounded(gz("é" * 6))

    def test_over_cap_payload_propagates_eoferror_from_decode_payload(self):
        self.mod.PULL_MAX_BYTES = 4
        with self.assertRaises(EOFError) as cm:
            self.mod._decode_payload(gz(b"12345"))
        self.assertEqual("decompressed payload exceeds 4 bytes", str(cm.exception))

    def test_empty_gzip_stream_decodes_to_empty_text(self):
        self.assertEqual("", self.mod._decode_payload(gz(b"")))


class DecodePayloadTests(BacklogTestCase):
    def test_valid_payload_returns_its_text(self):
        self.assertEqual('{"x": 1}\n{"y": 2}\n', self.mod._decode_payload(gz('{"x": 1}\n{"y": 2}\n')))

    def test_non_utf8_records_exit_naming_the_exact_bad_count_and_that_nothing_changed(self):
        blob = gz(b'{"ok": 1}\n{"bad": "\xff"}\n{"bad": "\xfe\xfd"}\n')
        msg, _out, _err = self.exit_message(self.mod._decode_payload, blob)
        self.assertIn("backlog: 2 record(s) in the fleet namespace are not valid UTF-8", msg)
        self.assertIn("refusing to rebuild the index from a partial read; nothing was changed", msg)
        self.assertIn(f"{self.data}/*.jsonl", msg)

    def test_one_bad_record_among_many_is_counted_as_one(self):
        blob = gz(b"a\nb\n\x80\nc\n") + gz(b"d\n")
        msg, _out, _err = self.exit_message(self.mod._decode_payload, blob)
        self.assertIn(f"grep -lP '[\\x80-\\xFF]' {self.mod.DATA}/*.jsonl", msg)
        self.assertTrue(msg.startswith("backlog: 1 record(s) in the fleet namespace are not valid UTF-8 — "
                                       "refusing to rebuild the index from a partial read; "
                                       "nothing was changed."),
                        msg)

    def test_truncation_is_not_swallowed_as_a_decode_failure(self):
        with self.assertRaises(zlib.error) as cm:
            self.mod._decode_payload(gz("abc " * 100)[:-4])
        self.assertIn("ended before the final member", str(cm.exception))


class DecodesTests(BacklogTestCase):
    def test_valid_utf8_line_decodes(self):
        self.assertTrue(self.mod._decodes("zażółć".encode("utf-8")))
        self.assertTrue(self.mod._decodes(b""))

    def test_invalid_utf8_line_does_not(self):
        self.assertFalse(self.mod._decodes(b"abc\xff"))


if __name__ == "__main__":
    unittest.main()
