#!/usr/bin/env bash
# Generated by zuvo:write-tests. Medium unit test: temporary filesystem only.
set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TMP="$(mktemp -d)" || exit 1
trap 'rm -rf "$TMP"' EXIT
export HOME="$TMP/home" GIT_CONFIG_GLOBAL="$TMP/gitconfig" GIT_CONFIG_NOSYSTEM=1
mkdir -p "$HOME"
# shellcheck disable=SC1090
. "$ROOT/scripts/install.sh" >"$TMP/source.out" 2>&1 || exit 1

PASS=0; FAIL=0
t_ok() { printf '  PASS %s\n' "$1"; PASS=$((PASS + 1)); }
t_no() { printf '  FAIL %s\n' "$1"; FAIL=$((FAIL + 1)); }
SRC="$TMP/source.sh"; DST="$TMP/destination.sh"
printf 'current helper bytes\n' > "$SRC"
old_destination() { printf 'previous helper bytes\n' > "$DST"; }
old_intact() { [ "$(cat "$DST")" = 'previous helper bytes' ]; }
no_temp() { ! compgen -G "$TMP/.destination.sh.*" >/dev/null; }
fake_tool() {
  local dir="$TMP/$1" name="$2" body="$3"
  mkdir -p "$dir"
  printf '#!/bin/sh\n%s\n' "$body" > "$dir/$name"
  chmod +x "$dir/$name"
}

old_destination
rc=0; reason="$(install_file_atomic "$TMP/absent.sh" "$DST")" || rc=$?
if [ "$rc" -eq 1 ] && [ "$reason" = "source missing: $TMP/absent.sh" ] && old_intact; then
  t_ok "missing source is refused before destination changes"
else t_no "missing source was accepted or changed the destination"; fi

BLOCKED="$TMP/directory-destination"; mkdir -p "$BLOCKED"
rc=0; reason="$(install_file_atomic "$SRC" "$BLOCKED")" || rc=$?
if [ "$rc" -eq 1 ] && [ "$reason" = 'refused: the destination exists and is not a regular file' ] && \
   [ -z "$(ls -A "$BLOCKED")" ]; then
  t_ok "a directory destination is refused without moving a temp file inside"
else t_no "directory destination was changed or accepted"; fi

FIRST="$TMP/first-install.sh"
rc=0; reason="$(install_file_atomic "$SRC" "$FIRST")" || rc=$?
if [ "$rc" -eq 0 ] && [ -z "$reason" ] && [ -f "$FIRST" ] && \
   cmp -s "$SRC" "$FIRST" && [ ! -x "$FIRST" ] && \
   ! compgen -G "$TMP/.first-install.sh.*" >/dev/null; then
  t_ok "first install creates an exact regular file without temporary debris"
else t_no "first install failed or left incorrect bytes, mode, or debris"; fi

fake_tool failmk mktemp 'exit 43'
old_destination
rc=0; reason="$(PATH="$TMP/failmk:$PATH" install_file_atomic "$SRC" "$DST")" || rc=$?
if [ "$rc" -eq 1 ] && [ "$reason" = "mktemp failed (in $TMP)" ] && old_intact && no_temp; then
  t_ok "failed temp allocation leaves the previous file intact"
else t_no "mktemp failure was swallowed or changed the previous file"; fi

fake_tool failcp cp 'printf "partial bytes\\n" > "$2"; exit 43'
old_destination
rc=0; reason="$(PATH="$TMP/failcp:$PATH" install_file_atomic "$SRC" "$DST")" || rc=$?
if [ "$rc" -eq 1 ] && [ "$reason" = 'cp failed' ] && old_intact && no_temp; then
  t_ok "failed copy removes its partial temp and preserves the old file"
else t_no "failed copy left partial bytes or was reported successful"; fi

fake_tool trunc cp 'printf "truncated bytes\\n" > "$2"; exit 0'
old_destination
rc=0; reason="$(PATH="$TMP/trunc:$PATH" install_file_atomic "$SRC" "$DST")" || rc=$?
if [ "$rc" -eq 1 ] && [ "$reason" = 'content check failed (the copy differs from the source; the destination was left as it was)' ] && old_intact && no_temp; then
  t_ok "pre-move checksum rejects a successful but corrupt copy"
else t_no "corrupt staged bytes replaced the prior helper"; fi

fake_tool failchmod chmod 'exit 43'
old_destination
rc=0; reason="$(PATH="$TMP/failchmod:$PATH" install_file_atomic "$SRC" "$DST")" || rc=$?
if [ "$rc" -eq 1 ] && [ "$reason" = 'chmod failed' ] && old_intact && no_temp; then
  t_ok "chmod failure removes the temp and preserves the old helper"
else t_no "chmod failure was swallowed or left temp bytes"; fi

fake_tool failmv mv 'exit 43'
old_destination
rc=0; reason="$(PATH="$TMP/failmv:$PATH" install_file_atomic "$SRC" "$DST")" || rc=$?
if [ "$rc" -eq 1 ] && [ "$reason" = 'mv failed' ] && old_intact && no_temp; then
  t_ok "rename failure removes the temp and preserves the old helper"
else t_no "rename failure was swallowed or left temp bytes"; fi

fake_tool corruptmv mv '[ "$1" = -f ] && shift; printf "concurrent bytes\\n" > "$2"; rm -f "$1"'
old_destination
rc=0; reason="$(PATH="$TMP/corruptmv:$PATH" install_file_atomic "$SRC" "$DST")" || rc=$?
if [ "$rc" -eq 1 ] && [ "$reason" = 'content check failed after the move (the installed bytes differ from the source)' ] && \
   [ "$(cat "$DST")" = 'concurrent bytes' ] && no_temp; then
  t_ok "post-move checksum notices a destination changed after rename"
else t_no "post-move corruption was reported successful"; fi

old_destination
chmod +x "$SRC"
rc=0; reason="$(install_file_atomic "$SRC" "$DST")" || rc=$?
if [ "$rc" -eq 0 ] && [ -z "$reason" ] && [ -x "$DST" ] && cmp -s "$SRC" "$DST" && no_temp; then
  t_ok "successful copy installs exact executable source bytes"
else t_no "successful executable copy changed bytes, mode, or status"; fi

chmod -x "$SRC"
rc=0; reason="$(install_file_atomic "$SRC" "$DST")" || rc=$?
if [ "$rc" -eq 0 ] && [ -z "$reason" ] && [ ! -x "$DST" ] && cmp -s "$SRC" "$DST" && no_temp; then
  t_ok "successful copy follows the non-executable source mode"
else t_no "non-executable copy changed bytes, mode, or status"; fi

printf '  --- install atomic file: PASS=%s FAIL=%s\n' "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ]
