# Generated by zuvo:write-tests
"""scripts/zuvo-home/backlog — everything that talks to the collector: collector_ssh,
_collector_host, pull, cmd_sync, cmd_pull, report_pull.

ssh is never run: the fake subprocess.run executes the remote command through the real /bin/sh
against a sandbox data dir (the module's DATA / COLLECTOR_ENV are pointed at it), and the push of
backlog-collect.py is a CompletedProcess or an exception the test controls.
"""

import contextlib
import io
import json
import os
import subprocess
import sys
import unittest
from unittest import mock

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from backlog_testlib import (  # noqa: E402
    BacklogTestCase, item, load_backlog, rec, write_jsonl,
)


class CollectorSshTests(BacklogTestCase):
    def test_no_collector_host_exits_by_name_and_never_runs_ssh(self):
        self.mod.VPS = ""
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "true", 5, "probe")
        self.assertEqual("backlog: no collector host configured (ZUVO_COLLECTOR_SSH or "
                         "~/.zuvo/collector.conf) — cannot probe", msg)
        self.assertEqual([], self.fake.calls)

    def test_exit_zero_returns_stdout_text_and_passes_host_command_and_timeout(self):
        out = self.mod.collector_ssh("printf 'hello\\nworld\\n'", 7, "probe")
        self.assertEqual("hello\nworld\n", out)
        argv, kw = self.fake.ssh_calls[0]
        self.assertEqual(["ssh", "-o", "ConnectTimeout=10", "fake-collector",
                          "printf 'hello\\nworld\\n'"], argv)
        self.assertEqual(7, kw["timeout"])
        self.assertTrue(kw["text"])
        self.assertTrue(kw["capture_output"])

    def test_binary_returns_bytes_and_asks_for_non_text_output(self):
        out = self.mod.collector_ssh("printf 'hi'", 7, "probe", binary=True)
        self.assertEqual(b"hi", out)
        self.assertFalse(self.fake.ssh_calls[0][1]["text"])

    def test_timeout_exits_naming_host_and_seconds_and_that_nothing_changed(self):
        self.fake.ssh_result = subprocess.TimeoutExpired(["ssh"], 7)
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "true", 7, "probe")
        self.assertEqual("backlog: the collector fake-collector did not answer within 7s — cannot probe; "
                         "nothing was changed", msg)

    def test_oserror_exits_saying_ssh_could_not_run_with_the_reason(self):
        self.fake.ssh_result = FileNotFoundError("no ssh here")
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "true", 7, "probe")
        self.assertIn("backlog: could not run ssh to the collector fake-collector (no ssh here)", msg)
        self.assertTrue(msg.endswith("— cannot probe; nothing was changed"))

    def test_nonzero_exit_names_the_status_and_the_last_stderr_line(self):
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "printf 'a\\nb\\nlast\\n' >&2; exit 7",
                                        7, "probe")
        self.assertIn("(exit 7: last)", msg)
        self.assertNotIn("exit 7: a", msg)
        self.assertTrue(msg.startswith(
            "backlog: ssh to the collector fake-collector, or the command it ran there, failed"))
        self.assertTrue(msg.endswith("— cannot probe; nothing was changed"))

    def test_nonzero_exit_with_empty_stderr_says_no_stderr(self):
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "exit 7", 7, "probe")
        self.assertIn("(exit 7: no stderr)", msg)

    def test_nonzero_exit_with_whitespace_only_stderr_says_no_stderr(self):
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "printf '  \\n\\n' >&2; exit 9", 7, "probe")
        self.assertIn("(exit 9: no stderr)", msg)

    def test_binary_mode_decodes_stderr_bytes_with_replacement(self):
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "printf 'bad \\377 thing\\n' >&2; exit 2",
                                        7, "probe", binary=True)
        self.assertIn("(exit 2: bad � thing)", msg)

    def test_soft_rc_matching_the_exit_status_returns_none(self):
        self.assertIsNone(self.mod.collector_ssh("echo x >&2; exit 4", 7, "probe", soft_rc=4))

    def test_soft_rc_not_matching_the_exit_status_still_exits(self):
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "exit 5", 7, "probe", soft_rc=4)
        self.assertIn("(exit 5: no stderr)", msg)

    def test_without_soft_rc_the_soft_status_is_an_error(self):
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "echo locked >&2; exit 4", 7, "probe")
        self.assertIn("(exit 4: locked)", msg)

    def test_soft_rc_zero_is_honoured_because_the_check_is_is_not_none(self):
        self.assertIsNone(self.mod.collector_ssh("echo out", 7, "probe", soft_rc=0))


class CollectorHostTests(BacklogTestCase):
    def setUp(self):
        super().setUp()
        self.zhome = os.path.join(self.tmp, "zhome")
        os.makedirs(self.zhome)
        os.environ.pop("ZUVO_COLLECTOR_SSH", None)
        os.environ["ZUVO_HOME"] = self.zhome

    def conf(self, text, home=None):
        with open(os.path.join(home or self.zhome, "collector.conf"), "w", encoding="utf-8") as f:
            f.write(text)

    def test_env_wins_over_the_conf_file_and_is_stripped(self):
        self.conf('ZUVO_COLLECTOR_SSH="h2"\n')
        os.environ["ZUVO_COLLECTOR_SSH"] = "  h1  "
        self.assertEqual("h1", self.mod._collector_host())

    def test_whitespace_only_env_falls_through_to_the_conf(self):
        self.conf('ZUVO_COLLECTOR_SSH="h2"\n')
        os.environ["ZUVO_COLLECTOR_SSH"] = "   "
        self.assertEqual("h2", self.mod._collector_host())

    def test_conf_value_in_double_quotes_is_unquoted(self):
        self.conf('# collector\n\n  ZUVO_COLLECTOR_SSH = "h2"  \n')
        self.assertEqual("h2", self.mod._collector_host())

    def test_conf_value_in_single_quotes_is_unquoted(self):
        self.conf("ZUVO_COLLECTOR_SSH='user@h3'\n")
        self.assertEqual("user@h3", self.mod._collector_host())

    def test_conf_value_keeps_an_equals_sign_after_the_first(self):
        self.conf("ZUVO_COLLECTOR_SSH=h4=x\n")
        self.assertEqual("h4=x", self.mod._collector_host())

    def test_without_zuvo_home_reads_dot_zuvo_under_home(self):
        os.environ.pop("ZUVO_HOME")
        home = os.path.join(self.tmp, "home")
        os.makedirs(os.path.join(home, ".zuvo"))
        self.conf("ZUVO_COLLECTOR_SSH=h-home\n", home=os.path.join(home, ".zuvo"))
        os.environ["HOME"] = home
        self.assertEqual("h-home", self.mod._collector_host())

    def test_no_env_and_no_conf_is_empty(self):
        self.assertEqual("", self.mod._collector_host())

    def test_conf_without_the_key_is_empty(self):
        self.conf("OTHER=1\n")
        self.assertEqual("", self.mod._collector_host())

    def test_import_takes_vps_from_the_conf(self):
        self.conf('ZUVO_COLLECTOR_SSH="h-import"\n')
        mod = load_backlog(self.zuvo, collector_ssh=None, extra_env={"ZUVO_HOME": self.zhome})
        self.assertEqual("h-import", mod.VPS)

    def test_conf_key_with_the_same_prefix_is_not_the_host(self):
        # Regression (X8): `startswith` took ZUVO_COLLECTOR_SSH_OPTS's value for the host.
        self.conf("ZUVO_COLLECTOR_SSH_OPTS=-p 2222\nZUVO_COLLECTOR_SSH=real-host\n")
        self.assertEqual("real-host", self.mod._collector_host())

    def test_conf_export_form_is_read(self):
        self.conf("export ZUVO_COLLECTOR_SSH='ex-host'\n")
        self.assertEqual("ex-host", self.mod._collector_host())

    def test_bare_key_is_skipped_and_a_later_assignment_wins(self):
        # Regression (X8): a bare key raised IndexError from split("=", 1)[1].
        self.conf("ZUVO_COLLECTOR_SSH\nZUVO_COLLECTOR_SSH=after-bare\n")
        self.assertEqual("after-bare", self.mod._collector_host())

    def test_bare_key_alone_means_no_host(self):
        self.conf("ZUVO_COLLECTOR_SSH\n")
        self.assertEqual("", self.mod._collector_host())

    def test_bare_key_does_not_break_import(self):
        # Regression (X8): _collector_host runs at import, so the bare key killed every command.
        self.conf("ZUVO_COLLECTOR_SSH\n")
        mod = load_backlog(self.zuvo, collector_ssh=None, extra_env={"ZUVO_HOME": self.zhome})
        self.assertEqual("", mod.VPS)


class PullTests(BacklogTestCase):
    def write(self, name, records):
        write_jsonl(os.path.join(self.data, name), records)

    def test_keeps_only_the_newest_run_per_host(self):
        self.write("a.jsonl", [
            rec("hostA", "r1", 1.0, [item("hostA", "repo", "A-OLD")]),
            rec("hostA", "r2", 2.0, [item("hostA", "repo", "A-1"), item("hostA", "repo", "A-2")]),
        ])
        self.write("b.jsonl", [rec("hostB", "b1", 1.5, [item("hostB", "repo", "B-1")])])
        items, strays, newest = self.mod.pull()
        self.assertEqual(["A-1", "A-2", "B-1"], [i["item_id"] for i in items])
        self.assertEqual(["A-1", "A-2", "B-1"], [i["item_id"] for i in self.index_items()])
        self.assertEqual({"hostA": (2.0, "r2"), "hostB": (1.5, "b1")}, newest)
        self.assertEqual([], strays)

    def test_an_older_run_seen_later_does_not_replace_the_newer(self):
        self.write("a.jsonl", [
            rec("hostA", "r2", 2.0, [item("hostA", "repo", "NEW")]),
            rec("hostA", "r1", 1.0, [item("hostA", "repo", "OLD")]),
        ])
        items, _s, newest = self.mod.pull()
        self.assertEqual(["NEW"], [i["item_id"] for i in items])
        self.assertEqual({"hostA": (2.0, "r2")}, newest)

    def test_equal_timestamps_keep_the_first_run_seen(self):
        self.write("a.jsonl", [
            rec("hostA", "r1", 1.0, [item("hostA", "repo", "FIRST")]),
            rec("hostA", "r2", 1.0, [item("hostA", "repo", "SECOND")]),
        ])
        items, _s, newest = self.mod.pull()
        self.assertEqual(["FIRST"], [i["item_id"] for i in items])
        self.assertEqual({"hostA": (1.0, "r1")}, newest)

    def test_batches_of_the_same_run_are_concatenated(self):
        self.write("a.jsonl", [
            rec("hostA", "r1", 1.0, [item("hostA", "repo", "A-1")], batch=0, batches=2),
            rec("hostA", "r1", 1.1, [item("hostA", "repo", "A-2")], batch=1, batches=2),
        ])
        items, _s, newest = self.mod.pull()
        self.assertEqual(["A-1", "A-2"], [i["item_id"] for i in items])
        self.assertEqual({"hostA": (1.1, "r1")}, newest)

    def test_records_without_payload_host_or_valid_json_are_skipped(self):
        self.write("a.jsonl", [
            "{not json",
            {"received_at": 5.0},
            {"received_at": 5.0, "payload": None},
            {"received_at": 5.0, "payload": {"run_id": "x", "items": [item("?", "r", "NOHOST")]}},
            {"received_at": 5.0,
             "payload": {"host": "", "run_id": "x", "items": [item("?", "r", "EMPTYHOST")]}},
            rec("hostA", "r1", 1.0, [item("hostA", "repo", "KEPT")]),
        ])
        items, _s, newest = self.mod.pull()
        self.assertEqual(["KEPT"], [i["item_id"] for i in items])
        self.assertEqual({"hostA": (1.0, "r1")}, newest)

    def test_missing_or_null_items_count_as_no_items(self):
        self.write("a.jsonl", [
            rec("hostA", "r1", 1.0, omit_items=True),
            {"received_at": 1.0, "payload": {"host": "hostB", "run_id": "b1", "items": None}},
        ])
        items, _s, newest = self.mod.pull()
        self.assertEqual([], items)
        self.assertEqual({"hostA": (1.0, "r1"), "hostB": (1.0, "b1")}, newest)
        self.assertEqual(0, self.read_meta()["items"])

    def test_strays_come_only_from_the_chosen_run_and_meta_records_everything(self):
        self.write("a.jsonl", [
            rec("hostA", "r1", 1.0, [item("hostA", "repo", "OLD")], strays=["/old/wt/memory/backlog.md"]),
            rec("hostA", "r2", 2.0, [item("hostA", "repo", "A-1")], strays=["/new/wt/memory/backlog.md"]),
            rec("hostB.lan", "b1", 3.0, [item("hostB.lan", "repo", "B-1"), item("hostB.lan", "repo", "B-2")]),
        ])
        _items, strays, _n = self.mod.pull()
        self.assertEqual([{"host": "hostA", "path": "/new/wt/memory/backlog.md"}], strays)
        self.assertEqual({
            "hosts": {"hostA": {"received_at": 2.0, "run_id": "r2"},
                      "hostB.lan": {"received_at": 3.0, "run_id": "b1"}},
            "strays": [{"host": "hostA", "path": "/new/wt/memory/backlog.md"}],
            "items": 3,
        }, self.read_meta())

    def test_remote_command_targets_the_data_dir_with_120s_and_binary_output(self):
        os.makedirs(self.data)
        self.mod.pull()
        argv, kw = self.fake.ssh_calls[0]
        self.assertTrue(argv[-1].startswith(f"d={self.data}; "))
        self.assertIn('gzip -1 -c -- "$@"', argv[-1])
        self.assertEqual(120, kw["timeout"])
        self.assertFalse(kw["text"])

    def test_empty_data_dir_writes_an_empty_index_and_zero_meta(self):
        os.makedirs(self.data)
        self.seed_index()
        self.assertEqual(([], [], {}), self.mod.pull())
        self.assertEqual("", self.read_index())
        self.assertEqual({"hosts": {}, "strays": [], "items": 0}, self.read_meta())

    def test_missing_data_dir_exits_as_moved_and_leaves_the_index(self):
        before = self.seed_index()
        msg, _o, _e = self.exit_message(self.mod.pull)
        self.assertIn(f"backlog data dir {self.data} does not exist on the collector (moved?)", msg)
        self.assertIn("cannot pull the fleet index; nothing was changed", msg)
        self.assertEqual(before, self.read_index())

    def test_unreadable_data_dir_with_unreadable_ok_returns_none(self):
        os.makedirs(self.data)
        before = self.seed_index()
        self.chmod_locked(self.data)
        self.assertIsNone(self.mod.pull(unreadable_ok=True))
        self.assertEqual(before, self.read_index())

    def test_unreadable_data_dir_without_unreadable_ok_exits_as_unreadable(self):
        os.makedirs(self.data)
        before = self.seed_index()
        self.chmod_locked(self.data)
        msg, _o, _e = self.exit_message(self.mod.pull)
        self.assertIn(f"(exit 4: backlog data dir {self.data} is not readable by this user)", msg)
        self.assertEqual(before, self.read_index())

    def test_data_dir_behind_an_unsearchable_ancestor_is_unreadable_not_missing(self):
        os.makedirs(self.data)
        ancestor = os.path.dirname(self.data)
        self.chmod_locked(ancestor)
        self.assertIsNone(self.mod.pull(unreadable_ok=True))
        msg, _o, _e = self.exit_message(self.mod.pull)
        self.assertIn("is not readable by this user", msg)
        self.assertNotIn("moved?", msg)

    def test_data_path_that_is_a_file_exits_even_when_unreadable_is_ok(self):
        os.makedirs(os.path.dirname(self.data))
        with open(self.data, "w") as f:
            f.write("x\n")
        msg, _o, _e = self.exit_message(self.mod.pull, unreadable_ok=True)
        self.assertIn(f"backlog data dir {self.data} exists but is not a directory", msg)

    def test_dangling_symlink_is_named_as_broken_not_moved(self):
        os.makedirs(os.path.dirname(self.data))
        os.symlink(os.path.join(self.tmp, "gone-target"), self.data)
        msg, _o, _e = self.exit_message(self.mod.pull, unreadable_ok=True)
        self.assertIn(f"backlog data dir {self.data} is a broken symlink", msg)

    def test_file_ancestor_is_named(self):
        afile = os.path.join(self.tmp, "afile")
        with open(afile, "w") as f:
            f.write("x\n")
        self.mod.DATA = os.path.join(afile, "data")
        msg, _o, _e = self.exit_message(self.mod.pull, unreadable_ok=True)
        self.assertIn(f"backlog data dir {afile}/data: {afile} is not a directory", msg)

    def test_an_unreadable_backlog_file_fails_the_pull_and_keeps_the_index(self):
        self.write("a.jsonl", [rec("hostA", "r1", 1.0, [item("hostA", "repo", "A-1")])])
        self.write("b.jsonl", [rec("hostB", "b1", 1.0, [])])
        before = self.seed_index()
        self.chmod_locked(os.path.join(self.data, "b.jsonl"))
        msg, _o, _e = self.exit_message(self.mod.pull)
        self.assertIn("b.jsonl", msg)
        self.assertIn("cannot pull the fleet index; nothing was changed", msg)
        self.assertEqual(before, self.read_index())

    def test_corrupt_payload_exits_as_undecompressable_and_keeps_the_index(self):
        before = self.seed_index()
        self.fake.ssh_result = subprocess.CompletedProcess(["ssh"], 0, b"not gzip", b"")
        msg, _o, _e = self.exit_message(self.mod.pull)
        self.assertIn("backlog: the payload from the collector fake-collector could not be decompressed", msg)
        self.assertTrue(msg.endswith("— cannot pull the fleet index; nothing was changed"))
        self.assertEqual(before, self.read_index())

    def test_non_utf8_record_refuses_the_whole_pull_by_count(self):
        os.makedirs(self.data)
        with open(os.path.join(self.data, "a.jsonl"), "wb") as f:
            f.write(json.dumps(rec("hostA", "r1", 1.0, [])).encode() + b"\n" + b'{"bad": "\xff"}\n')
        before = self.seed_index()
        msg, _o, _e = self.exit_message(self.mod.pull)
        self.assertIn("backlog: 1 record(s) in the fleet namespace are not valid UTF-8", msg)
        self.assertEqual(before, self.read_index())

    def test_incomplete_newest_run_does_not_replace_the_complete_one(self):
        # Regression PARTIAL-RUN-WINS (X8): r2 has only batch 0 of 2; its newer timestamp used to make it
        # the chosen run and drop the complete r1.
        self.write("a.jsonl", [
            rec("hostA", "r1", 1.0, [item("hostA", "repo", "R1-B0")], batch=0, batches=2),
            rec("hostA", "r1", 1.1, [item("hostA", "repo", "R1-B1")], batch=1, batches=2),
            rec("hostA", "r2", 2.0, [item("hostA", "repo", "R2-B0")], batch=0, batches=2),
        ])
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            items, _s, newest = self.mod.pull()
        self.assertEqual(["R1-B0", "R1-B1"], [i["item_id"] for i in items])
        self.assertEqual(["R1-B0", "R1-B1"], [i["item_id"] for i in self.index_items()])
        self.assertEqual({"hostA": (1.1, "r1")}, newest)
        self.assertEqual("backlog: hostA: newest run r2 is incomplete (1/2 batches) — kept the complete "
                         "run r1\n", err.getvalue())

    def test_complete_run_needs_every_declared_batch(self):
        # Boundary of `len(seen) >= of`: 2 of 2 is complete, so the newer r2 wins with no warning.
        self.write("a.jsonl", [
            rec("hostA", "r1", 1.0, [item("hostA", "repo", "R1-B0")], batch=0, batches=1),
            rec("hostA", "r2", 2.0, [item("hostA", "repo", "R2-B0")], batch=0, batches=2),
            rec("hostA", "r2", 2.1, [item("hostA", "repo", "R2-B1")], batch=1, batches=2),
        ])
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            items, _s, newest = self.mod.pull()
        self.assertEqual(["R2-B0", "R2-B1"], [i["item_id"] for i in items])
        self.assertEqual({"hostA": (2.1, "r2")}, newest)
        self.assertEqual("", err.getvalue())

    def test_only_an_incomplete_run_is_used_and_named(self):
        self.write("a.jsonl", [
            rec("hostA", "r9", 3.0, [item("hostA", "repo", "R9-B1")], batch=1, batches=3),
        ])
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            items, _s, newest = self.mod.pull()
        self.assertEqual(["R9-B1"], [i["item_id"] for i in items])
        self.assertEqual({"hostA": (3.0, "r9")}, newest)
        self.assertEqual("backlog: hostA: run r9 is incomplete (1/3 batches) and no complete run exists — "
                         "using it; that host's items are short\n", err.getvalue())

    def test_older_incomplete_run_is_ignored_silently(self):
        self.write("a.jsonl", [
            rec("hostA", "old", 1.0, [item("hostA", "repo", "OLD")], batch=0, batches=2),
            rec("hostA", "new", 2.0, [item("hostA", "repo", "NEW")], batch=0, batches=1),
        ])
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            items, _s, _n = self.mod.pull()
        self.assertEqual(["NEW"], [i["item_id"] for i in items])
        self.assertEqual("", err.getvalue())

    def test_payload_without_batches_counts_as_one_whole_run(self):
        records = [{"received_at": 5.0, "payload": {"host": "legacy", "run_id": "L1",
                                                    "items": [item("legacy", "repo", "LEG-1")]}}]
        self.write("a.jsonl", records)
        items, _s, newest = self.mod.pull()
        self.assertEqual(["LEG-1"], [i["item_id"] for i in items])
        self.assertEqual({"legacy": (5.0, "L1")}, newest)

    def test_failed_meta_write_keeps_the_previous_index_and_meta(self):
        # Regression (X9): INDEX was rewritten in place before META, so a failure writing META left the
        # NEW index beside an empty META.
        self.write("a.jsonl", [rec("hostA", "r1", 1.0, [item("hostA", "repo", "NEW-1")])])
        self.seed_index('{"item_id": "OLD-1"}\n')
        with open(self.mod.META, "w") as f:
            json.dump({"hosts": {"old": {}}, "strays": [], "items": 1}, f)
        with mock.patch.object(self.mod.json, "dump", side_effect=OSError("disk full")), \
                self.assertRaises(OSError) as cm:
            self.mod.pull()
        self.assertEqual("disk full", str(cm.exception))
        self.assertEqual(["OLD-1"], [i["item_id"] for i in self.index_items()])
        with open(self.mod.META) as f:
            self.assertEqual({"hosts": {"old": {}}, "strays": [], "items": 1}, json.load(f))
        leftovers = [n for n in os.listdir(os.path.dirname(self.mod.INDEX)) if n.endswith(".tmp")]
        self.assertEqual([], leftovers)


class CmdSyncTests(BacklogTestCase):
    def setUp(self):
        super().setUp()
        write_jsonl(os.path.join(self.data, "a.jsonl"), [
            rec("hostA", "r1", 1.0, [item("hostA", "repo", "A-1"), item("hostA", "repo", "A-2")]),
        ])

    def set_collector_env(self, text):
        with open(self.collector_env, "w") as f:
            f.write(text)

    def push_env(self):
        self.assertEqual(1, len(self.fake.push_calls))
        return self.fake.push_calls[0][1]["env"]

    def test_local_codesift_token_is_stripped_and_no_token_fetch_runs(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "  tok-local  "
        self.capture(self.mod.cmd_sync)
        self.assertEqual("tok-local", self.push_env()["CODESIFT_COLLECTOR_TOKEN"])
        self.assertEqual(1, len(self.fake.ssh_calls))            # the pull only
        self.assertNotIn("collector.env", self.fake.ssh_calls[0][0][-1])

    def test_only_zuvo_collector_token_set_is_used(self):
        os.environ["ZUVO_COLLECTOR_TOKEN"] = "tok-zuvo-local"
        self.capture(self.mod.cmd_sync)
        self.assertEqual("tok-zuvo-local", self.push_env()["CODESIFT_COLLECTOR_TOKEN"])
        self.assertEqual(1, len(self.fake.ssh_calls))

    def test_codesift_token_wins_over_zuvo_token(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok-cs"
        os.environ["ZUVO_COLLECTOR_TOKEN"] = "tok-z"
        self.capture(self.mod.cmd_sync)
        self.assertEqual("tok-cs", self.push_env()["CODESIFT_COLLECTOR_TOKEN"])

    def test_without_local_token_fetches_codesift_token_from_collector_env(self):
        self.set_collector_env("CODESIFT_COLLECTOR_TOKEN=tok-1\n")
        self.capture(self.mod.cmd_sync)
        self.assertEqual("tok-1", self.push_env()["CODESIFT_COLLECTOR_TOKEN"])
        argv, kw = self.fake.ssh_calls[0]
        self.assertTrue(argv[-1].startswith(f". {self.collector_env} && "))
        self.assertEqual(60, kw["timeout"])

    def test_without_local_token_fetches_zuvo_token_from_collector_env(self):
        self.set_collector_env("ZUVO_COLLECTOR_TOKEN=tok-z\n")
        self.capture(self.mod.cmd_sync)
        self.assertEqual("tok-z", self.push_env()["CODESIFT_COLLECTOR_TOKEN"])

    def test_empty_fetched_token_exits_naming_both_variables_and_does_not_push(self):
        self.set_collector_env("CODESIFT_COLLECTOR_TOKEN=\n")
        msg, _o, _e = self.exit_message(self.mod.cmd_sync)
        self.assertEqual("backlog: the collector fake-collector has no CODESIFT_COLLECTOR_TOKEN "
                         "(or ZUVO_COLLECTOR_TOKEN) in its collector.env — not pushing without one; "
                         "nothing was changed", msg)
        self.assertEqual([], self.fake.push_calls)

    def test_missing_collector_env_is_that_failure_not_a_missing_token(self):
        msg, _o, _e = self.exit_message(self.mod.cmd_sync)
        self.assertIn("cannot fetch the collector token; nothing was changed", msg)
        self.assertIn("collector.env", msg)
        self.assertNotIn("has no CODESIFT_COLLECTOR_TOKEN", msg)
        self.assertEqual([], self.fake.push_calls)

    def test_push_runs_backlog_collect_with_push_flag_and_300s(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok"
        self.capture(self.mod.cmd_sync)
        argv, kw = self.fake.push_calls[0]
        self.assertEqual([sys.executable, os.path.join(self.zuvo, "backlog-collect.py"), "--push"], argv)
        self.assertEqual(300, kw["timeout"])
        self.assertTrue(kw["text"])

    def test_push_timeout_says_it_may_or_may_not_have_landed(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok"
        self.fake.push_result = subprocess.TimeoutExpired(["push"], 300)
        msg, _o, _e = self.exit_message(self.mod.cmd_sync)
        self.assertEqual("backlog: the push (backlog-collect.py --push) did not finish within 300s — it may "
                         "or may not have landed on the collector; the index was not refreshed", msg)
        self.assertEqual([], self.fake.ssh_calls)

    def test_push_oserror_says_nothing_was_pushed(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok"
        self.fake.push_result = OSError("exec format error")
        msg, _o, _e = self.exit_message(self.mod.cmd_sync)
        self.assertEqual("backlog: could not run backlog-collect.py (exec format error) — "
                         "nothing was pushed; the index was not refreshed", msg)

    def test_failed_push_exits_with_its_status_and_never_pulls(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok"
        before = self.seed_index()
        self.fake.push_result = subprocess.CompletedProcess([], 1, "", "batch 1 refused")
        msg, out, err = self.exit_message(self.mod.cmd_sync)
        self.assertEqual("backlog: the push (backlog-collect.py --push) failed (exit 1) — "
                         "the index was not refreshed", msg)
        self.assertEqual([], self.fake.ssh_calls)
        self.assertNotIn("index:", out)
        self.assertIn("batch 1 refused", err)
        self.assertEqual(before, self.read_index())

    def test_pull_failure_after_a_landed_push_says_the_push_landed(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok"
        self.mod.DATA = os.path.join(self.tmp, "nowhere", "backlog")
        msg, _o, _e = self.exit_message(self.mod.cmd_sync)
        self.assertIn("does not exist on the collector (moved?)", msg)
        self.assertTrue(msg.endswith("— cannot pull the fleet index; the local index was not changed, "
                                     "but the push above did land"))
        self.assertNotIn("nothing was changed", msg)

    def test_pull_exit_with_an_int_code_is_reported_as_a_failed_pull(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok"
        with mock.patch.object(self.mod, "pull", side_effect=SystemExit(3)):
            msg, _o, _e = self.exit_message(self.mod.cmd_sync)
        self.assertEqual("backlog: the pull failed (exit 3); the local index was not changed, "
                         "but the push above did land", msg)

    def test_unreadable_data_dir_reports_not_refreshed_and_returns(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok"
        before = self.seed_index()
        self.chmod_locked(self.data)
        ret, out, _e = self.capture(self.mod.cmd_sync)
        self.assertIsNone(ret)
        self.assertIn("index: not refreshed on this host — the collector's backlog data dir "
                      "is not readable", out)
        self.assertIn("the push above landed", out)
        self.assertEqual(before, self.read_index())

    def test_push_stdout_and_stderr_are_relayed_stripped(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok"
        self.fake.push_result = subprocess.CompletedProcess([], 0, "  pushed 1/1 \n", "\nwarn\n")
        _r, out, err = self.capture(self.mod.cmd_sync)
        self.assertEqual("pushed 1/1", out.splitlines()[0])
        self.assertEqual("warn\n", err)

    def test_success_prints_the_pull_report(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok"
        _r, out, err = self.capture(self.mod.cmd_sync)
        self.assertEqual([f"index: {self.mod.INDEX} — 2 items from 1 host(s)",
                          "  hostA: 2 items (run r1)"], out.splitlines())
        self.assertEqual("", err)
        self.assertEqual(["A-1", "A-2"], [i["item_id"] for i in self.index_items()])


class ReportPullTests(BacklogTestCase):
    def test_summary_and_per_host_lines_sorted_by_host(self):
        items = [item("beta", "r", "1"), item("alpha", "r", "2"), item("alpha", "r", "3")]
        newest = {"beta": (2.0, "b9"), "alpha": (1.0, "a2")}
        _r, out, _e = self.capture(self.mod.report_pull, items, [], newest)
        self.assertEqual([f"index: {self.mod.INDEX} — 3 items from 2 host(s)",
                          "  alpha: 2 items (run a2)",
                          "  beta: 1 items (run b9)"], out.splitlines())

    def test_host_with_no_items_reports_zero(self):
        _r, out, _e = self.capture(self.mod.report_pull, [item("other", "r", "1")], [],
                                   {"quiet": (1.0, "q1")})
        self.assertIn("  quiet: 0 items (run q1)", out.splitlines())

    def test_strays_add_the_worktree_fork_warning(self):
        _r, out, _e = self.capture(self.mod.report_pull, [], [{"host": "h", "path": "/p"}], {})
        self.assertEqual([f"index: {self.mod.INDEX} — 0 items from 0 host(s)",
                          "  ⚠ 1 worktree-fork copies flagged (see `backlog strays`)"], out.splitlines())

    def test_no_strays_no_warning(self):
        _r, out, _e = self.capture(self.mod.report_pull, [], [], {})
        self.assertNotIn("⚠", out)


class CmdPullTests(BacklogTestCase):
    def test_prints_the_report_of_a_successful_pull(self):
        write_jsonl(os.path.join(self.data, "a.jsonl"), [
            rec("mac.local", "m1", 1.0, [item("mac.local", "zuvo", "B-1")], strays=["/wt/memory/backlog.md"]),
        ])
        _r, out, _e = self.capture(self.mod.cmd_pull)
        self.assertEqual([f"index: {self.mod.INDEX} — 1 items from 1 host(s)",
                          "  mac.local: 1 items (run m1)",
                          "  ⚠ 1 worktree-fork copies flagged (see `backlog strays`)"], out.splitlines())

    def test_a_failed_pull_propagates_its_named_exit(self):
        msg, out, _e = self.exit_message(self.mod.cmd_pull)
        self.assertIn("does not exist on the collector (moved?)", msg)
        self.assertEqual("", out)


if __name__ == "__main__":
    unittest.main()
