# Generated by zuvo:write-tests
"""scripts/zuvo-home/backlog — everything that talks to the collector: collector_ssh,
_collector_host, pull, cmd_sync, cmd_pull, report_pull.

ssh is never run: the fake subprocess.run executes the remote command through the real /bin/sh
against a sandbox data dir (the module's DATA / COLLECTOR_ENV are pointed at it), and the push of
backlog-collect.py is a CompletedProcess or an exception the test controls.
"""

import contextlib
import io
import json
import os
import subprocess
import sys
import threading
import unittest
from unittest import mock

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from backlog_testlib import (  # noqa: E402
    REAL_RUN, BacklogTestCase, item, load_backlog, rec, write_jsonl,
)


class CollectorSshTests(BacklogTestCase):
    def test_no_collector_host_exits_by_name_and_never_runs_ssh(self):
        self.mod.VPS = ""
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "true", 5, "probe")
        self.assertEqual("backlog: no collector host configured (ZUVO_COLLECTOR_SSH or "
                         "~/.zuvo/collector.conf) — cannot probe", msg)
        self.assertEqual([], self.fake.calls)

    def test_exit_zero_returns_stdout_text_and_passes_host_command_and_timeout(self):
        out = self.mod.collector_ssh("printf 'hello\\nworld\\n'", 7, "probe")
        self.assertEqual("hello\nworld\n", out)
        argv, kw = self.fake.ssh_calls[0]
        self.assertEqual(["ssh", "-o", "ConnectTimeout=10", "fake-collector",
                          "printf 'hello\\nworld\\n'"], argv)
        self.assertEqual(7, kw["timeout"])
        self.assertTrue(kw["text"])
        self.assertTrue(kw["capture_output"])

    def test_binary_returns_bytes_and_asks_for_non_text_output(self):
        out = self.mod.collector_ssh("printf 'hi'", 7, "probe", binary=True)
        self.assertEqual(b"hi", out)
        self.assertFalse(self.fake.ssh_calls[0][1]["text"])

    def test_timeout_exits_naming_host_and_seconds_and_that_nothing_changed(self):
        self.fake.ssh_result = subprocess.TimeoutExpired(["ssh"], 7)
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "true", 7, "probe")
        self.assertEqual("backlog: the collector fake-collector did not answer within 7s — cannot probe; "
                         "nothing was changed", msg)

    def test_oserror_exits_saying_ssh_could_not_run_with_the_reason(self):
        self.fake.ssh_result = FileNotFoundError("no ssh here")
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "true", 7, "probe")
        self.assertIn("backlog: could not run ssh to the collector fake-collector (no ssh here)", msg)
        self.assertTrue(msg.endswith("— cannot probe; nothing was changed"))

    def test_nonzero_exit_names_the_status_and_the_last_stderr_line(self):
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "printf 'a\\nb\\nlast\\n' >&2; exit 7",
                                        7, "probe")
        self.assertIn("(exit 7: last)", msg)
        self.assertNotIn("exit 7: a", msg)
        self.assertTrue(msg.startswith(
            "backlog: ssh to the collector fake-collector, or the command it ran there, failed"))
        self.assertTrue(msg.endswith("— cannot probe; nothing was changed"))

    def test_nonzero_exit_with_empty_stderr_says_no_stderr(self):
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "exit 7", 7, "probe")
        self.assertIn("(exit 7: no stderr)", msg)

    def test_nonzero_exit_with_whitespace_only_stderr_says_no_stderr(self):
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "printf '  \\n\\n' >&2; exit 9", 7, "probe")
        self.assertIn("(exit 9: no stderr)", msg)

    def test_binary_mode_decodes_stderr_bytes_with_replacement(self):
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "printf 'bad \\377 thing\\n' >&2; exit 2",
                                        7, "probe", binary=True)
        self.assertIn("(exit 2: bad � thing)", msg)

    def test_soft_rc_matching_the_exit_status_returns_none(self):
        self.assertIsNone(self.mod.collector_ssh("echo x >&2; exit 4", 7, "probe", soft_rc=4))

    def test_soft_rc_not_matching_the_exit_status_still_exits(self):
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "exit 5", 7, "probe", soft_rc=4)
        self.assertIn("(exit 5: no stderr)", msg)

    def test_without_soft_rc_the_soft_status_is_an_error(self):
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "echo locked >&2; exit 4", 7, "probe")
        self.assertIn("(exit 4: locked)", msg)

    def test_soft_rc_zero_is_honoured_because_the_check_is_is_not_none(self):
        self.assertIsNone(self.mod.collector_ssh("echo out", 7, "probe", soft_rc=0))

    def test_soft_rc_returns_none_only_when_set_and_equal(self):
        # `soft_rc is not None and returncode == soft_rc`: set+equal -> None; set+different and
        # unset+same status each exit with the status.
        self.assertIsNone(self.mod.collector_ssh("exit 4", 7, "probe", soft_rc=4))
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "exit 5", 7, "probe", soft_rc=4)
        self.assertIn("(exit 5: no stderr)", msg)
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "exit 4", 7, "probe", soft_rc=None)
        self.assertIn("(exit 4: no stderr)", msg)

    def test_last_stderr_line_or_no_stderr_when_empty(self):
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "printf 'one\\ntwo\\n' >&2; exit 3",
                                        7, "probe")
        self.assertIn("(exit 3: two)", msg)
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "exit 3", 7, "probe")
        self.assertIn("(exit 3: no stderr)", msg)

    def test_binary_mode_returns_bytes_and_decodes_failure_stderr(self):
        self.assertEqual(b"\xffok", self.mod.collector_ssh("printf '\\377ok'", 7, "probe", binary=True))
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "printf 'gone \\376\\n' >&2; exit 6",
                                        7, "probe", binary=True)
        self.assertIn("(exit 6: gone �)", msg)


class CollectorHostTests(BacklogTestCase):
    def setUp(self):
        super().setUp()
        self.zhome = os.path.join(self.tmp, "zhome")
        os.makedirs(self.zhome)
        os.environ.pop("ZUVO_COLLECTOR_SSH", None)
        os.environ["ZUVO_HOME"] = self.zhome

    def conf(self, text, home=None):
        with open(os.path.join(home or self.zhome, "collector.conf"), "w", encoding="utf-8") as f:
            f.write(text)

    def test_env_wins_over_the_conf_file_and_is_stripped(self):
        self.conf('ZUVO_COLLECTOR_SSH="h2"\n')
        os.environ["ZUVO_COLLECTOR_SSH"] = "  h1  "
        self.assertEqual("h1", self.mod._collector_host())

    def test_whitespace_only_env_falls_through_to_the_conf(self):
        self.conf('ZUVO_COLLECTOR_SSH="h2"\n')
        os.environ["ZUVO_COLLECTOR_SSH"] = "   "
        self.assertEqual("h2", self.mod._collector_host())

    def test_conf_value_in_double_quotes_is_unquoted(self):
        self.conf('# collector\n\n  ZUVO_COLLECTOR_SSH = "h2"  \n')
        self.assertEqual("h2", self.mod._collector_host())

    def test_conf_value_in_single_quotes_is_unquoted(self):
        self.conf("ZUVO_COLLECTOR_SSH='user@h3'\n")
        self.assertEqual("user@h3", self.mod._collector_host())

    def test_conf_value_keeps_an_equals_sign_after_the_first(self):
        self.conf("ZUVO_COLLECTOR_SSH=h4=x\n")
        self.assertEqual("h4=x", self.mod._collector_host())

    def test_without_zuvo_home_reads_dot_zuvo_under_home(self):
        os.environ.pop("ZUVO_HOME")
        home = os.path.join(self.tmp, "home")
        os.makedirs(os.path.join(home, ".zuvo"))
        self.conf("ZUVO_COLLECTOR_SSH=h-home\n", home=os.path.join(home, ".zuvo"))
        os.environ["HOME"] = home
        self.assertEqual("h-home", self.mod._collector_host())

    def test_no_env_and_no_conf_is_empty(self):
        self.assertEqual("", self.mod._collector_host())

    def test_conf_without_the_key_is_empty(self):
        self.conf("OTHER=1\n")
        self.assertEqual("", self.mod._collector_host())

    def test_import_takes_vps_from_the_conf(self):
        self.conf('ZUVO_COLLECTOR_SSH="h-import"\n')
        mod = load_backlog(self.zuvo, collector_ssh=None, extra_env={"ZUVO_HOME": self.zhome})
        self.assertEqual("h-import", mod.VPS)

    def test_conf_key_with_the_same_prefix_is_not_the_host(self):
        # Regression (X8): `startswith` took ZUVO_COLLECTOR_SSH_OPTS's value for the host.
        self.conf("ZUVO_COLLECTOR_SSH_OPTS=-p 2222\nZUVO_COLLECTOR_SSH=real-host\n")
        self.assertEqual("real-host", self.mod._collector_host())

    def test_conf_export_form_is_read(self):
        self.conf("export ZUVO_COLLECTOR_SSH='ex-host'\n")
        self.assertEqual("ex-host", self.mod._collector_host())

    def test_bare_key_is_skipped_and_a_later_assignment_wins(self):
        # Regression (X8): a bare key raised IndexError from split("=", 1)[1].
        self.conf("ZUVO_COLLECTOR_SSH\nZUVO_COLLECTOR_SSH=after-bare\n")
        self.assertEqual("after-bare", self.mod._collector_host())

    def test_bare_key_alone_means_no_host(self):
        self.conf("ZUVO_COLLECTOR_SSH\n")
        self.assertEqual("", self.mod._collector_host())

    def test_bare_key_does_not_break_import(self):
        # Regression (X8): _collector_host runs at import, so the bare key killed every command.
        self.conf("ZUVO_COLLECTOR_SSH\n")
        mod = load_backlog(self.zuvo, collector_ssh=None, extra_env={"ZUVO_HOME": self.zhome})
        self.assertEqual("", mod.VPS)

    def test_zuvo_home_decides_when_set_else_home_dot_zuvo(self):
        home = os.path.join(self.tmp, "home")
        os.makedirs(os.path.join(home, ".zuvo"))
        self.conf("ZUVO_COLLECTOR_SSH=h-home\n", home=os.path.join(home, ".zuvo"))
        self.conf("ZUVO_COLLECTOR_SSH=h-zuvo-home\n")
        os.environ["HOME"] = home
        self.assertEqual("h-zuvo-home", self.mod._collector_host())
        os.environ.pop("ZUVO_HOME")
        self.assertEqual("h-home", self.mod._collector_host())

    def test_exact_key_and_equals_sign_are_both_required(self):
        # `key == 'ZUVO_COLLECTOR_SSH' and sep`: a prefixed key WITH `=` and the exact key WITHOUT `=`
        # are each rejected by one operand alone.
        self.conf("ZUVO_COLLECTOR_SSH_OPTS=-p 2222\nZUVO_COLLECTOR_SSH\nZUVO_COLLECTOR_SSH=the-host\n")
        self.assertEqual("the-host", self.mod._collector_host())

    def test_prefix_and_bare_keys_before_the_real_line_leave_import_with_the_real_host(self):
        self.conf("ZUVO_COLLECTOR_SSH_OPTS=-p 2222\nZUVO_COLLECTOR_SSH\nexport ZUVO_COLLECTOR_SSH='real'\n")
        mod = load_backlog(self.zuvo, collector_ssh=None, extra_env={"ZUVO_HOME": self.zhome})
        self.assertEqual("real", mod.VPS)

    def test_resolution_order_env_then_conf_then_empty(self):
        os.environ["ZUVO_COLLECTOR_SSH"] = "h-env"
        self.conf("ZUVO_COLLECTOR_SSH=\"h-conf\"\n")
        self.assertEqual("h-env", self.mod._collector_host())
        os.environ.pop("ZUVO_COLLECTOR_SSH")
        self.assertEqual("h-conf", self.mod._collector_host())
        os.remove(os.path.join(self.zhome, "collector.conf"))
        self.assertEqual("", self.mod._collector_host())


class PullTests(BacklogTestCase):
    def write(self, name, records):
        write_jsonl(os.path.join(self.data, name), records)

    def test_keeps_only_the_newest_run_per_host(self):
        self.write("a.jsonl", [
            rec("hostA", "r1", 1.0, [item("hostA", "repo", "A-OLD")]),
            rec("hostA", "r2", 2.0, [item("hostA", "repo", "A-1"), item("hostA", "repo", "A-2")]),
        ])
        self.write("b.jsonl", [rec("hostB", "b1", 1.5, [item("hostB", "repo", "B-1")])])
        items, strays, newest = self.mod.pull()
        self.assertEqual(["A-1", "A-2", "B-1"], [i["item_id"] for i in items])
        self.assertEqual(["A-1", "A-2", "B-1"], [i["item_id"] for i in self.index_items()])
        self.assertEqual({"hostA": (2.0, "r2"), "hostB": (1.5, "b1")}, newest)
        self.assertEqual([], strays)
        self.assertEqual({"hosts": {"hostA": {"received_at": 2.0, "run_id": "r2"},
                                    "hostB": {"received_at": 1.5, "run_id": "b1"}},
                          "strays": [], "items": 3}, self.read_meta())

    def test_an_older_run_seen_later_does_not_replace_the_newer(self):
        self.write("a.jsonl", [
            rec("hostA", "r2", 2.0, [item("hostA", "repo", "NEW")]),
            rec("hostA", "r1", 1.0, [item("hostA", "repo", "OLD")]),
        ])
        items, _s, newest = self.mod.pull()
        self.assertEqual(["NEW"], [i["item_id"] for i in items])
        self.assertEqual({"hostA": (2.0, "r2")}, newest)

    def test_equal_timestamps_keep_the_first_run_seen(self):
        self.write("a.jsonl", [
            rec("hostA", "r1", 1.0, [item("hostA", "repo", "FIRST")]),
            rec("hostA", "r2", 1.0, [item("hostA", "repo", "SECOND")]),
        ])
        items, _s, newest = self.mod.pull()
        self.assertEqual(["FIRST"], [i["item_id"] for i in items])
        self.assertEqual({"hostA": (1.0, "r1")}, newest)

    def test_batches_of_the_same_run_are_concatenated(self):
        self.write("a.jsonl", [
            rec("hostA", "r1", 1.0, [item("hostA", "repo", "A-1")], batch=0, batches=2),
            rec("hostA", "r1", 1.1, [item("hostA", "repo", "A-2")], batch=1, batches=2),
        ])
        items, _s, newest = self.mod.pull()
        self.assertEqual(["A-1", "A-2"], [i["item_id"] for i in items])
        self.assertEqual({"hostA": (1.1, "r1")}, newest)

    def test_records_without_payload_host_or_valid_json_are_skipped(self):
        self.write("a.jsonl", [
            "{not json",
            {"received_at": 5.0},
            {"received_at": 5.0, "payload": None},
            {"received_at": 5.0, "payload": {"run_id": "x", "items": [item("?", "r", "NOHOST")]}},
            {"received_at": 5.0,
             "payload": {"host": "", "run_id": "x", "items": [item("?", "r", "EMPTYHOST")]}},
            rec("hostA", "r1", 1.0, [item("hostA", "repo", "KEPT")]),
        ])
        items, _s, newest = self.mod.pull()
        self.assertEqual(["KEPT"], [i["item_id"] for i in items])
        self.assertEqual({"hostA": (1.0, "r1")}, newest)

    def test_missing_or_null_items_count_as_no_items(self):
        self.write("a.jsonl", [
            rec("hostA", "r1", 1.0, omit_items=True),
            {"received_at": 1.0, "payload": {"host": "hostB", "run_id": "b1", "items": None}},
            rec("hostC", "c1", 1.0, [item("hostC", "repo", "C-1")]),
        ])
        items, _s, newest = self.mod.pull()
        self.assertEqual(["C-1"], [i["item_id"] for i in items])
        self.assertEqual({"hostA": (1.0, "r1"), "hostB": (1.0, "b1"), "hostC": (1.0, "c1")}, newest)
        self.assertEqual(1, self.read_meta()["items"])

    def test_strays_come_only_from_the_chosen_run_and_meta_records_everything(self):
        self.write("a.jsonl", [
            rec("hostA", "r1", 1.0, [item("hostA", "repo", "OLD")], strays=["/old/wt/memory/backlog.md"]),
            rec("hostA", "r2", 2.0, [item("hostA", "repo", "A-1")], strays=["/new/wt/memory/backlog.md"]),
            rec("hostB.lan", "b1", 3.0, [item("hostB.lan", "repo", "B-1"), item("hostB.lan", "repo", "B-2")]),
        ])
        _items, strays, _n = self.mod.pull()
        self.assertEqual([{"host": "hostA", "path": "/new/wt/memory/backlog.md"}], strays)
        self.assertEqual({
            "hosts": {"hostA": {"received_at": 2.0, "run_id": "r2"},
                      "hostB.lan": {"received_at": 3.0, "run_id": "b1"}},
            "strays": [{"host": "hostA", "path": "/new/wt/memory/backlog.md"}],
            "items": 3,
        }, self.read_meta())

    def test_remote_command_targets_the_data_dir_with_120s_and_binary_output(self):
        os.makedirs(self.data)
        self.mod.pull()
        argv, kw = self.fake.ssh_calls[0]
        self.assertTrue(argv[-1].startswith(f"d={self.data}; "))
        self.assertIn('gzip -1 -c -- "$@"', argv[-1])
        self.assertEqual(120, kw["timeout"])
        self.assertFalse(kw["text"])

    def test_empty_data_dir_writes_an_empty_index_and_zero_meta(self):
        os.makedirs(self.data)
        self.seed_index()
        self.assertEqual(([], [], {}), self.mod.pull())
        self.assertEqual("", self.read_index())
        self.assertEqual({"hosts": {}, "strays": [], "items": 0}, self.read_meta())

    def test_missing_data_dir_exits_as_moved_and_leaves_the_index(self):
        before = self.seed_index()
        msg, _o, _e = self.exit_message(self.mod.pull)
        self.assertIn(f"backlog data dir {self.data} does not exist on the collector (moved?)", msg)
        self.assertIn("cannot pull the fleet index; nothing was changed", msg)
        self.assertEqual(before, self.read_index())

    def test_unreadable_data_dir_with_unreadable_ok_returns_none(self):
        os.makedirs(self.data)
        before = self.seed_index()
        self.chmod_locked(self.data)
        self.assertIsNone(self.mod.pull(unreadable_ok=True))
        self.assertEqual(before, self.read_index())

    def test_unreadable_data_dir_without_unreadable_ok_exits_as_unreadable(self):
        os.makedirs(self.data)
        before = self.seed_index()
        self.chmod_locked(self.data)
        msg, _o, _e = self.exit_message(self.mod.pull)
        self.assertIn(f"(exit 4: backlog data dir {self.data} is not readable by this user)", msg)
        self.assertEqual(before, self.read_index())

    def test_data_dir_behind_an_unsearchable_ancestor_is_unreadable_not_missing(self):
        os.makedirs(self.data)
        ancestor = os.path.dirname(self.data)
        self.chmod_locked(ancestor)
        before = self.seed_index()
        self.assertIsNone(self.mod.pull(unreadable_ok=True))
        msg, _o, _e = self.exit_message(self.mod.pull)
        self.assertIn("is not readable by this user", msg)
        self.assertNotIn("moved?", msg)
        self.assertEqual(before, self.read_index())

    def test_data_path_that_is_a_file_exits_even_when_unreadable_is_ok(self):
        os.makedirs(os.path.dirname(self.data))
        with open(self.data, "w") as f:
            f.write("x\n")
        msg, _o, _e = self.exit_message(self.mod.pull, unreadable_ok=True)
        self.assertIn(f"backlog data dir {self.data} exists but is not a directory", msg)

    def test_dangling_symlink_is_named_as_broken_not_moved(self):
        os.makedirs(os.path.dirname(self.data))
        os.symlink(os.path.join(self.tmp, "gone-target"), self.data)
        msg, _o, _e = self.exit_message(self.mod.pull, unreadable_ok=True)
        self.assertIn(f"backlog data dir {self.data} is a broken symlink", msg)

    def test_file_ancestor_is_named(self):
        afile = os.path.join(self.tmp, "afile")
        with open(afile, "w") as f:
            f.write("x\n")
        self.mod.DATA = os.path.join(afile, "data")
        msg, _o, _e = self.exit_message(self.mod.pull, unreadable_ok=True)
        self.assertIn(f"backlog data dir {afile}/data: {afile} is not a directory", msg)

    def test_an_unreadable_backlog_file_fails_the_pull_and_keeps_the_index(self):
        self.write("a.jsonl", [rec("hostA", "r1", 1.0, [item("hostA", "repo", "A-1")])])
        self.write("b.jsonl", [rec("hostB", "b1", 1.0, [])])
        before = self.seed_index()
        self.chmod_locked(os.path.join(self.data, "b.jsonl"))
        msg, _o, _e = self.exit_message(self.mod.pull)
        self.assertIn("b.jsonl", msg)
        self.assertIn("cannot pull the fleet index; nothing was changed", msg)
        self.assertEqual(before, self.read_index())

    def test_corrupt_payload_exits_as_undecompressable_and_keeps_the_index(self):
        before = self.seed_index()
        self.fake.ssh_result = subprocess.CompletedProcess(["ssh"], 0, b"not gzip", b"")
        msg, _o, _e = self.exit_message(self.mod.pull)
        self.assertIn("backlog: the payload from the collector fake-collector could not be decompressed", msg)
        self.assertTrue(msg.endswith("— cannot pull the fleet index; nothing was changed"))
        self.assertEqual(before, self.read_index())

    def test_non_utf8_record_refuses_the_whole_pull_by_count(self):
        os.makedirs(self.data)
        with open(os.path.join(self.data, "a.jsonl"), "wb") as f:
            f.write(json.dumps(rec("hostA", "r1", 1.0, [])).encode() + b"\n" + b'{"bad": "\xff"}\n')
        before = self.seed_index()
        msg, _o, _e = self.exit_message(self.mod.pull)
        self.assertIn("backlog: 1 record(s) in the fleet namespace are not valid UTF-8", msg)
        self.assertEqual(before, self.read_index())

    def test_incomplete_newest_run_does_not_replace_the_complete_one(self):
        # Regression PARTIAL-RUN-WINS (X8): r2 has only batch 0 of 2; its newer timestamp used to make it
        # the chosen run and drop the complete r1.
        self.write("a.jsonl", [
            rec("hostA", "r1", 1.0, [item("hostA", "repo", "R1-B0")], batch=0, batches=2),
            rec("hostA", "r1", 1.1, [item("hostA", "repo", "R1-B1")], batch=1, batches=2),
            rec("hostA", "r2", 2.0, [item("hostA", "repo", "R2-B0")], batch=0, batches=2),
        ])
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            items, _s, newest = self.mod.pull()
        self.assertEqual(["R1-B0", "R1-B1"], [i["item_id"] for i in items])
        self.assertEqual(["R1-B0", "R1-B1"], [i["item_id"] for i in self.index_items()])
        self.assertEqual({"hostA": (1.1, "r1")}, newest)
        self.assertEqual("backlog: hostA: newest run r2 is incomplete (1/2 batches) — kept the complete "
                         "run r1\n", err.getvalue())

    def test_complete_run_needs_every_declared_batch(self):
        # Boundary of `len(seen) >= of`: 2 of 2 is complete, so the newer r2 wins with no warning.
        self.write("a.jsonl", [
            rec("hostA", "r1", 1.0, [item("hostA", "repo", "R1-B0")], batch=0, batches=1),
            rec("hostA", "r2", 2.0, [item("hostA", "repo", "R2-B0")], batch=0, batches=2),
            rec("hostA", "r2", 2.1, [item("hostA", "repo", "R2-B1")], batch=1, batches=2),
        ])
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            items, _s, newest = self.mod.pull()
        self.assertEqual(["R2-B0", "R2-B1"], [i["item_id"] for i in items])
        self.assertEqual({"hostA": (2.1, "r2")}, newest)
        self.assertEqual("", err.getvalue())

    def test_only_an_incomplete_run_is_used_and_named(self):
        self.write("a.jsonl", [
            rec("hostA", "r9", 3.0, [item("hostA", "repo", "R9-B1")], batch=1, batches=3),
        ])
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            items, _s, newest = self.mod.pull()
        self.assertEqual(["R9-B1"], [i["item_id"] for i in items])
        self.assertEqual({"hostA": (3.0, "r9")}, newest)
        self.assertEqual("backlog: hostA: run r9 is incomplete (1/3 batches) and no complete run exists — "
                         "using it; that host's items are short\n", err.getvalue())

    def test_older_incomplete_run_is_ignored_silently(self):
        self.write("a.jsonl", [
            rec("hostA", "old", 1.0, [item("hostA", "repo", "OLD")], batch=0, batches=2),
            rec("hostA", "new", 2.0, [item("hostA", "repo", "NEW")], batch=0, batches=1),
        ])
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            items, _s, _n = self.mod.pull()
        self.assertEqual(["NEW"], [i["item_id"] for i in items])
        self.assertEqual("", err.getvalue())

    def test_payload_without_batches_counts_as_one_whole_run(self):
        records = [{"received_at": 5.0, "payload": {"host": "legacy", "run_id": "L1",
                                                    "items": [item("legacy", "repo", "LEG-1")]}}]
        self.write("a.jsonl", records)
        items, _s, newest = self.mod.pull()
        self.assertEqual(["LEG-1"], [i["item_id"] for i in items])
        self.assertEqual({"legacy": (5.0, "L1")}, newest)

    def test_failed_meta_write_keeps_the_previous_index_and_meta(self):
        # Regression (X9): INDEX was rewritten in place before META, so a failure writing META left the
        # NEW index beside an empty META.
        self.write("a.jsonl", [rec("hostA", "r1", 1.0, [item("hostA", "repo", "NEW-1")])])
        self.seed_index('{"item_id": "OLD-1"}\n')
        with open(self.mod.META, "w") as f:
            json.dump({"hosts": {"old": {}}, "strays": [], "items": 1}, f)
        with mock.patch.object(self.mod.json, "dump", side_effect=OSError("disk full")), \
                self.assertRaises(OSError) as cm:
            self.mod.pull()
        self.assertEqual("disk full", str(cm.exception))
        self.assertEqual(["OLD-1"], [i["item_id"] for i in self.index_items()])
        with open(self.mod.META) as f:
            self.assertEqual({"hosts": {"old": {}}, "strays": [], "items": 1}, json.load(f))
        leftovers = [n for n in os.listdir(os.path.dirname(self.mod.INDEX)) if n.endswith(".tmp")]
        self.assertEqual([], leftovers)

    def pull_quiet(self):
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            result = self.mod.pull()
        return result, err.getvalue()

    def test_completeness_boundary_of_seen_against_declared_batches(self):
        # `len(seen) >= of`: equal (1 of 1) is complete, fewer (1 of 2) is not, more (3 distinct of 2)
        # is still complete.
        self.write("a.jsonl", [
            rec("hostA", "r1", 1.0, [item("hostA", "repo", "A-R1")], batch=0, batches=1),
            rec("hostA", "r2", 2.0, [item("hostA", "repo", "A-R2")], batch=0, batches=2),
            rec("hostB", "b1", 1.0, [item("hostB", "repo", "B-0")], batch=0, batches=2),
            rec("hostB", "b1", 1.1, [item("hostB", "repo", "B-1")], batch=1, batches=2),
            rec("hostB", "b1", 1.2, [item("hostB", "repo", "B-2")], batch=2, batches=2),
        ])
        (items, _s, newest), err = self.pull_quiet()
        self.assertEqual(["A-R1", "B-0", "B-1", "B-2"], [i["item_id"] for i in items])
        self.assertEqual({"hostA": (1.0, "r1"), "hostB": (1.2, "b1")}, newest)
        self.assertEqual("backlog: hostA: newest run r2 is incomplete (1/2 batches) — kept the complete "
                         "run r1\n", err)

    def test_newer_run_replaces_equal_and_older_do_not(self):
        # `info['ts'] > pick[host][0]`: newer later replaces, equal later and older later do not.
        self.write("a.jsonl", [
            rec("hostA", "a1", 1.0, [item("hostA", "repo", "A-FIRST")]),
            rec("hostA", "a2", 1.0, [item("hostA", "repo", "A-EQUAL")]),
            rec("hostB", "b1", 1.0, [item("hostB", "repo", "B-OLD")]),
            rec("hostB", "b2", 2.0, [item("hostB", "repo", "B-NEW")]),
            rec("hostC", "c1", 2.0, [item("hostC", "repo", "C-NEW")]),
            rec("hostC", "c2", 1.0, [item("hostC", "repo", "C-OLD")]),
        ])
        items, _s, newest = self.mod.pull()
        self.assertEqual(["A-FIRST", "B-NEW", "C-NEW"], [i["item_id"] for i in items])
        self.assertEqual({"hostA": (1.0, "a1"), "hostB": (2.0, "b2"), "hostC": (2.0, "c1")}, newest)

    def test_incomplete_run_warns_only_when_strictly_newer_than_the_complete_one(self):
        # `ts > newest[host][0]` for partial runs: equal and older are silent, newer warns.
        self.write("a.jsonl", [
            rec("hostA", "a-full", 2.0, [item("hostA", "repo", "A")], batch=0, batches=1),
            rec("hostA", "a-part", 2.0, [], batch=0, batches=2),
            rec("hostB", "b-full", 1.0, [item("hostB", "repo", "B")], batch=0, batches=1),
            rec("hostB", "b-part", 2.0, [], batch=0, batches=2),
            rec("hostC", "c-part", 1.0, [], batch=0, batches=2),
            rec("hostC", "c-full", 2.0, [item("hostC", "repo", "C")], batch=0, batches=1),
        ])
        (items, _s, newest), err = self.pull_quiet()
        self.assertEqual(["A", "B", "C"], [i["item_id"] for i in items])
        self.assertEqual("backlog: hostB: newest run b-part is incomplete (1/2 batches) — kept the "
                         "complete run b-full\n", err)

    def test_kept_run_warning_names_the_run_id_not_its_timestamp(self):
        self.write("a.jsonl", [
            rec("hostA", "keep-me", 1.5, [item("hostA", "repo", "K")], batch=0, batches=1),
            rec("hostA", "half", 3.0, [], batch=0, batches=2),
        ])
        (_items, _s, _n), err = self.pull_quiet()
        self.assertTrue(err.endswith("kept the complete run keep-me\n"), err)
        self.assertNotIn("1.5", err)

    def test_legacy_run_without_batches_and_a_batched_run_are_both_complete(self):
        # `of is None or len(seen) >= of`: the legacy run is complete by the left operand alone, the
        # batched run by the right operand alone; neither is reported as incomplete.
        self.write("a.jsonl", [
            {"received_at": 1.0, "payload": {"host": "legacy", "run_id": "L1",
                                             "items": [item("legacy", "repo", "LEG")]}},
            rec("batched", "B1", 1.0, [item("batched", "repo", "BAT")], batch=0, batches=1),
        ])
        (items, _s, newest), err = self.pull_quiet()
        self.assertEqual(["LEG", "BAT"], [i["item_id"] for i in items])
        self.assertEqual({"legacy": (1.0, "L1"), "batched": (1.0, "B1")}, newest)
        self.assertEqual("", err)

    def test_every_non_directory_data_path_exits_by_name(self):
        afile = os.path.join(self.tmp, "plain-file")
        with open(afile, "w") as f:
            f.write("x\n")
        dangling = os.path.join(self.tmp, "dangling")
        os.symlink(os.path.join(self.tmp, "no-such-target"), dangling)
        before = self.seed_index()
        cases = (
            (afile, f"backlog data dir {afile} exists but is not a directory"),
            (dangling, f"backlog data dir {dangling} is a broken symlink"),
            (os.path.join(afile, "data"), f"backlog data dir {afile}/data: {afile} is not a directory"),
        )
        for path, expected in cases:
            with self.subTest(path=path):
                self.mod.DATA = path
                msg, _o, _e = self.exit_message(self.mod.pull, unreadable_ok=True)
                self.assertIn(expected, msg)
                self.assertIn("(exit 3: ", msg)
                self.assertEqual(before, self.read_index())


class CmdSyncTests(BacklogTestCase):
    def setUp(self):
        super().setUp()
        write_jsonl(os.path.join(self.data, "a.jsonl"), [
            rec("hostA", "r1", 1.0, [item("hostA", "repo", "A-1"), item("hostA", "repo", "A-2")]),
        ])

    def set_collector_env(self, text):
        with open(self.collector_env, "w") as f:
            f.write(text)

    def push_env(self):
        self.assertEqual(1, len(self.fake.push_calls))
        return self.fake.push_calls[0][1]["env"]

    def test_local_codesift_token_is_stripped_and_no_token_fetch_runs(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "  tok-local  "
        self.capture(self.mod.cmd_sync)
        self.assertEqual("tok-local", self.push_env()["CODESIFT_COLLECTOR_TOKEN"])
        self.assertEqual(1, len(self.fake.ssh_calls))            # the pull only
        self.assertNotIn("collector.env", self.fake.ssh_calls[0][0][-1])

    def test_only_zuvo_collector_token_set_is_used(self):
        os.environ["ZUVO_COLLECTOR_TOKEN"] = "tok-zuvo-local"
        self.capture(self.mod.cmd_sync)
        self.assertEqual("tok-zuvo-local", self.push_env()["CODESIFT_COLLECTOR_TOKEN"])
        self.assertEqual(1, len(self.fake.ssh_calls))

    def test_codesift_token_wins_over_zuvo_token(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok-cs"
        os.environ["ZUVO_COLLECTOR_TOKEN"] = "tok-z"
        self.capture(self.mod.cmd_sync)
        self.assertEqual("tok-cs", self.push_env()["CODESIFT_COLLECTOR_TOKEN"])

    def test_without_local_token_fetches_codesift_token_from_collector_env(self):
        self.set_collector_env("CODESIFT_COLLECTOR_TOKEN=tok-1\n")
        self.capture(self.mod.cmd_sync)
        self.assertEqual("tok-1", self.push_env()["CODESIFT_COLLECTOR_TOKEN"])
        argv, kw = self.fake.ssh_calls[0]
        self.assertTrue(argv[-1].startswith(f". {self.collector_env} && "))
        self.assertEqual(60, kw["timeout"])

    def test_without_local_token_fetches_zuvo_token_from_collector_env(self):
        self.set_collector_env("ZUVO_COLLECTOR_TOKEN=tok-z\n")
        self.capture(self.mod.cmd_sync)
        self.assertEqual("tok-z", self.push_env()["CODESIFT_COLLECTOR_TOKEN"])

    def test_empty_fetched_token_exits_naming_both_variables_and_does_not_push(self):
        self.set_collector_env("CODESIFT_COLLECTOR_TOKEN=\n")
        msg, _o, _e = self.exit_message(self.mod.cmd_sync)
        self.assertEqual("backlog: the collector fake-collector has no CODESIFT_COLLECTOR_TOKEN "
                         "(or ZUVO_COLLECTOR_TOKEN) in its collector.env — not pushing without one; "
                         "nothing was changed", msg)
        self.assertEqual([], self.fake.push_calls)

    def test_missing_collector_env_is_that_failure_not_a_missing_token(self):
        msg, _o, _e = self.exit_message(self.mod.cmd_sync)
        self.assertIn("cannot fetch the collector token; nothing was changed", msg)
        self.assertIn("collector.env", msg)
        self.assertNotIn("has no CODESIFT_COLLECTOR_TOKEN", msg)
        self.assertEqual([], self.fake.push_calls)

    def test_push_runs_backlog_collect_with_push_flag_and_300s(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok"
        self.capture(self.mod.cmd_sync)
        argv, kw = self.fake.push_calls[0]
        self.assertEqual([sys.executable, os.path.join(self.zuvo, "backlog-collect.py"), "--push"], argv)
        self.assertEqual(300, kw["timeout"])
        self.assertTrue(kw["text"])

    def test_push_timeout_says_it_may_or_may_not_have_landed(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok"
        self.fake.push_result = subprocess.TimeoutExpired(["push"], 300)
        msg, _o, _e = self.exit_message(self.mod.cmd_sync)
        self.assertEqual("backlog: the push (backlog-collect.py --push) did not finish within 300s — it may "
                         "or may not have landed on the collector; the index was not refreshed", msg)
        self.assertEqual([], self.fake.ssh_calls)

    def test_push_oserror_says_nothing_was_pushed(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok"
        self.fake.push_result = OSError("exec format error")
        msg, _o, _e = self.exit_message(self.mod.cmd_sync)
        self.assertEqual("backlog: could not run backlog-collect.py (exec format error) — "
                         "nothing was pushed; the index was not refreshed", msg)

    def test_failed_push_exits_with_its_status_and_never_pulls(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok"
        before = self.seed_index()
        self.fake.push_result = subprocess.CompletedProcess([], 1, "", "batch 1 refused")
        msg, out, err = self.exit_message(self.mod.cmd_sync)
        self.assertEqual("backlog: the push (backlog-collect.py --push) failed (exit 1) — "
                         "the index was not refreshed", msg)
        self.assertEqual([], self.fake.ssh_calls)
        self.assertNotIn("index:", out)
        self.assertIn("batch 1 refused", err)
        self.assertEqual(before, self.read_index())

    def test_pull_failure_after_a_landed_push_says_the_push_landed(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok"
        self.mod.DATA = os.path.join(self.tmp, "nowhere", "backlog")
        msg, _o, _e = self.exit_message(self.mod.cmd_sync)
        self.assertIn("does not exist on the collector (moved?)", msg)
        self.assertTrue(msg.endswith("— cannot pull the fleet index; the local index was not changed, "
                                     "but the push above did land"))
        self.assertNotIn("nothing was changed", msg)

    def test_pull_exit_with_an_int_code_is_reported_as_a_failed_pull(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok"
        with mock.patch.object(self.mod, "pull", side_effect=SystemExit(3)):
            msg, _o, _e = self.exit_message(self.mod.cmd_sync)
        self.assertEqual("backlog: the pull failed (exit 3); the local index was not changed, "
                         "but the push above did land", msg)

    def test_unreadable_data_dir_reports_not_refreshed_and_returns(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok"
        before = self.seed_index()
        self.chmod_locked(self.data)
        ret, out, _e = self.capture(self.mod.cmd_sync)
        self.assertIsNone(ret)
        self.assertIn("index: not refreshed on this host — the collector's backlog data dir "
                      "is not readable", out)
        self.assertIn("the push above landed", out)
        self.assertEqual(before, self.read_index())

    def test_push_stdout_and_stderr_are_relayed_stripped(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok"
        self.fake.push_result = subprocess.CompletedProcess([], 0, "  pushed 1/1 \n", "\nwarn\n")
        _r, out, err = self.capture(self.mod.cmd_sync)
        self.assertEqual("pushed 1/1", out.splitlines()[0])
        self.assertEqual("warn\n", err)

    def test_token_precedence_codesift_then_zuvo(self):
        # `CODESIFT or ZUVO or ''`: with both set the first decides; with only ZUVO set the second does.
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok-cs"
        os.environ["ZUVO_COLLECTOR_TOKEN"] = "tok-z"
        self.capture(self.mod.cmd_sync)
        os.environ.pop("CODESIFT_COLLECTOR_TOKEN")
        self.capture(self.mod.cmd_sync)
        self.assertEqual(["tok-cs", "tok-z"],
                         [kw["env"]["CODESIFT_COLLECTOR_TOKEN"] for _a, kw in self.fake.push_calls])
        self.assertEqual([], [a for a, _k in self.fake.ssh_calls if "collector.env" in a[-1]])

    def test_none_from_pull_alone_means_not_refreshed(self):
        # `pulled is None`: a readable data dir is reported, an unreadable one is "not refreshed".
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok"
        _r, out, _e = self.capture(self.mod.cmd_sync)
        self.assertEqual(f"index: {self.mod.INDEX} — 2 items from 1 host(s)", out.splitlines()[0])
        self.assertNotIn("not refreshed", out)
        self.chmod_locked(self.data)
        ret, out, _e = self.capture(self.mod.cmd_sync)
        self.assertIsNone(ret)
        self.assertTrue(out.startswith("index: not refreshed on this host"), out)
        self.assertNotIn("items from", out)

    def test_success_prints_the_pull_report(self):
        os.environ["CODESIFT_COLLECTOR_TOKEN"] = "tok"
        _r, out, err = self.capture(self.mod.cmd_sync)
        self.assertEqual([f"index: {self.mod.INDEX} — 2 items from 1 host(s)",
                          "  hostA: 2 items (run r1)"], out.splitlines())
        self.assertEqual("", err)
        self.assertEqual(["A-1", "A-2"], [i["item_id"] for i in self.index_items()])


class ReportPullTests(BacklogTestCase):
    def test_summary_and_per_host_lines_sorted_by_host(self):
        items = [item("beta", "r", "1"), item("alpha", "r", "2"), item("alpha", "r", "3")]
        newest = {"beta": (2.0, "b9"), "alpha": (1.0, "a2")}
        _r, out, _e = self.capture(self.mod.report_pull, items, [], newest)
        self.assertEqual([f"index: {self.mod.INDEX} — 3 items from 2 host(s)",
                          "  alpha: 2 items (run a2)",
                          "  beta: 1 items (run b9)"], out.splitlines())

    def test_host_with_no_items_reports_zero(self):
        _r, out, _e = self.capture(self.mod.report_pull, [item("other", "r", "1")], [],
                                   {"quiet": (1.0, "q1")})
        self.assertIn("  quiet: 0 items (run q1)", out.splitlines())

    def test_strays_add_the_worktree_fork_warning(self):
        _r, out, _e = self.capture(self.mod.report_pull, [], [{"host": "h", "path": "/p"}], {})
        self.assertEqual([f"index: {self.mod.INDEX} — 0 items from 0 host(s)",
                          "  ⚠ 1 worktree-fork copies flagged (see `backlog strays`)"], out.splitlines())

    def test_no_strays_no_warning(self):
        _r, out, _e = self.capture(self.mod.report_pull, [], [], {})
        self.assertNotIn("⚠", out)


class CmdPullTests(BacklogTestCase):
    def test_prints_the_report_of_a_successful_pull(self):
        write_jsonl(os.path.join(self.data, "a.jsonl"), [
            rec("mac.local", "m1", 1.0, [item("mac.local", "zuvo", "B-1")], strays=["/wt/memory/backlog.md"]),
        ])
        _r, out, _e = self.capture(self.mod.cmd_pull)
        self.assertEqual([f"index: {self.mod.INDEX} — 1 items from 1 host(s)",
                          "  mac.local: 1 items (run m1)",
                          "  ⚠ 1 worktree-fork copies flagged (see `backlog strays`)"], out.splitlines())

    def test_pull_without_strays_prints_only_counts(self):
        write_jsonl(os.path.join(self.data, "a.jsonl"), [
            rec("vps", "v7", 1.0, [item("vps", "api", "A-1"), item("vps", "api", "A-2")]),
        ])
        ret, out, _e = self.capture(self.mod.cmd_pull)
        self.assertIsNone(ret)
        self.assertEqual([f"index: {self.mod.INDEX} — 2 items from 1 host(s)",
                          "  vps: 2 items (run v7)"], out.splitlines())

    def test_a_failed_pull_propagates_its_named_exit(self):
        msg, out, _e = self.exit_message(self.mod.cmd_pull)
        self.assertIn("does not exist on the collector (moved?)", msg)
        self.assertEqual("", out)


class AdversarialPassOneTests(BacklogTestCase):
    """Defects and weak oracles adversarial pass 1 found."""

    def write(self, name, records):
        write_jsonl(os.path.join(self.data, name), records)

    def test_completeness_needs_every_batch_number_not_just_the_count(self):
        # Regression: batches {0, 2} of 2 counted as 2 >= 2 although batch 1 never arrived.
        self.write("a.jsonl", [
            rec("h", "good", 1.0, [item("h", "r", "GOOD")]),
            rec("h", "gap", 2.0, [item("h", "r", "GAP-B0")], batch=0, batches=2),
            rec("h", "gap", 2.1, [item("h", "r", "GAP-B2")], batch=2, batches=2),
        ])
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            items, _s, newest = self.mod.pull()
        self.assertEqual(["GOOD"], [i["item_id"] for i in items])
        self.assertEqual({"h": (1.0, "good")}, newest)
        self.assertEqual("backlog: h: newest run gap is incomplete (1/2 batches) — kept the complete "
                         "run good\n", err.getvalue())

    def test_records_that_are_not_backlog_payloads_are_counted_on_stderr(self):
        # Regression: unparseable or host-less records were dropped with no word.
        self.write("a.jsonl", ["{not json", '"a bare string"', json.dumps({"payload": {"run_id": "x"}}),
                               "", rec("h", "r1", 1.0, [item("h", "r", "KEPT")])])
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            items, _s, _n = self.mod.pull()
        self.assertEqual(["KEPT"], [i["item_id"] for i in items])
        self.assertEqual("backlog: skipped 3 record(s) on the collector that are not backlog payloads "
                         "(unparseable JSON or no host)\n", err.getvalue())

    def test_failed_index_swap_keeps_the_previous_pair_and_removes_temp_files(self):
        self.write("a.jsonl", [rec("hostA", "r1", 1.0, [item("hostA", "repo", "NEW-1")])])
        self.seed_index('{"item_id": "OLD-1"}\n')
        with open(self.mod.META, "w") as f:
            json.dump({"hosts": {"old": {}}, "strays": [], "items": 1}, f)
        with mock.patch.object(self.mod.os, "replace", side_effect=OSError("cross-device")), \
                self.assertRaises(OSError):
            self.mod.pull()
        self.assertEqual(["OLD-1"], [i["item_id"] for i in self.index_items()])
        self.assertEqual({"hosts": {"old": {}}, "strays": [], "items": 1}, self.read_meta())
        self.assertEqual([], [n for n in os.listdir(self.zuvo) if n.endswith(".tmp")])


class AdversarialPassTwoTests(BacklogTestCase):
    """Fleet-supplied record shapes, the swap lock and the rollback's own failure (adversarial pass 2)."""

    def write(self, name, records):
        write_jsonl(os.path.join(self.data, name), records)

    def test_null_or_text_received_at_counts_as_zero_instead_of_crashing(self):
        # Regression: max(0, None) / max(0, "x") raised TypeError in the middle of the pull.
        def raw(ts, host, run, item_id):
            return {"received_at": ts, "payload": {"host": host, "run_id": run,
                                                   "items": [item(host, "r", item_id)]}}
        self.write("a.jsonl", [raw(None, "h", "r-null", "N"), raw("yesterday", "g", "r-str", "S"),
                               raw(1.0, "h", "r-num", "NUM")])
        items, _s, newest = self.mod.pull()
        self.assertEqual({"h": (1.0, "r-num"), "g": (0, "r-str")}, newest)
        self.assertEqual(["NUM", "S"], sorted(i["item_id"] for i in items))

    def test_a_batch_delivered_twice_is_counted_once(self):
        # Regression: a retried POST of batch 0 doubled its items in the index.
        self.write("a.jsonl", [
            rec("h", "r1", 1.0, [item("h", "r", "B0-ITEM")], batch=0, batches=2),
            rec("h", "r1", 1.5, [item("h", "r", "B0-ITEM")], batch=0, batches=2),
            rec("h", "r1", 2.0, [item("h", "r", "B1-ITEM")], batch=1, batches=2),
        ])
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            items, _s, newest = self.mod.pull()
        self.assertEqual(["B0-ITEM", "B1-ITEM"], [i["item_id"] for i in items])
        self.assertEqual({"h": (2.0, "r1")}, newest)
        self.assertEqual("", err.getvalue())

    def test_items_that_are_not_objects_are_dropped(self):
        self.write("a.jsonl", [{"received_at": 1.0, "payload": {
            "host": "h", "run_id": "r1", "items": ["a string", 7, None, item("h", "r", "OBJ")]}}])
        items, _s, _n = self.mod.pull()
        self.assertEqual(["OBJ"], [i["item_id"] for i in items])

    def test_a_failed_rollback_names_both_failures(self):
        self.write("a.jsonl", [rec("hostA", "r1", 1.0, [item("hostA", "repo", "NEW-1")])])
        self.seed_index('{"item_id": "OLD-1"}\n')
        real_replace = os.replace

        def replace(src, dst):
            if dst == self.mod.META:
                raise OSError("meta swap failed")
            if src.endswith(".prev"):
                raise OSError("rollback failed")
            return real_replace(src, dst)
        with mock.patch.object(self.mod.os, "replace", side_effect=replace), \
                self.assertRaises(OSError) as cm:
            self.mod.pull()
        self.assertEqual(f"meta swap failed; rolling the index back also failed (rollback failed) — "
                         f"{self.mod.INDEX} is newer than {self.mod.META}", str(cm.exception))

    def test_the_write_and_swap_run_under_an_exclusive_lock(self):
        self.write("a.jsonl", [rec("hostA", "r1", 1.0, [item("hostA", "repo", "NEW-1")])])
        calls = []
        fake_fcntl = mock.Mock(LOCK_EX=2)
        fake_fcntl.flock.side_effect = lambda fh, op: calls.append(
            (fh.name, op, os.path.exists(self.mod.INDEX)))
        with mock.patch.dict(sys.modules, {"fcntl": fake_fcntl}):
            self.mod.pull()
        self.assertEqual([(self.mod.INDEX + ".lock", 2, False)], calls)
        self.assertEqual(["NEW-1"], [i["item_id"] for i in self.index_items()])

    def test_without_fcntl_the_pull_still_writes(self):
        self.write("a.jsonl", [rec("hostA", "r1", 1.0, [item("hostA", "repo", "NEW-1")])])
        with mock.patch.dict(sys.modules, {"fcntl": None}):
            self.mod.pull()
        self.assertEqual(["NEW-1"], [i["item_id"] for i in self.index_items()])

    def test_text_mode_output_that_is_not_utf8_still_reaches_the_message(self):
        # Regression: text mode decoded strictly, so a non-UTF-8 byte raised out of subprocess.
        msg, _o, _e = self.exit_message(self.mod.collector_ssh, "printf 'bad \\377 byte\\n' >&2; exit 3",
                                        5, "probe")
        self.assertIn("(exit 3: bad \ufffd byte)", msg)

    def test_conf_inline_comment_and_unquoted_export_are_read(self):
        zhome = os.path.join(self.tmp, "zhome")
        os.makedirs(zhome)
        os.environ.pop("ZUVO_COLLECTOR_SSH", None)
        os.environ["ZUVO_HOME"] = zhome
        conf = os.path.join(zhome, "collector.conf")
        for text, want in (("ZUVO_COLLECTOR_SSH=box-1  # the collector\n", "box-1"),
                           ("export ZUVO_COLLECTOR_SSH=plain-host\n", "plain-host")):
            with self.subTest(text=text):
                with open(conf, "w", encoding="utf-8") as f:
                    f.write(text)
                self.assertEqual(want, self.mod._collector_host())


class ReauditEdgeTests(BacklogTestCase):
    """Edges the third blind re-audit named (codex-5.3)."""

    def write(self, name, records):
        write_jsonl(os.path.join(self.data, name), records)

    def test_boolean_received_at_counts_as_zero_not_as_one(self):
        # bool is an int subclass: True would otherwise read as timestamp 1 and beat a real 0.5.
        def raw(ts, run, item_id):
            return {"received_at": ts,
                    "payload": {"host": "h", "run_id": run, "items": [item("h", "r", item_id)]}}
        self.write("a.jsonl", [raw(True, "r-bool", "BOOL"), raw(0.5, "r-real", "REAL")])
        items, _s, newest = self.mod.pull()
        self.assertEqual({"h": (0.5, "r-real")}, newest)
        self.assertEqual(["REAL"], [i["item_id"] for i in items])

    def test_the_last_batch_carrying_strays_decides_them(self):
        self.write("a.jsonl", [
            rec("h", "r1", 1.0, [item("h", "r", "B0")], strays=["/first"], batch=0, batches=2),
            rec("h", "r1", 1.1, [item("h", "r", "B1")], strays=["/second"], batch=1, batches=2),
        ])
        _i, strays, _n = self.mod.pull()
        self.assertEqual([{"host": "h", "path": "/second"}], strays)

    def test_of_several_incomplete_runs_the_newest_is_used(self):
        self.write("a.jsonl", [
            rec("h", "older-partial", 1.0, [item("h", "r", "OLD")], batch=0, batches=2),
            rec("h", "newer-partial", 2.0, [item("h", "r", "NEW")], batch=0, batches=3),
        ])
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            items, _s, newest = self.mod.pull()
        self.assertEqual({"h": (2.0, "newer-partial")}, newest)
        self.assertEqual(["NEW"], [i["item_id"] for i in items])
        self.assertEqual("backlog: h: run newer-partial is incomplete (1/3 batches) and no complete run "
                         "exists — using it; that host's items are short\n", err.getvalue())

    def test_a_second_pull_waits_for_the_lock_held_by_another_process(self):
        if "fcntl" not in sys.modules:
            try:
                import fcntl  # noqa: F401
            except ImportError:
                self.skipTest("no fcntl on this platform: the swap is not locked")
        self.write("a.jsonl", [rec("hostA", "r1", 1.0, [item("hostA", "repo", "NEW-1")])])
        os.makedirs(self.zuvo, exist_ok=True)
        # The holder keeps the lock until told to let go — no sleep, no elapsed-time threshold. While it
        # holds it, pull must still be blocked; a pull that ignored the lock would already be done.
        holder = subprocess.Popen(
            [sys.executable, "-c",
             "import fcntl, sys\n"
             "f = open(sys.argv[1], 'a'); fcntl.flock(f, fcntl.LOCK_EX)\n"
             "print('locked', flush=True); sys.stdin.readline()\n",
             self.mod.INDEX + ".lock"], stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True)
        self.addCleanup(holder.wait)
        # Cleanups run last-in first-out: the holder is released (stdin closed -> readline returns)
        # BEFORE it is waited for, so a failing assertion below cannot leave the wait hanging forever.
        self.addCleanup(lambda: holder.stdin.closed or holder.stdin.close())
        self.assertEqual("locked\n", holder.stdout.readline())
        holder.stdout.close()
        errors = []

        def run_pull():
            try:
                self.mod.pull()
            except BaseException as e:   # surfaced below, not swallowed
                errors.append(e)
        worker = threading.Thread(target=run_pull, daemon=True)   # daemon: never outlives a failed test
        worker.start()
        worker.join(timeout=1.0)
        self.assertTrue(worker.is_alive(), "pull finished while another process held the index lock")
        self.assertFalse(os.path.exists(self.mod.INDEX))
        holder.stdin.write("release\n")
        holder.stdin.close()
        worker.join(timeout=30)
        self.assertFalse(worker.is_alive())
        self.assertEqual([], errors)
        self.assertEqual(["NEW-1"], [i["item_id"] for i in self.index_items()])
        self.assertEqual(1, self.read_meta()["items"])
        self.assertEqual([], [n for n in os.listdir(self.zuvo) if n.endswith((".tmp", ".prev"))])


class FinalReviewTests(BacklogTestCase):
    """The final full-content cross-model review: fleet field types and the lock's own failure."""

    def write(self, name, records):
        write_jsonl(os.path.join(self.data, name), records)

    def payload(self, run, ts, item_id, **extra):
        p = {"host": "h", "run_id": run, "items": [item("h", "r", item_id)]}
        p.update(extra)
        return {"received_at": ts, "payload": p}

    def test_a_boolean_batch_is_not_batch_one(self):
        # bool is an int subclass: True used to count as batch 1, completing a 2-batch run.
        self.write("a.jsonl", [rec("h", "good", 1.0, [item("h", "r", "GOOD")]),
                               self.payload("bool", 2.0, "B0", batch=0, batches=2),
                               self.payload("bool", 2.1, "BT", batch=True, batches=2)])
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            _i, _s, newest = self.mod.pull()
        self.assertEqual({"h": (1.0, "good")}, newest)
        self.assertIn("newest run bool is incomplete (1/2 batches)", err.getvalue())

    def test_a_huge_declared_batch_count_is_counted_not_materialised(self):
        # range(10**12) used to be built as a set; now the run is simply incomplete, instantly.
        self.write("a.jsonl", [rec("h", "good", 1.0, [item("h", "r", "GOOD")]),
                               self.payload("huge", 2.0, "H0", batch=0, batches=10 ** 12)])
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            _i, _s, newest = self.mod.pull()
        self.assertEqual({"h": (1.0, "good")}, newest)
        self.assertIn(f"newest run huge is incomplete (1/{10 ** 12} batches)", err.getvalue())

    def test_zero_or_negative_batches_declare_nothing(self):
        for declared in (0, -2, True, "2"):
            with self.subTest(batches=declared):
                self.write("a.jsonl", [rec("h", "old", 1.0, [item("h", "r", "OLD")]),
                                       self.payload("new", 2.0, "NEW", batch=0, batches=declared)])
                items, _s, newest = self.mod.pull()
                self.assertEqual({"h": (2.0, "new")}, newest)
                self.assertEqual(["NEW"], [i["item_id"] for i in items])

    def test_a_line_separator_inside_a_json_string_does_not_split_the_record(self):
        # Written raw (ensure_ascii off): str.splitlines() broke the record at U+2028.
        rec_line = json.dumps(rec("h", "r1", 1.0, [item("h", "r", "LS", text="a\u2028b")]),
                              ensure_ascii=False)
        self.write("a.jsonl", [rec_line])
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            items, _s, _n = self.mod.pull()
        self.assertEqual(["a\u2028b"], [i["text"] for i in items])
        self.assertEqual("", err.getvalue())

    def test_strays_keep_only_path_strings(self):
        self.write("a.jsonl", [self.payload("r1", 1.0, "X",
                                            stray_worktree_copies=["/ok", 7, None, {"p": 1}])])
        _i, strays, _n = self.mod.pull()
        self.assertEqual([{"host": "h", "path": "/ok"}], strays)
        self.write("a.jsonl", [self.payload("r2", 2.0, "Y", stray_worktree_copies="/not/a/list")])
        _i, strays, _n = self.mod.pull()
        self.assertEqual([], strays)

    def test_a_flock_that_raises_still_closes_the_lock_and_writes_nothing(self):
        self.write("a.jsonl", [rec("hostA", "r1", 1.0, [item("hostA", "repo", "NEW-1")])])
        before = self.seed_index()
        opened = []
        real_open = open

        def tracking_open(path, *a, **kw):
            fh = real_open(path, *a, **kw)
            if str(path).endswith(".lock"):
                opened.append(fh)
            return fh
        fake_fcntl = mock.Mock(LOCK_EX=2)
        fake_fcntl.flock.side_effect = OSError("no locks available")
        with mock.patch.dict(sys.modules, {"fcntl": fake_fcntl}), \
                mock.patch("builtins.open", side_effect=tracking_open), self.assertRaises(OSError):
            self.mod.pull()
        self.assertEqual(1, len(opened))
        self.assertTrue(opened[0].closed)
        self.assertEqual(before, self.read_index())


class FinalReauditTests(BacklogTestCase):
    """Edges the final blind re-audit named (codex-5.3, qwen)."""

    def write(self, name, records):
        write_jsonl(os.path.join(self.data, name), records)

    def test_a_resent_batch_with_a_later_timestamp_does_not_move_its_run(self):
        # The duplicate is skipped before it can raise the run's time: r1 stays at 1.1, so r2 (1.5) wins.
        self.write("a.jsonl", [
            rec("h", "r1", 1.0, [item("h", "r", "R1")], batch=0, batches=1),
            rec("h", "r2", 1.5, [item("h", "r", "R2")], batch=0, batches=1),
            rec("h", "r1", 9.0, [item("h", "r", "R1")], batch=0, batches=1),
        ])
        items, _s, newest = self.mod.pull()
        self.assertEqual({"h": (1.5, "r2")}, newest)
        self.assertEqual(["R2"], [i["item_id"] for i in items])

    def test_a_failed_swap_releases_the_lock_for_the_next_pull(self):
        self.write("a.jsonl", [rec("hostA", "r1", 1.0, [item("hostA", "repo", "NEW-1")])])
        real_replace = os.replace

        def fail_meta(src, dst):
            if dst == self.mod.META:
                raise OSError("meta swap failed")
            return real_replace(src, dst)
        with mock.patch.object(self.mod.os, "replace", side_effect=fail_meta), self.assertRaises(OSError):
            self.mod.pull()
        probe = REAL_RUN(   # the harness patches subprocess.run module-wide
            [sys.executable, "-c",
             "import fcntl, sys\nf = open(sys.argv[1], 'a')\n"
             "fcntl.flock(f, fcntl.LOCK_EX | fcntl.LOCK_NB)\nprint('free')\n",
             self.mod.INDEX + ".lock"], capture_output=True, text=True, timeout=30)
        self.assertEqual("free\n", probe.stdout, probe.stderr)
        self.mod.pull()
        self.assertEqual(["NEW-1"], [i["item_id"] for i in self.index_items()])
        self.assertEqual(1, self.read_meta()["items"])

    def test_the_first_valid_conf_line_wins(self):
        zhome = os.path.join(self.tmp, "zhome")
        os.makedirs(zhome)
        os.environ.pop("ZUVO_COLLECTOR_SSH", None)
        os.environ["ZUVO_HOME"] = zhome
        with open(os.path.join(zhome, "collector.conf"), "w", encoding="utf-8") as f:
            f.write("ZUVO_COLLECTOR_SSH=first\nZUVO_COLLECTOR_SSH=second\n")
        self.assertEqual("first", self.mod._collector_host())

    def test_a_symlinked_data_dir_is_read_like_a_real_one(self):
        real = os.path.join(self.tmp, "real-data")
        write_jsonl(os.path.join(real, "a.jsonl"),
                    [rec("hostA", "r1", 1.0, [item("hostA", "repo", "VIA-LINK")])])
        os.makedirs(os.path.dirname(self.data), exist_ok=True)
        os.symlink(real, self.data)
        items, _s, newest = self.mod.pull()
        self.assertEqual(["VIA-LINK"], [i["item_id"] for i in items])
        self.assertEqual({"hostA": (1.0, "r1")}, newest)

    def test_a_readable_but_unsearchable_data_dir_is_unreadable(self):
        os.makedirs(self.data)
        if os.geteuid() == 0:
            self.skipTest("root ignores directory permissions")
        os.chmod(self.data, 0o444)
        self.addCleanup(os.chmod, self.data, 0o700)
        before = self.seed_index()
        self.assertIsNone(self.mod.pull(unreadable_ok=True))
        msg, _o, _e = self.exit_message(self.mod.pull)
        self.assertIn("(exit 4: backlog data dir", msg)
        self.assertIn("is not readable by this user)", msg)
        self.assertEqual(before, self.read_index())


class IndexSwapTests(BacklogTestCase):
    """INDEX and META are one pair: a swap that fails half-way rolls back (blind re-audit B41)."""

    def setUp(self):
        super().setUp()
        write_jsonl(os.path.join(self.data, "a.jsonl"),
                    [rec("hostA", "r1", 1.0, [item("hostA", "repo", "NEW-1")])])
        self.real_replace = os.replace

    def fail_on_meta(self, src, dst):
        if dst == self.mod.META:
            raise OSError("meta swap failed")
        return self.real_replace(src, dst)

    def leftovers(self):
        return sorted(n for n in os.listdir(self.zuvo) if n.endswith((".tmp", ".prev")))

    def test_failed_meta_swap_rolls_the_index_back_to_the_previous_pair(self):
        self.seed_index('{"item_id": "OLD-1"}\n')
        with open(self.mod.META, "w") as f:
            json.dump({"hosts": {"old": {}}, "strays": [], "items": 1}, f)
        with mock.patch.object(self.mod.os, "replace", side_effect=self.fail_on_meta), \
                self.assertRaises(OSError) as cm:
            self.mod.pull()
        self.assertEqual("meta swap failed", str(cm.exception))
        self.assertEqual(["OLD-1"], [i["item_id"] for i in self.index_items()])
        self.assertEqual({"hosts": {"old": {}}, "strays": [], "items": 1}, self.read_meta())
        self.assertEqual([], self.leftovers())

    def test_failed_meta_swap_with_no_previous_index_leaves_none(self):
        with mock.patch.object(self.mod.os, "replace", side_effect=self.fail_on_meta), \
                self.assertRaises(OSError):
            self.mod.pull()
        self.assertFalse(os.path.exists(self.mod.INDEX))
        self.assertFalse(os.path.exists(self.mod.META))
        self.assertEqual([], self.leftovers())

    def test_without_hard_links_the_previous_index_is_copied_and_the_swap_completes(self):
        self.seed_index('{"item_id": "OLD-1"}\n')
        with mock.patch.object(self.mod.os, "link", side_effect=OSError("no hard links here")):
            self.mod.pull()
        self.assertEqual(["NEW-1"], [i["item_id"] for i in self.index_items()])
        self.assertEqual(1, self.read_meta()["items"])
        self.assertEqual([], self.leftovers())

    def test_stale_prev_file_from_an_interrupted_run_is_replaced(self):
        self.seed_index('{"item_id": "OLD-1"}\n')
        with open(self.mod.INDEX + ".prev", "w") as f:
            f.write("stale\n")
        self.mod.pull()
        self.assertEqual(["NEW-1"], [i["item_id"] for i in self.index_items()])
        self.assertEqual([], self.leftovers())


class CollectorPathDefaultsTests(BacklogTestCase):
    """The production paths, unpatched: one root for the data dir and collector.env (re-audit B10)."""

    def test_both_collector_paths_derive_from_the_one_root(self):
        mod = load_backlog(self.zuvo)
        self.assertEqual("/opt/telemetry-collector", mod.COLLECTOR_ROOT)
        self.assertEqual("/opt/telemetry-collector/data/backlog", mod.DATA)
        self.assertEqual("/opt/telemetry-collector/collector.env", mod.COLLECTOR_ENV)

    def test_remote_commands_target_the_production_paths(self):
        mod = load_backlog(self.zuvo)
        fake = type(self.fake)()   # canned failure: no command runs, only its text is recorded
        fake.ssh_result = subprocess.CompletedProcess(["ssh"], 7, b"", b"boom")   # pull reads bytes
        with mock.patch.object(mod.subprocess, "run", fake), self.assertRaises(SystemExit):
            mod.pull()
        fake.ssh_result = subprocess.CompletedProcess(["ssh"], 7, "", "boom")     # the token fetch, text
        with mock.patch.object(mod.subprocess, "run", fake), self.assertRaises(SystemExit):
            mod.cmd_sync()
        pull_cmd, token_cmd = fake.ssh_calls[0][0][-1], fake.ssh_calls[1][0][-1]
        self.assertTrue(pull_cmd.startswith("d=/opt/telemetry-collector/data/backlog; "), pull_cmd)
        self.assertTrue(token_cmd.startswith(". /opt/telemetry-collector/collector.env && "), token_cmd)


class BlindAuditFollowUpTests(BacklogTestCase):
    """Rows the blind coverage audit found only partly covered (pass 1: FIX)."""

    def write(self, name, records):
        write_jsonl(os.path.join(self.data, name), records)

    def test_zuvo_dir_defaults_to_home_dot_zuvo_when_unset(self):
        home = os.path.join(self.tmp, "home")
        with mock.patch.dict(os.environ, {"HOME": home}):
            mod = load_backlog(None)
        self.assertEqual(os.path.join(home, ".zuvo"), mod.ZUVO)
        self.assertEqual(os.path.join(home, ".zuvo", "backlog-index.jsonl"), mod.INDEX)
        self.assertEqual(os.path.join(home, ".zuvo", "backlog-index.meta.json"), mod.META)

    def test_conf_with_non_utf8_bytes_is_still_read(self):
        zhome = os.path.join(self.tmp, "zhome")
        os.makedirs(zhome)
        with open(os.path.join(zhome, "collector.conf"), "wb") as f:
            f.write(b"# \xff\xfe operator notes\nZUVO_COLLECTOR_SSH=h3\n")
        os.environ.pop("ZUVO_COLLECTOR_SSH", None)
        os.environ["ZUVO_HOME"] = zhome
        self.assertEqual("h3", self.mod._collector_host())

    def test_cap_refusal_through_pull_names_the_cap_and_keeps_the_index(self):
        self.write("a.jsonl", [rec("hostA", "r1", 1.0, [item("hostA", "repo", "A-1", text="x" * 200)])])
        before = self.seed_index()
        self.mod.PULL_MAX_BYTES = 10
        msg, _o, _e = self.exit_message(self.mod.pull)
        self.assertIn("could not be decompressed (decompressed payload exceeds 10 bytes)", msg)
        self.assertTrue(msg.endswith("nothing was changed"))
        self.assertEqual(before, self.read_index())

    def test_records_without_run_id_share_one_run_per_host(self):
        self.write("a.jsonl", [
            {"received_at": 1.0, "payload": {"host": "h", "items": [item("h", "r", "NR-1")]}},
            {"received_at": 2.0, "payload": {"host": "h", "items": [item("h", "r", "NR-2")]}},
        ])
        items, _s, newest = self.mod.pull()
        self.assertEqual(["NR-1", "NR-2"], [i["item_id"] for i in items])
        self.assertEqual({"h": (2.0, "")}, newest)

    def test_missing_received_at_counts_as_zero(self):
        self.write("a.jsonl", [
            {"payload": {"host": "h", "run_id": "no-ts", "items": [item("h", "r", "OLD")]}},
            {"received_at": 0.5, "payload": {"host": "h", "run_id": "ts", "items": [item("h", "r", "NEW")]}},
            {"payload": {"host": "solo", "run_id": "s1", "items": [item("solo", "r", "SOLO")]}},
        ])
        items, _s, newest = self.mod.pull()
        self.assertEqual(["NEW", "SOLO"], [i["item_id"] for i in items])
        self.assertEqual({"h": (0.5, "ts"), "solo": (0, "s1")}, newest)

    def test_run_time_is_its_newest_record_even_when_an_older_one_arrives_last(self):
        # r1's records arrive 2.0 then 1.0; its time stays 2.0, so it beats r2 at 1.5.
        self.write("a.jsonl", [
            rec("h", "r1", 2.0, [item("h", "r", "R1-B0")], batch=0, batches=2),
            rec("h", "r2", 1.5, [item("h", "r", "R2")]),
            rec("h", "r1", 1.0, [item("h", "r", "R1-B1")], batch=1, batches=2),
        ])
        items, _s, newest = self.mod.pull()
        self.assertEqual(["R1-B0", "R1-B1"], [i["item_id"] for i in items])
        self.assertEqual({"h": (2.0, "r1")}, newest)

    def test_non_integer_batches_is_ignored_and_the_run_counts_whole(self):
        # Only an int declares a batch count; anything else is treated like a pre-batching payload.
        self.write("a.jsonl", [
            rec("h", "old", 1.0, [item("h", "r", "OLD")]),
            {"received_at": 2.0, "payload": {"host": "h", "run_id": "new", "batch": 0, "batches": "2",
                                             "items": [item("h", "r", "NEW")]}},
        ])
        err = io.StringIO()
        with contextlib.redirect_stderr(err):
            items, _s, newest = self.mod.pull()
        self.assertEqual(["NEW"], [i["item_id"] for i in items])
        self.assertEqual({"h": (2.0, "new")}, newest)
        self.assertEqual("", err.getvalue())

    def test_dangling_jsonl_symlink_fails_the_pull_by_name(self):
        os.makedirs(self.data)
        os.symlink(os.path.join(self.tmp, "gone.jsonl"), os.path.join(self.data, "a.jsonl"))
        before = self.seed_index()
        msg, _o, _e = self.exit_message(self.mod.pull)
        self.assertIn("backlog: ssh to the collector fake-collector, or the command it ran there, "
                      "failed (exit", msg)
        self.assertIn("a.jsonl", msg)   # gzip's own error names the file it could not read
        self.assertIn("cannot pull the fleet index; nothing was changed", msg)
        self.assertEqual(before, self.read_index())


if __name__ == "__main__":
    unittest.main()
