# Generated by zuvo:write-tests
"""scripts/zuvo-home/backlog — the read views over the merged index: load, cmd_ls, cmd_open,
cmd_crit, cmd_grep, cmd_strays, and the `__main__` dispatch (run as a real process).
"""

import os
import sys
import unittest
from unittest import mock

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from backlog_testlib import BACKLOG, REAL_RUN, BacklogTestCase, item, run_cli  # noqa: E402


def ls_rows(out):
    """{key: (open, done, oldest)} from the table body of cmd_ls."""
    lines = out.splitlines()
    body = lines[2:lines.index("-" * 74, 2)]
    rows = {}
    for line in body:
        key, open_, done, oldest = line.split()
        rows[key] = (int(open_), int(done), oldest)
    return rows, [line.split()[0] for line in body]


class LoadTests(BacklogTestCase):
    def test_missing_index_exits_telling_how_to_build_it(self):
        # Two elements, so a neighbouring index (argv[1] / argv[-1]) would name "ls", not the script.
        with mock.patch.object(sys, "argv", ["/opt/bin/backlog", "ls"]):
            msg, _o, _e = self.exit_message(self.mod.load)
        self.assertEqual("no index yet — run: /opt/bin/backlog sync", msg)

    def test_blank_lines_are_skipped_and_missing_meta_is_empty(self):
        os.makedirs(self.zuvo)
        with open(self.mod.INDEX, "w") as f:
            f.write('{"item_id": "B-1"}\n\n   \n{"item_id": "B-2"}\n')
        items, meta = self.mod.load()
        self.assertEqual([{"item_id": "B-1"}, {"item_id": "B-2"}], items)
        self.assertEqual({}, meta)

    def test_meta_is_returned_when_present(self):
        self.write_index([item("h", "r", "B-1")], meta={"hosts": {"h": {"run_id": "r1"}}, "strays": []})
        items, meta = self.mod.load()
        self.assertEqual(["B-1"], [i["item_id"] for i in items])
        self.assertEqual({"hosts": {"h": {"run_id": "r1"}}, "strays": []}, meta)


class CmdLsTests(BacklogTestCase):
    def test_counts_per_short_host_and_repo_sorted_by_open_desc_with_total(self):
        self.write_index([
            item("mac.local", "zuvo", "Z-1", "open", added="2026-01-05"),
            item("mac.local", "zuvo", "Z-2", "open", added="2026-01-02"),
            item("mac.local", "zuvo", "Z-3", "open", added="2026-01-09"),
            item("mac.local", "zuvo", "Z-4", "done", added=""),
            item("vps", "api", "A-1", "done", added="2026-03-01"),
            item("vps", "api", "A-2", "open", added=""),
            item("vps", "api", "A-3", "done", added="2026-02-01"),
            item("bot.example.com", "site", "S-1", "open", added="2026-04-04"),
            item("bot.example.com", "site", "S-2", "open"),
        ], meta={"hosts": {"mac.local": {}, "vps": {}, "bot.example.com": {}, "gone": {}}})
        _r, out, _e = self.capture(self.mod.cmd_ls)
        rows, order = ls_rows(out)
        self.assertEqual({"mac:zuvo": (3, 1, "2026-01-02"),
                          "bot:site": (2, 0, "2026-04-04"),
                          "vps:api": (1, 2, "2026-02-01")}, rows)
        self.assertEqual(["mac:zuvo", "bot:site", "vps:api"], order)
        self.assertEqual("TOTAL open=6 done=3 across 3 repos / 4 hosts", out.splitlines()[-1])
        self.assertEqual(f"{'repo':<46} {'open':>6} {'done':>6}  oldest", out.splitlines()[0])

    def test_oldest_ignores_empty_dates_seen_first(self):
        self.write_index([item("h", "r", "1", added=""), item("h", "r", "2", added="2026-05-05"),
                          item("h", "r", "3", added="")])
        _r, out, _e = self.capture(self.mod.cmd_ls)
        self.assertEqual({"h:r": (3, 0, "2026-05-05")}, ls_rows(out)[0])

    def test_oldest_with_no_dates_prints_a_dash(self):
        self.write_index([item("h", "r", "1", added=""), {"host": "h", "repo": "r", "status": "done"}])
        _r, out, _e = self.capture(self.mod.cmd_ls)
        self.assertEqual({"h:r": (1, 1, "-")}, ls_rows(out)[0])

    def test_equal_oldest_dates_keep_the_value(self):
        self.write_index([item("h", "r", "1", added="2026-01-01"), item("h", "r", "2", added="2026-01-01")])
        _r, out, _e = self.capture(self.mod.cmd_ls)
        self.assertEqual({"h:r": (2, 0, "2026-01-01")}, ls_rows(out)[0])

    def test_missing_status_counts_as_open_and_other_statuses_are_not_open_or_done(self):
        self.write_index([{"host": "h", "repo": "r"}, item("h", "r", "2", status="wontfix")], meta={})
        _r, out, _e = self.capture(self.mod.cmd_ls)
        self.assertEqual({"h:r": (1, 0, "-")}, ls_rows(out)[0])
        self.assertEqual("TOTAL open=1 done=0 across 1 repos / 0 hosts", out.splitlines()[-1])

    def test_missing_host_and_repo_show_question_marks(self):
        self.write_index([{"status": "open"}])
        _r, out, _e = self.capture(self.mod.cmd_ls)
        self.assertEqual({"?:?": (1, 0, "-")}, ls_rows(out)[0])

    def test_long_keys_are_cut_to_45_characters(self):
        repo = "r" * 60
        self.write_index([item("h", repo, "1")])
        _r, out, _e = self.capture(self.mod.cmd_ls)
        self.assertEqual([("h:" + repo)[:45]], ls_rows(out)[1])

    def test_oldest_boundary_earlier_replaces_equal_and_later_keep(self):
        # `a < oldest`: an earlier date replaces, an equal one and a later one do not.
        self.write_index([item("h", "r", str(n), added=a) for n, a in
                          enumerate(("2026-01-05", "2026-01-02", "2026-01-02", "2026-01-09"))])
        _r, out, _e = self.capture(self.mod.cmd_ls)
        self.assertEqual({"h:r": (4, 0, "2026-01-02")}, ls_rows(out)[0])

    def test_ls_host_is_cut_at_the_first_dot(self):
        self.write_index([item("alpha.beta.gamma", "r", "1")])
        _r, out, _e = self.capture(self.mod.cmd_ls)
        self.assertEqual(["alpha:r"], ls_rows(out)[1])

    def test_empty_added_after_a_date_does_not_clear_oldest(self):
        # `a and (...)`: an empty date is rejected by the left operand alone.
        self.write_index([item("h", "r", "1", added="2026-07-07"), item("h", "r", "2", added=""),
                          {"host": "h", "repo": "r", "status": "open", "added": None}])
        _r, out, _e = self.capture(self.mod.cmd_ls)
        self.assertEqual({"h:r": (3, 0, "2026-07-07")}, ls_rows(out)[0])

    def test_first_date_sets_oldest_and_a_later_earlier_date_replaces_it(self):
        # `not oldest or a < oldest`: the first date is taken by the left operand alone, the
        # replacement by the right operand alone.
        self.write_index([item("h", "r", "1", added="2026-09-09"), item("h", "r", "2", added="2026-01-01")])
        _r, out, _e = self.capture(self.mod.cmd_ls)
        self.assertEqual({"h:r": (2, 0, "2026-01-01")}, ls_rows(out)[0])

    def test_dated_repo_shows_its_date_and_undated_shows_a_dash(self):
        self.write_index([item("h", "dated", "1", added="2026-02-02"), item("h", "undated", "2", added="")])
        _r, out, _e = self.capture(self.mod.cmd_ls)
        self.assertEqual({"h:dated": (1, 0, "2026-02-02"), "h:undated": (1, 0, "-")}, ls_rows(out)[0])


class CmdOpenTests(BacklogTestCase):
    def setUp(self):
        super().setUp()
        self.write_index([
            item("mac.local", "zuvo-plugin", "B-1", "open", "high", "2026-01-01", "first"),
            item("mac.local", "zuvo-plugin", "B-2", "open", None, "2026-03-01", "newest"),
            item("vps", "other", "O-1", "open", "low", "", "undated"),
            item("vps", "zuvo-landing", "L-1", "done", "critical", "2026-04-01", "closed"),
            item("vps", "zuvo-landing", "L-2", "open", "medium", "2026-02-01", "landing"),
        ])

    def test_only_open_items_newest_first_undated_last(self):
        ret, out, _e = self.capture(self.mod.cmd_open, [])
        self.assertIsNone(ret)
        self.assertEqual([
            "[2026-03-01] mac:zuvo-plugin B-2        - | newest",
            "[2026-02-01] vps:zuvo-landing L-2   medium | landing",
            "[2026-01-01] mac:zuvo-plugin B-1     high | first",
            "[----------] vps:other O-1      low | undated",
            "",
            "(4 open, showing 4)",
        ], out.splitlines())

    def test_repo_filter_is_a_substring_match_and_is_named_in_the_footer(self):
        _r, out, _e = self.capture(self.mod.cmd_open, ["--repo", "zuvo"])
        self.assertEqual(["B-2", "L-2", "B-1"], [line.split()[2] for line in out.splitlines()[:3]])
        self.assertEqual("(3 open in zuvo, showing 3)", out.splitlines()[-1])

    def test_repo_filter_matching_nothing_reports_zero(self):
        _r, out, _e = self.capture(self.mod.cmd_open, ["--repo", "nope"])
        self.assertEqual(["", "(0 open in nope, showing 0)"], out.splitlines())

    def test_repo_without_a_value_returns_2_with_a_message_and_no_listing(self):
        ret, out, err = self.capture(self.mod.cmd_open, ["--repo"])
        self.assertEqual(2, ret)
        self.assertEqual("backlog open: --repo needs a value\n", err)
        self.assertEqual("", out)

    def test_more_than_60_shows_60_and_the_true_total(self):
        # Distinct dates, newest first: B-60 is shown first and the oldest, B-0, is the one cut.
        self.write_index([item("h", "r", f"B-{n}", added=f"2026-{n // 28 + 1:02d}-{n % 28 + 1:02d}")
                          for n in range(61)])
        _r, out, _e = self.capture(self.mod.cmd_open, [])
        lines = out.splitlines()
        shown = [line.split()[2] for line in lines if line.startswith("[")]
        self.assertEqual(60, len(shown))
        self.assertEqual(("B-60", "B-1"), (shown[0], shown[-1]))
        self.assertNotIn("B-0", shown)
        self.assertEqual("(61 open, showing 60)", lines[-1])

    def test_text_is_cut_to_110_characters(self):
        self.write_index([item("h", "r", "B-1", text="x" * 110 + "TAIL-NOT-SHOWN")])
        _r, out, _e = self.capture(self.mod.cmd_open, [])
        self.assertEqual("[----------] h:r B-1        - | " + "x" * 110, out.splitlines()[0])

    def test_repo_value_boundary_flag_last_vs_followed_by_value(self):
        # `_ri >= len(args)`: the flag as the last argument (equal case) refuses; one more argument reads it.
        ret, out, err = self.capture(self.mod.cmd_open, ["x", "--repo"])
        self.assertEqual(2, ret)
        self.assertEqual("backlog open: --repo needs a value\n", err)
        self.assertEqual("", out)
        ret, out, err = self.capture(self.mod.cmd_open, ["--repo", "landing"])
        self.assertIsNone(ret)
        self.assertEqual("", err)
        self.assertEqual("(1 open in landing, showing 1)", out.splitlines()[-1])

    def test_open_host_is_cut_at_the_first_dot(self):
        self.write_index([item("alpha.beta.gamma", "r", "B-1", added="2026-01-01", text="t")])
        _r, out, _e = self.capture(self.mod.cmd_open, [])
        self.assertTrue(out.splitlines()[0].startswith("[2026-01-01] alpha:r B-1"), out)

    def test_without_repo_everything_open_with_repo_only_matches(self):
        # `not repo or repo in ...`: no filter takes every open item, a filter only the matching ones.
        _r, out, _e = self.capture(self.mod.cmd_open, [])
        self.assertEqual("(4 open, showing 4)", out.splitlines()[-1])
        _r, out, _e = self.capture(self.mod.cmd_open, ["--repo", "other"])
        self.assertEqual(["O-1"], [line.split()[2] for line in out.splitlines() if line.startswith("[")])

    def test_open_none_and_absent_added_sort_after_dated_items(self):
        self.write_index([
            {"host": "h", "repo": "r", "item_id": "NONE", "status": "open", "added": None},
            item("h", "r", "OLD", added="2026-01-01"),
            {"host": "h", "repo": "r", "item_id": "ABSENT", "status": "open"},
            item("h", "r", "NEW", added="2026-06-01"),
        ])
        _r, out, _e = self.capture(self.mod.cmd_open, [])
        self.assertEqual(["NEW", "OLD", "NONE", "ABSENT"],
                         [line.split()[2] for line in out.splitlines() if line.startswith("[")])

    def test_open_missing_severity_prints_a_dash_beside_a_real_one(self):
        self.write_index([item("h", "r", "S-1", severity="high", added="2026-02-02"),
                          item("h", "r", "S-2", severity=None, added="2026-01-01")])
        _r, out, _e = self.capture(self.mod.cmd_open, [])
        self.assertEqual(["[2026-02-02] h:r S-1     high | ", "[2026-01-01] h:r S-2        - | "],
                         out.splitlines()[:2])

    def test_repo_value_is_the_argument_right_after_the_flag(self):
        # `args.index('--repo') + 1`: the value is the NEXT argument, not the last one or the flag.
        _r, out, _e = self.capture(self.mod.cmd_open, ["--repo", "landing", "trailing"])
        self.assertEqual("(1 open in landing, showing 1)", out.splitlines()[-1])

    def test_open_repo_without_value_exits_two(self):
        # Regression (cmd_open X1): the dispatch dropped cmd_open's 2, so the PROCESS exited 0.
        r = run_cli(self.tmp, "open", "--repo")
        self.assertEqual(2, r.returncode)
        self.assertEqual("backlog open: --repo needs a value\n", r.stderr)
        self.assertEqual("", r.stdout)


class CmdCritTests(BacklogTestCase):
    def test_open_critical_then_high_oldest_first_upper_cased(self):
        self.write_index([
            item("mac.local", "a", "H-NEW", "open", "high", "2026-05-01", "high new"),
            item("vps", "b", "C-NEW", "open", "critical", "2026-04-01", "crit new"),
            item("vps", "b", "H-OLD", "open", "high", "2026-01-01", "high old"),
            item("vps", "b", "C-OLD", "open", "critical", "2026-02-01", "crit old"),
            item("vps", "b", "C-DONE", "done", "critical", "2026-01-01", "closed"),
            item("vps", "b", "M-1", "open", "medium", "2026-01-01", "medium"),
            item("vps", "b", "N-1", "open", None, "2026-01-01", "none"),
        ])
        _r, out, _e = self.capture(self.mod.cmd_crit)
        self.assertEqual([
            "CRITICAL vps:b C-OLD | crit old",
            "CRITICAL vps:b C-NEW | crit new",
            "    HIGH vps:b H-OLD | high old",
            "    HIGH mac:a H-NEW | high new",
            "",
            "(4 critical/high open across the fleet, showing 4)",
        ], out.splitlines())

    def test_undated_sorts_first_within_its_severity(self):
        self.write_index([item("h", "r", "DATED", "open", "high", "2026-01-01"),
                          item("h", "r", "UNDATED", "open", "high", "")])
        _r, out, _e = self.capture(self.mod.cmd_crit)
        self.assertEqual(["UNDATED", "DATED"], [line.split()[2] for line in out.splitlines()[:2]])

    def test_nothing_critical_reports_zero(self):
        self.write_index([item("h", "r", "L-1", "open", "low")])
        _r, out, _e = self.capture(self.mod.cmd_crit)
        self.assertEqual(["", "(0 critical/high open across the fleet, showing 0)"], out.splitlines())

    def test_crit_host_is_cut_at_the_first_dot(self):
        self.write_index([item("alpha.beta.gamma", "r", "C-1", "open", "critical", text="t")])
        _r, out, _e = self.capture(self.mod.cmd_crit)
        self.assertEqual("CRITICAL alpha:r C-1 | t", out.splitlines()[0])

    def test_crit_done_items_are_never_listed(self):
        self.write_index([item("h", "r", "OPEN", "open", "critical"),
                          item("h", "r", "DONE", "done", "critical")])
        _r, out, _e = self.capture(self.mod.cmd_crit)
        self.assertEqual(["OPEN"], [line.split()[2] for line in out.splitlines() if "|" in line])
        self.assertEqual("(1 critical/high open across the fleet, showing 1)", out.splitlines()[-1])

    def test_crit_critical_sorts_before_high_regardless_of_date(self):
        self.write_index([item("h", "r", "HIGH-OLD", "open", "high", "2020-01-01"),
                          item("h", "r", "CRIT-NEW", "open", "critical", "2026-12-31")])
        _r, out, _e = self.capture(self.mod.cmd_crit)
        self.assertEqual(["CRIT-NEW", "HIGH-OLD"],
                         [line.split()[2] for line in out.splitlines() if "|" in line])


class CmdGrepTests(BacklogTestCase):
    def setUp(self):
        super().setUp()
        self.write_index([
            item("mac.local", "zuvo", "B-1", "open", text="Flaky test in CI"),
            item("vps", "Landing-Site", "L-1", "done", text="broken link"),
            item("vps", "api", "A-1", "open", text="slow query"),
        ])

    def test_no_arguments_exits_with_usage(self):
        msg, _o, _e = self.exit_message(self.mod.cmd_grep, [])
        self.assertEqual("usage: backlog grep <text>", msg)

    def test_text_match_is_case_insensitive(self):
        _r, out, _e = self.capture(self.mod.cmd_grep, ["FLAKY"])
        self.assertEqual(["open mac:zuvo B-1 | Flaky test in CI", "", "(1 matches, showing 1)"],
                         out.splitlines())

    def test_repo_match_is_case_insensitive(self):
        _r, out, _e = self.capture(self.mod.cmd_grep, ["landing"])
        self.assertEqual(["done vps:Landing-Site L-1 | broken link", "", "(1 matches, showing 1)"],
                         out.splitlines())

    def test_arguments_are_joined_with_spaces(self):
        # "slow test" contains "test" but not "test in": only the joined phrase may match.
        self.write_index([item("mac.local", "zuvo", "B-1", "open", text="Flaky test in CI"),
                          item("vps", "api", "T-1", "open", text="slow test")])
        _r, out, _e = self.capture(self.mod.cmd_grep, ["test", "in"])
        self.assertEqual(["open mac:zuvo B-1 | Flaky test in CI", "", "(1 matches, showing 1)"],
                         out.splitlines())

    def test_no_match_reports_zero(self):
        _r, out, _e = self.capture(self.mod.cmd_grep, ["zzz"])
        self.assertEqual(["", "(0 matches, showing 0)"], out.splitlines())

    def test_grep_query_spanning_text_and_repo_is_not_a_match(self):
        # Regression (cmd_grep X2): text and repo were concatenated, so "cd" matched text "abc" + repo "def".
        self.write_index([item("h", "def", "S-1", text="abc")])
        _r, out, _e = self.capture(self.mod.cmd_grep, ["cd"])
        self.assertEqual(["", "(0 matches, showing 0)"], out.splitlines())

    def test_grep_matches_either_field_alone(self):
        # `q in text or q in repo`: T-1 matches on text only, R-1 on repo only, N-1 on neither.
        self.write_index([item("h", "alpha", "T-1", text="Needle here"),
                          item("h", "needle-repo", "R-1", text="other"),
                          item("h", "x", "N-1", text="nothing")])
        _r, out, _e = self.capture(self.mod.cmd_grep, ["NEEDLE"])
        self.assertEqual(["T-1", "R-1"], [line.split()[2] for line in out.splitlines() if "|" in line])
        self.assertEqual("(2 matches, showing 2)", out.splitlines()[-1])


class CmdStraysTests(BacklogTestCase):
    def test_no_meta_means_clean(self):
        self.write_index([])
        _r, out, _e = self.capture(self.mod.cmd_strays)
        self.assertEqual("no worktree-fork backlog copies — clean ✓\n", out)

    def test_empty_strays_means_clean(self):
        self.write_index([], meta={"strays": []})
        _r, out, _e = self.capture(self.mod.cmd_strays)
        self.assertEqual("no worktree-fork backlog copies — clean ✓\n", out)

    def test_strays_are_listed_with_the_host_cut_at_the_first_dot(self):
        self.write_index([], meta={"strays": [{"host": "mac.local.lan", "path": "/wt/a/memory/backlog.md"},
                                              {"host": "vps", "path": "/wt/b/memory/backlog.md"}]})
        _r, out, _e = self.capture(self.mod.cmd_strays)
        self.assertEqual([
            "2 worktree-fork copies (protocol says ONE backlog per repo, at the MAIN checkout):",
            "  mac: /wt/a/memory/backlog.md",
            "  vps: /wt/b/memory/backlog.md",
        ], out.splitlines())

    def test_clean_until_a_stray_appears_then_one_line_each(self):
        self.write_index([], meta={"strays": []})
        _r, out, _e = self.capture(self.mod.cmd_strays)
        self.assertEqual(["no worktree-fork backlog copies — clean ✓"], out.splitlines())
        self.write_index([], meta={"strays": [{"host": "box.lan", "path": "/wt/x"}]})
        _r, out, _e = self.capture(self.mod.cmd_strays)
        self.assertEqual(["1 worktree-fork copies (protocol says ONE backlog per repo, "
                          "at the MAIN checkout):", "  box: /wt/x"], out.splitlines())


class DispatchTests(BacklogTestCase):
    """`__main__`: the real file as a real process in a sandbox with no collector configured."""

    def setUp(self):
        super().setUp()
        self.write_index([item("mac.local", "zuvo", "B-1", "open", "critical", "2026-01-01", "flaky gate")],
                         meta={"hosts": {"mac.local": {}}, "strays": [{"host": "mac.local", "path": "/wt"}]})

    def test_no_argument_runs_ls(self):
        r = run_cli(self.tmp)
        self.assertEqual(0, r.returncode, r.stderr)
        self.assertIn("mac:zuvo", r.stdout)
        self.assertEqual("TOTAL open=1 done=0 across 1 repos / 1 hosts", r.stdout.splitlines()[-1])

    def test_unknown_command_exits_1_with_usage_on_stderr(self):
        r = run_cli(self.tmp, "nope")
        self.assertEqual(1, r.returncode)
        self.assertTrue(r.stderr.startswith("zuvo backlog — ONE place for every backlog in the fleet"))
        self.assertIn("~/.zuvo/backlog grep <text>       full-text search across every backlog", r.stderr)
        self.assertEqual("", r.stdout)

    def test_grep_without_text_exits_1_with_usage(self):
        r = run_cli(self.tmp, "grep")
        self.assertEqual(1, r.returncode)
        self.assertEqual("usage: backlog grep <text>\n", r.stderr)

    def test_each_view_command_routes_to_its_function(self):
        cases = {
            ("ls",): "TOTAL open=1",
            ("open",): "(1 open, showing 1)",
            ("open", "--repo", "zuvo"): "(1 open in zuvo, showing 1)",
            ("crit",): "(1 critical/high open across the fleet, showing 1)",
            ("grep", "FLAKY"): "(1 matches, showing 1)",
            ("strays",): "  mac: /wt",
        }
        for args, marker in cases.items():
            with self.subTest(args=args):
                r = run_cli(self.tmp, *args)
                self.assertEqual(0, r.returncode, r.stderr)
                self.assertIn(marker, r.stdout)

    def test_pull_and_sync_route_to_the_collector_and_name_the_missing_host(self):
        for cmd, what in (("pull", "pull the fleet index"), ("sync", "fetch the collector token")):
            with self.subTest(cmd=cmd):
                r = run_cli(self.tmp, cmd)
                self.assertEqual(1, r.returncode)
                self.assertEqual("backlog: no collector host configured (ZUVO_COLLECTOR_SSH or "
                                 f"~/.zuvo/collector.conf) — cannot {what}\n", r.stderr)

    def test_argument_count_boundary_no_arg_is_ls_one_arg_is_the_command(self):
        # `len(sys.argv) > 1`: argv of length 1 (equal case) runs ls; length 2 runs the named command.
        r = run_cli(self.tmp)
        self.assertEqual(0, r.returncode, r.stderr)
        self.assertEqual("TOTAL open=1 done=0 across 1 repos / 1 hosts", r.stdout.splitlines()[-1])
        r = run_cli(self.tmp, "strays")
        self.assertEqual(0, r.returncode, r.stderr)
        self.assertEqual(["1 worktree-fork copies (protocol says ONE backlog per repo, "
                          "at the MAIN checkout):", "  mac: /wt"], r.stdout.splitlines())

    def test_missing_index_names_the_script_path(self):
        os.remove(self.mod.INDEX)
        r = run_cli(self.tmp, "ls")
        self.assertEqual(1, r.returncode)
        self.assertIn("no index yet — run: ", r.stderr)
        self.assertIn("scripts/zuvo-home/backlog sync", r.stderr)


class BlindAuditFollowUpViewTests(BacklogTestCase):
    """Rows the blind coverage audit found uncovered or partly covered (pass 1: FIX)."""

    def test_crit_shows_sixty_and_reports_the_true_total(self):
        # Distinct dates, oldest first: C-00 leads and the newest, C-60, is the one cut.
        self.write_index([item("h", "r", f"C-{n:02d}", "open", "critical",
                               f"2026-{n // 28 + 1:02d}-{n % 28 + 1:02d}") for n in range(61)])
        _r, out, _e = self.capture(self.mod.cmd_crit)
        lines = out.splitlines()
        shown = [line.split()[2] for line in lines if line.startswith("CRITICAL ")]
        self.assertEqual(60, len(shown))
        self.assertEqual(("C-00", "C-59"), (shown[0], shown[-1]))
        self.assertNotIn("C-60", shown)
        self.assertEqual("(61 critical/high open across the fleet, showing 60)", lines[-1])

    def test_crit_cuts_text_at_110_characters(self):
        text = "a" * 110 + "TAIL-NOT-SHOWN"
        self.write_index([item("h", "r", "C-1", "open", "high", "2026-01-01", text)])
        _r, out, _e = self.capture(self.mod.cmd_crit)
        self.assertEqual("    HIGH h:r C-1 | " + "a" * 110, out.splitlines()[0])

    def test_grep_shows_sixty_and_reports_the_true_total(self):
        # Index order is kept: G-00..G-59 are shown, G-60 is the one cut.
        self.write_index([item("h", "r", f"G-{n:02d}", text="needle") for n in range(61)])
        _r, out, _e = self.capture(self.mod.cmd_grep, ["needle"])
        lines = out.splitlines()
        shown = [line.split()[2] for line in lines if line.endswith("| needle")]
        self.assertEqual([f"G-{n:02d}" for n in range(60)], shown)
        self.assertEqual("(61 matches, showing 60)", lines[-1])

    def test_grep_tolerates_items_missing_status_text_or_repo(self):
        self.write_index([
            {"host": "h.local", "item_id": "NO-TEXT", "repo": "findme-repo"},
            {"host": "h", "item_id": "NO-REPO", "status": "done", "text": "Findme in text"},
        ])
        _r, out, _e = self.capture(self.mod.cmd_grep, ["FINDME"])
        self.assertEqual(["   ? h:findme-repo NO-TEXT | ", "done h:None NO-REPO | Findme in text", "",
                          "(2 matches, showing 2)"], out.splitlines())


class PolyglotHeaderTests(BacklogTestCase):
    """The file as production runs it: /bin/sh reads the header and re-execs a Python 3."""

    def setUp(self):
        super().setUp()
        self.empty = os.path.join(self.tmp, "empty-bin")
        os.makedirs(self.empty)
        # cmd_open loads the index before it parses --repo; without one it exits "no index yet".
        self.write_index([item("h", "r", "B-1")])

    def run_sh(self, path_dirs, *args):
        env = {"PATH": os.pathsep.join(path_dirs), "HOME": self.tmp,
               "ZUVO_DIR": self.zuvo, "ZUVO_COLLECTOR_SSH": ""}
        # REAL_RUN: the harness patches subprocess.run module-wide for the fake collector.
        return REAL_RUN(["/bin/sh", str(BACKLOG), *args], capture_output=True, text=True,
                        env=env, timeout=60)

    def test_sh_entry_reexecs_python3_and_forwards_argv_and_status(self):
        py_dir = os.path.join(self.tmp, "py3")
        os.makedirs(py_dir)
        os.symlink(os.path.realpath(sys.executable), os.path.join(py_dir, "python3"))
        r = self.run_sh([py_dir, self.empty], "open", "--repo")
        self.assertEqual(2, r.returncode)
        self.assertEqual("backlog open: --repo needs a value\n", r.stderr)
        self.assertEqual("", r.stdout)

    def test_sh_entry_falls_back_to_python_when_python3_is_absent(self):
        py_dir = os.path.join(self.tmp, "py")
        os.makedirs(py_dir)
        os.symlink(os.path.realpath(sys.executable), os.path.join(py_dir, "python"))
        r = self.run_sh([py_dir, self.empty], "open", "--repo")
        self.assertEqual(2, r.returncode)
        self.assertEqual("backlog open: --repo needs a value\n", r.stderr)
        self.assertEqual("", r.stdout)

    def test_sh_entry_with_no_python_at_all_execs_python3_and_fails_not_found(self):
        r = self.run_sh([self.empty], "ls")
        self.assertEqual(127, r.returncode)
        self.assertIn("python3", r.stderr)
        self.assertEqual("", r.stdout)



class FleetDataRobustnessTests(BacklogTestCase):
    """The index is fleet-supplied: unknown statuses and null fields must not break a view."""

    def test_ls_counts_only_open_and_done_and_an_odd_status_cannot_clobber_the_row(self):
        # Regression: the status was used as a dict key on the row, so status "oldest" replaced the
        # oldest date with a count and the next date comparison raised TypeError.
        self.write_index([
            item("h", "r", "A-1", "open", added="2026-02-01"),
            item("h", "r", "A-2", "oldest", added="2026-03-01"),
            item("h", "r", "A-3", "done", added="2026-01-15"),
            item("h", "r", "A-4", "in_progress", added="2026-04-01"),
        ], meta={"hosts": {"h": {}}})
        _r, out, _e = self.capture(self.mod.cmd_ls)
        rows, _order = ls_rows(out)
        self.assertEqual({"h:r": (1, 1, "2026-01-15")}, rows)
        self.assertEqual("TOTAL open=1 done=1 across 1 repos / 1 hosts", out.splitlines()[-1])

    def test_views_survive_null_text_repo_host_and_severity(self):
        # Regression: i.get("text", "") returns None for a key that is present with null, and
        # None.lower() / None[:110] / None.split() raised in grep, open and crit.
        nulls = {"host": None, "repo": None, "item_id": "N-1", "status": "open",
                 "severity": None, "added": None, "text": None}
        crit_null = dict(nulls, item_id="N-2", severity="high")
        self.write_index([nulls, crit_null, item("h", "needle-repo", "R-1", text="plain")])
        _r, out, _e = self.capture(self.mod.cmd_grep, ["needle"])
        self.assertEqual(["open h:needle-repo R-1 | plain", "", "(1 matches, showing 1)"], out.splitlines())
        _r, out, _e = self.capture(self.mod.cmd_open, [])
        self.assertIn("[----------] ?:None N-1        - | ", out.splitlines())
        _r, out, _e = self.capture(self.mod.cmd_open, ["--repo", "needle"])
        self.assertEqual("(1 open in needle, showing 1)", out.splitlines()[-1])
        _r, out, _e = self.capture(self.mod.cmd_crit)
        self.assertEqual(["    HIGH ?:None N-2 | ", "", "(1 critical/high open across the fleet, showing 1)"],
                         out.splitlines())


if __name__ == "__main__":
    unittest.main()
